/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { HTTPValidationError } from "./HTTPValidationError"
import type { TradeOfferView } from "./TradeOfferView"

export type AcceptListingPathParams = {
  /**
   * @type string, uuid
   */
  listing_id: string
}

/**
 * TradeOfferView
 * @description Successful Response
 */
export type AcceptListing200 = TradeOfferView

/**
 * HTTPValidationError
 * @description Validation Error
 */
export type AcceptListing422 = HTTPValidationError

export type AcceptListingMutationResponse = AcceptListing200

export type AcceptListingMutation = {
  Response: AcceptListing200
  PathParams: AcceptListingPathParams
  Errors: AcceptListing422
}
