/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { AddCardRequest } from "./AddCardRequest"
import type { CollectionItemView } from "./CollectionItemView"
import type { HTTPValidationError } from "./HTTPValidationError"

/**
 * CollectionItemView
 * @description Successful Response
 */
export type AddCard201 = CollectionItemView

/**
 * HTTPValidationError
 * @description Validation Error
 */
export type AddCard422 = HTTPValidationError

/**
 * AddCardRequest
 */
export type AddCardMutationRequest = AddCardRequest

export type AddCardMutationResponse = AddCard201

export type AddCardMutation = {
  Response: AddCard201
  Request: AddCardMutationRequest
  Errors: AddCard422
}
