/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { AddWishlistRequest } from "./AddWishlistRequest"
import type { HTTPValidationError } from "./HTTPValidationError"
import type { WishlistItemView } from "./WishlistItemView"

/**
 * WishlistItemView
 * @description Successful Response
 */
export type AddToWishlist201 = WishlistItemView

/**
 * HTTPValidationError
 * @description Validation Error
 */
export type AddToWishlist422 = HTTPValidationError

/**
 * AddWishlistRequest
 */
export type AddToWishlistMutationRequest = AddWishlistRequest

export type AddToWishlistMutationResponse = AddToWishlist201

export type AddToWishlistMutation = {
  Response: AddToWishlist201
  Request: AddToWishlistMutationRequest
  Errors: AddToWishlist422
}
