/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * AddWishlistRequest
 */
export type AddWishlistRequest = {
  /**
   * @type string
   */
  card_id: string
  reason?: string | null
  /**
   * @minLength 0
   * @maxLength 3
   * @default 0
   * @type integer | undefined
   */
  priority?: number
}
