/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { HTTPValidationError } from "./HTTPValidationError"
import type { TradeListingView } from "./TradeListingView"

export type CancelListingPathParams = {
  /**
   * @type string, uuid
   */
  listing_id: string
}

/**
 * TradeListingView
 * @description Successful Response
 */
export type CancelListing200 = TradeListingView

/**
 * HTTPValidationError
 * @description Validation Error
 */
export type CancelListing422 = HTTPValidationError

export type CancelListingMutationResponse = CancelListing200

export type CancelListingMutation = {
  Response: CancelListing200
  PathParams: CancelListingPathParams
  Errors: CancelListing422
}
