/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CardView } from "./CardView"

/**
 * CardCandidate
 */
export type CardCandidate = {
  /**
   * @description A card with both layers: what is printed, and the species it depicts.
   * @type object
   */
  card: CardView
  /**
   * @type number
   */
  score: number
  /**
   * @type array
   */
  matched_on: string[]
}
