/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CardSetView } from "./CardSetView"
import type { SpeciesView } from "./SpeciesView"

/**
 * CardView
 * @description A card with both layers: what is printed, and the species it depicts.
 */
export type CardView = {
  /**
   * @type string
   */
  id: string
  /**
   * @type string
   */
  name: string
  /**
   * @type string
   */
  category: string
  /**
   * @type string
   */
  number: string
  rarity: string | null
  /**
   * @type object
   */
  variants: {
    [key: string]: boolean
  }
  hp: number | null
  image_small_url: string | null
  image_large_url: string | null
  /**
   * @type object
   */
  card_set: CardSetView
  species: SpeciesView | null
}
