/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const cardReadingRaritySymbolEnum = {
  circle: "circle",
  diamond: "diamond",
  star: "star",
  none: "none",
} as const

export type CardReadingRaritySymbolEnumKey =
  (typeof cardReadingRaritySymbolEnum)[keyof typeof cardReadingRaritySymbolEnum]

export const cardReadingConfidenceEnum = {
  high: "high",
  medium: "medium",
  low: "low",
} as const

export type CardReadingConfidenceEnumKey =
  (typeof cardReadingConfidenceEnum)[keyof typeof cardReadingConfidenceEnum]

/**
 * CardReading
 * @description What is PRINTED on the card. It does not identify: it transcribes.\n\nMerging transcription and identification is what makes these features\nhallucinate a card that fits what the model thinks it saw.
 */
export type CardReading = {
  name?: string | null
  collector_number?: string | null
  set_total?: number | null
  set_symbol_text?: string | null
  hp?: number | null
  rarity_symbol?: CardReadingRaritySymbolEnumKey | null
  /**
   * @type array | undefined
   */
  variant_hints?: string[]
  /**
   * @default "low"
   * @type string | undefined
   */
  confidence?: CardReadingConfidenceEnumKey
}
