/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * CardSetView
 */
export type CardSetView = {
  /**
   * @type string
   */
  id: string
  /**
   * @type string
   */
  name: string
  series: string | null
  /**
   * @type integer
   */
  printed_total: number
  release_date: string | null
  logo_url: string | null
}
