/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const cardConditionEnum = {
  mint: "mint",
  near_mint: "near_mint",
  lightly_played: "lightly_played",
  moderately_played: "moderately_played",
  heavily_played: "heavily_played",
  damaged: "damaged",
} as const

export type CardConditionEnumKey =
  (typeof cardConditionEnum)[keyof typeof cardConditionEnum]

/**
 * CardCondition
 */
export type CardCondition = CardConditionEnumKey
