/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ActivityEntry } from "./ActivityEntry"

/**
 * Response Collection Activity
 * @description Successful Response
 */
export type CollectionActivity200 = ActivityEntry[]

export type CollectionActivityQueryResponse = CollectionActivity200

export type CollectionActivityQuery = {
  Response: CollectionActivity200
  Errors: any
}
