/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CardCondition } from "./CardCondition"
import type { CardView } from "./CardView"

/**
 * CollectionItemView
 */
export type CollectionItemView = {
  /**
   * @type string, uuid
   */
  id: string
  /**
   * @type integer
   */
  quantity: number
  /**
   * @type string
   */
  condition: CardCondition
  /**
   * @type string
   */
  language: string
  /**
   * @type boolean
   */
  is_graded: boolean
  grade: number | null
  notes: string | null
  acquired_at: string | null
  /**
   * @type string, date-time
   */
  created_at: string
  /**
   * @description A card with both layers: what is printed, and the species it depicts.
   * @type object
   */
  card: CardView
}
