/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CollectionValue } from "./CollectionValue"
import type { GenerationCount } from "./GenerationCount"
import type { SetCoverage } from "./SetCoverage"
import type { TypeCount } from "./TypeCount"

/**
 * CollectionStats
 */
export type CollectionStats = {
  /**
   * @type integer
   */
  total_groups: number
  /**
   * @type integer
   */
  total_cards: number
  /**
   * @description What the collection is worth, and how much of it could be priced.\n\nThe coverage travels with the total because most cards have no market price;\na figure without it would read as complete when it is not.
   * @type object
   */
  value: CollectionValue
  /**
   * @type array
   */
  types: TypeCount[]
  /**
   * @type array
   */
  generations: GenerationCount[]
  /**
   * @type array
   */
  sets: SetCoverage[]
}

/**
 * CollectionStats
 * @description Successful Response
 */
export type CollectionStats200 = CollectionStats

export type CollectionStatsQueryResponse = CollectionStats200

export type CollectionStatsQuery = {
  Response: CollectionStats200
  Errors: any
}
