/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * CollectorView
 * @description Another collector, described only by what could move between you.\n\nTheir collection stays theirs: what is published is how much is spare and\nhow much of it either of you is short of.
 */
export type CollectorView = {
  /**
   * @type string
   */
  user_id: string
  name: string | null
  /**
   * @type integer
   */
  spares: number
  /**
   * @type integer
   */
  you_want: number
  /**
   * @type integer
   */
  they_want: number
}
