/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ProfileSet } from "./ProfileSet"

/**
 * CollectorProfile
 * @description A collector as another collector may see them.\n\nDeliberately not a portfolio: what a collection is worth is a claim about a\nperson, and it stays with them. What is published is what could move — how\nmuch is spare, what each of you is short of — plus the shape of what they\ncollect, which is what tells you whether it is worth talking to them.
 */
export type CollectorProfile = {
  /**
   * @type string
   */
  user_id: string
  name: string | null
  /**
   * @type boolean
   */
  is_self: boolean
  joined_at: string | null
  /**
   * @type integer
   */
  cards: number
  /**
   * @type integer
   */
  distinct_cards: number
  /**
   * @type integer
   */
  spares: number
  /**
   * @type integer
   */
  wants: number
  /**
   * @type integer
   */
  you_want: number
  /**
   * @type integer
   */
  they_want: number
  /**
   * @type array
   */
  sets: ProfileSet[]
}
