/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { GenerationCount } from "./GenerationCount"
import type { SetCoverage } from "./SetCoverage"
import type { TypeCount } from "./TypeCount"

/**
 * CollectionStats
 */
export type CollectionStats = {
  /**
   * @type integer
   */
  total_groups: number
  /**
   * @type integer
   */
  total_cards: number
  /**
   * @type array
   */
  types: TypeCount[]
  /**
   * @type array
   */
  generations: GenerationCount[]
  /**
   * @type array
   */
  sets: SetCoverage[]
}

/**
 * CollectionStats
 * @description Successful Response
 */
export type CollectionStats200 = CollectionStats

export type CollectionStatsQueryResponse = CollectionStats200

export type CollectionStatsQuery = {
  Response: CollectionStats200
  Errors: any
}
