/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * CollectionValue
 * @description What the collection is worth, and how much of it could be priced.\n\nThe coverage travels with the total because most cards have no market price;\na figure without it would read as complete when it is not.
 */
export type CollectionValue = {
  /**
   * @pattern ^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$
   * @type string
   */
  total_eur: string
  /**
   * @type integer
   */
  priced_cards: number
  /**
   * @type integer
   */
  unpriced_cards: number
}
