/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { HTTPValidationError } from "./HTTPValidationError"
import type { VisualComparison } from "./VisualComparison"

export type CompareCardsQueryParams = {
  /**
   * @type string
   */
  a: string
  /**
   * @type string
   */
  b: string
}

/**
 * VisualComparison
 * @description Successful Response
 */
export type CompareCards200 = VisualComparison

/**
 * HTTPValidationError
 * @description Validation Error
 */
export type CompareCards422 = HTTPValidationError

export type CompareCardsQueryResponse = CompareCards200

export type CompareCardsQuery = {
  Response: CompareCards200
  QueryParams: CompareCardsQueryParams
  Errors: CompareCards422
}
