/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * ConcentrationBucket
 * @description What the largest `cards` positions add up to.
 */
export type ConcentrationBucket = {
  /**
   * @type integer
   */
  cards: number
  /**
   * @pattern ^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$
   * @type string
   */
  value: string
  /**
   * @type number
   */
  share: number
}
