/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CardCondition } from "./CardCondition"

/**
 * ConditionCount
 */
export type ConditionCount = {
  /**
   * @type string
   */
  condition: CardCondition
  /**
   * @type integer
   */
  copies: number
}
