/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { AddCardRequest } from "./AddCardRequest"
import type { HTTPValidationError } from "./HTTPValidationError"

export type ConfirmScanPathParams = {
  /**
   * @type string, uuid
   */
  scan_id: string
}

/**
 * Response Confirm Scan
 * @description Successful Response
 */
export type ConfirmScan201 = any

/**
 * HTTPValidationError
 * @description Validation Error
 */
export type ConfirmScan422 = HTTPValidationError

/**
 * AddCardRequest
 */
export type ConfirmScanMutationRequest = AddCardRequest

export type ConfirmScanMutationResponse = ConfirmScan201

export type ConfirmScanMutation = {
  Response: ConfirmScan201
  Request: ConfirmScanMutationRequest
  PathParams: ConfirmScanPathParams
  Errors: ConfirmScan422
}
