/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * ConversationView
 */
export type ConversationView = {
  /**
   * @type string, uuid
   */
  id: string
  /**
   * @type string
   */
  title: string
  /**
   * @type string, date-time
   */
  created_at: string
  /**
   * @type string, date-time
   */
  updated_at: string
}
