/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { MessageView } from "./MessageView"

/**
 * ConversationDetail
 */
export type ConversationDetail = {
  /**
   * @type string, uuid
   */
  id: string
  /**
   * @type string
   */
  title: string
  /**
   * @type string, date-time
   */
  created_at: string
  /**
   * @type string, date-time
   */
  updated_at: string
  /**
   * @type array
   */
  messages: MessageView[]
}
