/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { OfferCardInput } from "./OfferCardInput"

/**
 * CreateListingRequest
 * @description Wanted cards are ids alone: a state can only be promised by whoever holds\nthe card, and on this side nobody holds it yet.
 */
export type CreateListingRequest = {
  /**
   * @type array
   */
  give: OfferCardInput[]
  /**
   * @type array
   */
  want: string[]
  note?: string | null
}
