/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * CreateOfferRequest
 */
export type CreateOfferRequest = {
  /**
   * @type string
   */
  to_user_id: string
  /**
   * @type array
   */
  offered: string[]
  /**
   * @type array
   */
  requested: string[]
  message?: string | null
}
