/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CreateOfferRequest } from "./CreateOfferRequest"
import type { HTTPValidationError } from "./HTTPValidationError"
import type { TradeOfferView } from "./TradeOfferView"

/**
 * TradeOfferView
 * @description Successful Response
 */
export type CreateOffer201 = TradeOfferView

/**
 * HTTPValidationError
 * @description Validation Error
 */
export type CreateOffer422 = HTTPValidationError

/**
 * CreateOfferRequest
 */
export type CreateOfferMutationRequest = CreateOfferRequest

export type CreateOfferMutationResponse = CreateOffer201

export type CreateOfferMutation = {
  Response: CreateOffer201
  Request: CreateOfferMutationRequest
  Errors: CreateOffer422
}
