/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BodyCreateScan } from "./BodyCreateScan"
import type { HTTPValidationError } from "./HTTPValidationError"
import type { ScanResult } from "./ScanResult"

/**
 * ScanResult
 * @description Successful Response
 */
export type CreateScan201 = ScanResult

/**
 * HTTPValidationError
 * @description Validation Error
 */
export type CreateScan422 = HTTPValidationError

/**
 * Body_create_scan
 */
export type CreateScanMutationRequest = BodyCreateScan

export type CreateScanMutationResponse = CreateScan201

export type CreateScanMutation = {
  Response: CreateScan201
  Request: CreateScanMutationRequest
  Errors: CreateScan422
}
