/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { OfferCardInput } from "./OfferCardInput"

/**
 * CreateOfferRequest
 */
export type CreateOfferRequest = {
  /**
   * @type string
   */
  to_user_id: string
  /**
   * @type array
   */
  offered: OfferCardInput[]
  /**
   * @type array
   */
  requested: OfferCardInput[]
  message?: string | null
}
