/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ShareLinkView } from "./ShareLinkView"

/**
 * ShareLinkView
 * @description Successful Response
 */
export type CreateShareLink201 = ShareLinkView

export type CreateShareLinkMutationResponse = CreateShareLink201

export type CreateShareLinkMutation = {
  Response: CreateShareLink201
  Errors: any
}
