/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * DirectMessageView
 * @description One message, told from the reader\'s side.\n\n`mine` is resolved per reader rather than stored: the same row is on the\nleft for one of the two and on the right for the other.
 */
export type DirectMessageView = {
  /**
   * @type string, uuid
   */
  id: string
  /**
   * @type string, uuid
   */
  thread_id: string
  /**
   * @type string
   */
  sender_id: string
  /**
   * @type boolean
   */
  mine: boolean
  /**
   * @type string
   */
  body: string
  /**
   * @type string, date-time
   */
  created_at: string
  read_at: string | null
}
