/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * EvolutionMemberView
 * @description One species of an evolution family, as its own Pokedex entry.
 */
export type EvolutionMemberView = {
  /**
   * @type integer
   */
  id: number
  /**
   * @type string
   */
  name: string
  /**
   * @type array
   */
  types: string[]
  sprite_url: string | null
  /**
   * @type boolean
   */
  owned: boolean
  /**
   * @type boolean
   */
  is_current: boolean
}
