/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * EvolutionMemberView
 * @description One species of an evolution family, as the card that stands for it.\n\nThe sprite stays for the members the catalog prints no card of, which is the\nonly case the line has nothing to show.
 */
export type EvolutionMemberView = {
  /**
   * @type integer
   */
  id: number
  /**
   * @type string
   */
  name: string
  /**
   * @type array
   */
  types: string[]
  sprite_url: string | null
  card_id: string | null
  card_name: string | null
  card_image_url: string | null
  card_category: string | null
  /**
   * @type boolean
   */
  owned: boolean
  /**
   * @type boolean
   */
  is_current: boolean
}
