/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { HTTPValidationError } from "./HTTPValidationError"

export const exportCollectionQueryParamsFormatEnum = {
  csv: "csv",
  json: "json",
} as const

export type ExportCollectionQueryParamsFormatEnumKey =
  (typeof exportCollectionQueryParamsFormatEnum)[keyof typeof exportCollectionQueryParamsFormatEnum]

export type ExportCollectionQueryParams = {
  /**
   * @default "csv"
   * @type string | undefined
   */
  format?: ExportCollectionQueryParamsFormatEnumKey
}

/**
 * @description Successful Response
 */
export type ExportCollection200 = any

/**
 * HTTPValidationError
 * @description Validation Error
 */
export type ExportCollection422 = HTTPValidationError

export type ExportCollectionQueryResponse = ExportCollection200

export type ExportCollectionQuery = {
  Response: ExportCollection200
  QueryParams: ExportCollectionQueryParams
  Errors: ExportCollection422
}
