/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { HTTPValidationError } from "./HTTPValidationError"

export type ForgetPreferencePathParams = {
  /**
   * @type string
   */
  key: string
}

/**
 * @description Successful Response
 */
export type ForgetPreference204 = any

/**
 * HTTPValidationError
 * @description Validation Error
 */
export type ForgetPreference422 = HTTPValidationError

export type ForgetPreferenceMutationResponse = ForgetPreference204

export type ForgetPreferenceMutation = {
  Response: ForgetPreference204
  PathParams: ForgetPreferencePathParams
  Errors: ForgetPreference422
}
