/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * GenerationCount
 */
export type GenerationCount = {
  /**
   * @type integer
   */
  generation: number
  /**
   * @type integer
   */
  count: number
}
