/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ConversationDetail } from "./ConversationDetail"
import type { HTTPValidationError } from "./HTTPValidationError"

export type GetConversationPathParams = {
  /**
   * @type string, uuid
   */
  conversation_id: string
}

/**
 * ConversationDetail
 * @description Successful Response
 */
export type GetConversation200 = ConversationDetail

/**
 * HTTPValidationError
 * @description Validation Error
 */
export type GetConversation422 = HTTPValidationError

export type GetConversationQueryResponse = GetConversation200

export type GetConversationQuery = {
  Response: GetConversation200
  PathParams: GetConversationPathParams
  Errors: GetConversation422
}
