/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ShareLinkView } from "./ShareLinkView"

/**
 * Response Get Share Link
 * @description Successful Response
 */
export type GetShareLink200 = ShareLinkView | null

export type GetShareLinkQueryResponse = GetShareLink200

export type GetShareLinkQuery = {
  Response: GetShareLink200
  Errors: any
}
