/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { HTTPValidationError } from "./HTTPValidationError"

export type GetScanImagePathParams = {
  /**
   * @type string, uuid
   */
  scan_id: string
}

/**
 * @description Successful Response
 */
export type GetScanImage200 = any

/**
 * HTTPValidationError
 * @description Validation Error
 */
export type GetScanImage422 = HTTPValidationError

export type GetScanImageQueryResponse = GetScanImage200

export type GetScanImageQuery = {
  Response: GetScanImage200
  PathParams: GetScanImagePathParams
  Errors: GetScanImage422
}
