/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { HTTPValidationError } from "./HTTPValidationError"
import type { ThreadView } from "./ThreadView"

export type GetThreadWithPathParams = {
  /**
   * @type string
   */
  partner_id: string
}

/**
 * ThreadView
 * @description Successful Response
 */
export type GetThreadWith200 = ThreadView

/**
 * HTTPValidationError
 * @description Validation Error
 */
export type GetThreadWith422 = HTTPValidationError

export type GetThreadWithQueryResponse = GetThreadWith200

export type GetThreadWithQuery = {
  Response: GetThreadWith200
  PathParams: GetThreadWithPathParams
  Errors: GetThreadWith422
}
