/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * Response Health
 * @description Successful Response
 */
export type Health200 = {
  [key: string]: string
}

export type HealthQueryResponse = Health200

export type HealthQuery = {
  Response: Health200
  Errors: any
}
