/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { HTTPValidationError } from "./HTTPValidationError"
import type { PageThreadView } from "./PageThreadView"

export type ListThreadsQueryParams = {
  search?: string | null
  /**
   * @minLength 1
   * @maxLength 50
   * @default 12
   * @type integer | undefined
   */
  limit?: number
  /**
   * @minLength 0
   * @default 0
   * @type integer | undefined
   */
  offset?: number
}

/**
 * Page[ThreadView]
 * @description Successful Response
 */
export type ListThreads200 = PageThreadView

/**
 * HTTPValidationError
 * @description Validation Error
 */
export type ListThreads422 = HTTPValidationError

export type ListThreadsQueryResponse = ListThreads200

export type ListThreadsQuery = {
  Response: ListThreads200
  QueryParams: ListThreadsQueryParams
  Errors: ListThreads422
}
