/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const listingStatusEnum = {
  open: "open",
  taken: "taken",
  cancelled: "cancelled",
} as const

export type ListingStatusEnumKey =
  (typeof listingStatusEnum)[keyof typeof listingStatusEnum]

/**
 * ListingStatus
 */
export type ListingStatus = ListingStatusEnumKey
