/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { HTTPValidationError } from "./HTTPValidationError"
import type { OfferStatus } from "./OfferStatus"
import type { PageTradeOfferView } from "./PageTradeOfferView"

export const listOffersQueryParamsDirectionEnum = {
  sent: "sent",
  received: "received",
} as const

export type ListOffersQueryParamsDirectionEnumKey =
  (typeof listOffersQueryParamsDirectionEnum)[keyof typeof listOffersQueryParamsDirectionEnum]

export type ListOffersQueryParams = {
  status_filter?: OfferStatus | null
  direction?: ListOffersQueryParamsDirectionEnumKey | null
  /**
   * @minLength 1
   * @maxLength 50
   * @default 10
   * @type integer | undefined
   */
  limit?: number
  /**
   * @minLength 0
   * @default 0
   * @type integer | undefined
   */
  offset?: number
}

/**
 * Page[TradeOfferView]
 * @description Successful Response
 */
export type ListOffers200 = PageTradeOfferView

/**
 * HTTPValidationError
 * @description Validation Error
 */
export type ListOffers422 = HTTPValidationError

export type ListOffersQueryResponse = ListOffers200

export type ListOffersQuery = {
  Response: ListOffers200
  QueryParams: ListOffersQueryParams
  Errors: ListOffers422
}
