/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { HTTPValidationError } from "./HTTPValidationError"
import type { PageCollectorView } from "./PageCollectorView"

export type ListCollectorsQueryParams = {
  search?: string | null
  /**
   * @minLength 1
   * @maxLength 50
   * @default 12
   * @type integer | undefined
   */
  limit?: number
  /**
   * @minLength 0
   * @default 0
   * @type integer | undefined
   */
  offset?: number
}

/**
 * Page[CollectorView]
 * @description Successful Response
 */
export type ListCollectors200 = PageCollectorView

/**
 * HTTPValidationError
 * @description Validation Error
 */
export type ListCollectors422 = HTTPValidationError

export type ListCollectorsQueryResponse = ListCollectors200

export type ListCollectorsQuery = {
  Response: ListCollectors200
  QueryParams: ListCollectorsQueryParams
  Errors: ListCollectors422
}
