/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { PreferenceView } from "./PreferenceView"

/**
 * Response List Preferences
 * @description Successful Response
 */
export type ListPreferences200 = PreferenceView[]

export type ListPreferencesQueryResponse = ListPreferences200

export type ListPreferencesQuery = {
  Response: ListPreferences200
  Errors: any
}
