/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { HTTPValidationError } from "./HTTPValidationError"
import type { ListingStatus } from "./ListingStatus"
import type { PageTradeListingView } from "./PageTradeListingView"

export type ListListingsQueryParams = {
  search?: string | null
  fulfillable?: boolean | null
  mine?: boolean | null
  /**
   * @default "open"
   * @type string | undefined
   */
  status_filter?: ListingStatus
  /**
   * @minLength 1
   * @maxLength 50
   * @default 6
   * @type integer | undefined
   */
  limit?: number
  /**
   * @minLength 0
   * @default 0
   * @type integer | undefined
   */
  offset?: number
}

/**
 * Page[TradeListingView]
 * @description Successful Response
 */
export type ListListings200 = PageTradeListingView

/**
 * HTTPValidationError
 * @description Validation Error
 */
export type ListListings422 = HTTPValidationError

export type ListListingsQueryResponse = ListListings200

export type ListListingsQuery = {
  Response: ListListings200
  QueryParams: ListListingsQueryParams
  Errors: ListListings422
}
