/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { HTTPValidationError } from "./HTTPValidationError"
import type { PageDirectMessageView } from "./PageDirectMessageView"

export type ListThreadMessagesPathParams = {
  /**
   * @type string, uuid
   */
  thread_id: string
}

export type ListThreadMessagesQueryParams = {
  /**
   * @minLength 1
   * @maxLength 100
   * @default 30
   * @type integer | undefined
   */
  limit?: number
  /**
   * @minLength 0
   * @default 0
   * @type integer | undefined
   */
  offset?: number
}

/**
 * Page[DirectMessageView]
 * @description Successful Response
 */
export type ListThreadMessages200 = PageDirectMessageView

/**
 * HTTPValidationError
 * @description Validation Error
 */
export type ListThreadMessages422 = HTTPValidationError

export type ListThreadMessagesQueryResponse = ListThreadMessages200

export type ListThreadMessagesQuery = {
  Response: ListThreadMessages200
  PathParams: ListThreadMessagesPathParams
  QueryParams: ListThreadMessagesQueryParams
  Errors: ListThreadMessages422
}
