/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ConversationView } from "./ConversationView"

/**
 * Response List Conversations
 * @description Successful Response
 */
export type ListConversations200 = ConversationView[]

export type ListConversationsQueryResponse = ListConversations200

export type ListConversationsQuery = {
  Response: ListConversations200
  Errors: any
}
