/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { HTTPValidationError } from "./HTTPValidationError"
import type { SetGap } from "./SetGap"

export type ListGapsQueryParams = {
  set_id?: string | null
  /**
   * @default 20
   * @type integer | undefined
   */
  limit?: number
}

/**
 * Response List Gaps
 * @description Successful Response
 */
export type ListGaps200 = SetGap[]

/**
 * HTTPValidationError
 * @description Validation Error
 */
export type ListGaps422 = HTTPValidationError

export type ListGapsQueryResponse = ListGaps200

export type ListGapsQuery = {
  Response: ListGaps200
  QueryParams: ListGapsQueryParams
  Errors: ListGaps422
}
