/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { HTTPValidationError } from "./HTTPValidationError"
import type { OfferStatus } from "./OfferStatus"
import type { TradeOfferView } from "./TradeOfferView"

export type ListOffersQueryParams = {
  status_filter?: OfferStatus | null
}

/**
 * Response List Offers
 * @description Successful Response
 */
export type ListOffers200 = TradeOfferView[]

/**
 * HTTPValidationError
 * @description Validation Error
 */
export type ListOffers422 = HTTPValidationError

export type ListOffersQueryResponse = ListOffers200

export type ListOffersQuery = {
  Response: ListOffers200
  QueryParams: ListOffersQueryParams
  Errors: ListOffers422
}
