/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CardCondition } from "./CardCondition"
import type { HTTPValidationError } from "./HTTPValidationError"
import type { PageCollectionItemView } from "./PageCollectionItemView"

export const listCollectionQueryParamsSortEnum = {
  recent: "recent",
  name: "name",
  number: "number",
  price: "price",
} as const

export type ListCollectionQueryParamsSortEnumKey =
  (typeof listCollectionQueryParamsSortEnum)[keyof typeof listCollectionQueryParamsSortEnum]

export type ListCollectionQueryParams = {
  type?: string | null
  generation?: number | null
  set_id?: string | null
  condition?: CardCondition | null
  search?: string | null
  /**
   * @default "recent"
   * @type string | undefined
   */
  sort?: ListCollectionQueryParamsSortEnumKey
  /**
   * @minLength 1
   * @maxLength 200
   * @default 50
   * @type integer | undefined
   */
  limit?: number
  /**
   * @minLength 0
   * @default 0
   * @type integer | undefined
   */
  offset?: number
}

/**
 * Page[CollectionItemView]
 * @description Successful Response
 */
export type ListCollection200 = PageCollectionItemView

/**
 * HTTPValidationError
 * @description Validation Error
 */
export type ListCollection422 = HTTPValidationError

export type ListCollectionQueryResponse = ListCollection200

export type ListCollectionQuery = {
  Response: ListCollection200
  QueryParams: ListCollectionQueryParams
  Errors: ListCollection422
}
