/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { HTTPValidationError } from "./HTTPValidationError"
import type { PageSpareCard } from "./PageSpareCard"

export type ListSparesPathParams = {
  /**
   * @type string
   */
  owner_id: string
}

export type ListSparesQueryParams = {
  search?: string | null
  /**
   * @default false
   * @type boolean | undefined
   */
  wanted_only?: boolean
  /**
   * @minLength 1
   * @maxLength 60
   * @default 24
   * @type integer | undefined
   */
  limit?: number
  /**
   * @minLength 0
   * @default 0
   * @type integer | undefined
   */
  offset?: number
}

/**
 * Page[SpareCard]
 * @description Successful Response
 */
export type ListSpares200 = PageSpareCard

/**
 * HTTPValidationError
 * @description Validation Error
 */
export type ListSpares422 = HTTPValidationError

export type ListSparesQueryResponse = ListSpares200

export type ListSparesQuery = {
  Response: ListSpares200
  PathParams: ListSparesPathParams
  QueryParams: ListSparesQueryParams
  Errors: ListSpares422
}
