/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { HTTPValidationError } from "./HTTPValidationError"
import type { TradeMatch } from "./TradeMatch"

export type ListTradesQueryParams = {
  /**
   * @default 10
   * @type integer | undefined
   */
  limit?: number
}

/**
 * Response List Trades
 * @description Successful Response
 */
export type ListTrades200 = TradeMatch[]

/**
 * HTTPValidationError
 * @description Validation Error
 */
export type ListTrades422 = HTTPValidationError

export type ListTradesQueryResponse = ListTrades200

export type ListTradesQuery = {
  Response: ListTrades200
  QueryParams: ListTradesQueryParams
  Errors: ListTrades422
}
