/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CardCondition } from "./CardCondition"
import type { CardView } from "./CardView"

/**
 * ListingCardView
 * @description A card named on a listing.\n\n`condition` is null on the wanted side, and so is `adjusted_usd` with it:\nnobody has said yet which copy would arrive, so the market price is the only\nhonest figure there.
 */
export type ListingCardView = {
  /**
   * @description A card with both layers: what is printed, and the species it depicts.
   * @type object
   */
  card: CardView
  condition: CardCondition | null
  price_usd: string | null
  adjusted_usd: string | null
}
