/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CardView } from "./CardView"

/**
 * MarketCardView
 * @description A catalog card plus how many copies the reader holds. Zero is a real\nanswer here, not a missing one: the whole grid is owned against unowned.
 */
export type MarketCardView = {
  /**
   * @description A card with both layers: what is printed, and the species it depicts.
   * @type object
   */
  card: CardView
  /**
   * @type integer
   */
  owned: number
  item_id?: string | null
}
