/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Successful Response
 */
export type MarkNewsSeen204 = any;

export type MarkNewsSeenMutationResponse = MarkNewsSeen204;

export type MarkNewsSeenMutation = {
  Response: MarkNewsSeen204;
  Errors: any;
};
