/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { HTTPValidationError } from "./HTTPValidationError"
import type { ThreadView } from "./ThreadView"

export type MarkThreadReadPathParams = {
  /**
   * @type string, uuid
   */
  thread_id: string
}

/**
 * ThreadView
 * @description Successful Response
 */
export type MarkThreadRead200 = ThreadView

/**
 * HTTPValidationError
 * @description Validation Error
 */
export type MarkThreadRead422 = HTTPValidationError

export type MarkThreadReadMutationResponse = MarkThreadRead200

export type MarkThreadReadMutation = {
  Response: MarkThreadRead200
  PathParams: MarkThreadReadPathParams
  Errors: MarkThreadRead422
}
