/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { HTTPValidationError } from "./HTTPValidationError"
import type { PageMarketCardView } from "./PageMarketCardView"

export const marketCardsQueryParamsOwnedEnum = {
  all: "all",
  owned: "owned",
  missing: "missing",
} as const

export type MarketCardsQueryParamsOwnedEnumKey =
  (typeof marketCardsQueryParamsOwnedEnum)[keyof typeof marketCardsQueryParamsOwnedEnum]

export const marketCardsQueryParamsSortEnum = {
  number: "number",
  name: "name",
  price: "price",
  owned: "owned",
} as const

export type MarketCardsQueryParamsSortEnumKey =
  (typeof marketCardsQueryParamsSortEnum)[keyof typeof marketCardsQueryParamsSortEnum]

export type MarketCardsQueryParams = {
  type?: string | null
  generation?: number | null
  set_id?: string | null
  search?: string | null
  /**
   * @default "all"
   * @type string | undefined
   */
  owned?: MarketCardsQueryParamsOwnedEnumKey
  /**
   * @default "number"
   * @type string | undefined
   */
  sort?: MarketCardsQueryParamsSortEnumKey
  /**
   * @minLength 1
   * @maxLength 200
   * @default 50
   * @type integer | undefined
   */
  limit?: number
  /**
   * @minLength 0
   * @default 0
   * @type integer | undefined
   */
  offset?: number
}

/**
 * Page[MarketCardView]
 * @description Successful Response
 */
export type MarketCards200 = PageMarketCardView

/**
 * HTTPValidationError
 * @description Validation Error
 */
export type MarketCards422 = HTTPValidationError

export type MarketCardsQueryResponse = MarketCards200

export type MarketCardsQuery = {
  Response: MarketCards200
  QueryParams: MarketCardsQueryParams
  Errors: MarketCards422
}
