/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { SetMarketView } from "./SetMarketView"

/**
 * Response Market Sets
 * @description Successful Response
 */
export type MarketSets200 = SetMarketView[]

export type MarketSetsQueryResponse = MarketSets200

export type MarketSetsQuery = {
  Response: MarketSets200
  Errors: any
}
