/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { MarketTypeCount } from "./MarketTypeCount"
import type { PortfolioReturn } from "./PortfolioReturn"
import type { PriceChange } from "./PriceChange"

/**
 * MarketSummary
 */
export type MarketSummary = {
  /**
   * @type integer
   */
  total_cards: number
  /**
   * @type integer
   */
  owned_cards: number
  /**
   * @pattern ^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$
   * @type string
   */
  catalog_value: string
  /**
   * @pattern ^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$
   * @type string
   */
  owned_value: string
  /**
   * @pattern ^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$
   * @type string
   */
  missing_value: string
  /**
   * @type array
   */
  types: MarketTypeCount[]
  change?: PriceChange | null
  performance?: PortfolioReturn | null
}

/**
 * MarketSummary
 * @description Successful Response
 */
export type MarketSummary200 = MarketSummary

export type MarketSummaryQueryResponse = MarketSummary200

export type MarketSummaryQuery = {
  Response: MarketSummary200
  Errors: any
}
