/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { MeResponse } from "./MeResponse"

/**
 * MeResponse
 * @description Successful Response
 */
export type Me200 = MeResponse

export type MeQueryResponse = Me200

export type MeQuery = {
  Response: Me200
  Errors: any
}
