/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const messageRoleEnum = {
  user: "user",
  assistant: "assistant",
} as const

export type MessageRoleEnumKey =
  (typeof messageRoleEnum)[keyof typeof messageRoleEnum]

/**
 * MessageRole
 */
export type MessageRole = MessageRoleEnumKey
