/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const newsEntryKindEnum = {
  offer_waiting: "offer_waiting",
  offer_answered: "offer_answered",
  trade_closed: "trade_closed",
  listing_taken: "listing_taken",
  message_unread: "message_unread",
  wish_cheaper: "wish_cheaper",
  wish_dearer: "wish_dearer",
} as const;

export type NewsEntryKindEnumKey =
  (typeof newsEntryKindEnum)[keyof typeof newsEntryKindEnum];

/**
 * NewsEntry
 * @description Something that happened, told from the reader\'s side.
 */
export type NewsEntry = {
  /**
   * @type string
   */
  kind: NewsEntryKindEnumKey;
  /**
   * @type string, date-time
   */
  at: string;
  /**
   * @type string
   */
  title: string;
  detail?: string | null;
  partner_id?: string | null;
  card_id?: string | null;
  card_name?: string | null;
  image_url?: string | null;
  amount?: string | null;
  href?: string | null;
  /**
   * @default false
   * @type boolean | undefined
   */
  actionable?: boolean;
  /**
   * @default false
   * @type boolean | undefined
   */
  seen?: boolean;
};
