/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { HTTPValidationError } from "./HTTPValidationError";
import type { NewsEntry } from "./NewsEntry";

/**
 * NewsFeed
 */
export type NewsFeed = {
  /**
   * @type array
   */
  items: NewsEntry[];
  /**
   * @type integer
   */
  total: number;
  /**
   * @type integer
   */
  limit: number;
  /**
   * @type integer
   */
  offset: number;
  /**
   * @type integer
   */
  waiting: number;
};

export type NewsFeedQueryParams = {
  /**
   * @default false
   * @type boolean | undefined
   */
  actionable?: boolean;
  /**
   * @minLength 1
   * @maxLength 50
   * @default 20
   * @type integer | undefined
   */
  limit?: number;
  /**
   * @minLength 0
   * @default 0
   * @type integer | undefined
   */
  offset?: number;
};

/**
 * NewsFeed
 * @description Successful Response
 */
export type NewsFeed200 = NewsFeed;

/**
 * HTTPValidationError
 * @description Validation Error
 */
export type NewsFeed422 = HTTPValidationError;

export type NewsFeedQueryResponse = NewsFeed200;

export type NewsFeedQuery = {
  Response: NewsFeed200;
  QueryParams: NewsFeedQueryParams;
  Errors: NewsFeed422;
};
