/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CardView } from "./CardView"

/**
 * OfferCardView
 * @description A card named in an offer.\n\nNo copy count, unlike a match: a match reports what is available to trade,\nan offer names which cards are on the table.
 */
export type OfferCardView = {
  /**
   * @description A card with both layers: what is printed, and the species it depicts.
   * @type object
   */
  card: CardView
  price_usd: string | null
}
