/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const offerStatusEnum = {
  pending: "pending",
  accepted: "accepted",
  declined: "declined",
  withdrawn: "withdrawn",
} as const

export type OfferStatusEnumKey =
  (typeof offerStatusEnum)[keyof typeof offerStatusEnum]

/**
 * OfferStatus
 */
export type OfferStatus = OfferStatusEnumKey
