/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CardCondition } from "./CardCondition"

/**
 * OfferCardInput
 * @description A card put on the table, in a state.\n\nLeaving the condition out lets the service pick the worst copy its owner\nholds, which is the one a collector parts with.
 */
export type OfferCardInput = {
  /**
   * @type string
   */
  card_id: string
  condition?: CardCondition | null
}
