/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * Response Owned Card Ids
 * @description Successful Response
 */
export type OwnedCardIds200 = string[]

export type OwnedCardIdsQueryResponse = OwnedCardIds200

export type OwnedCardIdsQuery = {
  Response: OwnedCardIds200
  Errors: any
}
