/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * OwnedSlot
 * @description One collector number the user holds, and what that card is.\n\nThe type travels with the number because the client draws coverage as a strip\nof type-coloured slots; without it every owned card renders the same.
 */
export type OwnedSlot = {
  /**
   * @type string
   */
  number: string
  type: string | null
}
