/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { TradeListingView } from "./TradeListingView"

/**
 * Page[TradeListingView]
 */
export type PageTradeListingView = {
  /**
   * @type array
   */
  items: TradeListingView[]
  /**
   * @type integer
   */
  total: number
  /**
   * @type integer
   */
  limit: number
  /**
   * @type integer
   */
  offset: number
}
