/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { TradeOfferView } from "./TradeOfferView"

/**
 * Page[TradeOfferView]
 */
export type PageTradeOfferView = {
  /**
   * @type array
   */
  items: TradeOfferView[]
  /**
   * @type integer
   */
  total: number
  /**
   * @type integer
   */
  limit: number
  /**
   * @type integer
   */
  offset: number
}
