/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CollectorView } from "./CollectorView"

/**
 * Page[CollectorView]
 */
export type PageCollectorView = {
  /**
   * @type array
   */
  items: CollectorView[]
  /**
   * @type integer
   */
  total: number
  /**
   * @type integer
   */
  limit: number
  /**
   * @type integer
   */
  offset: number
}
