/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { MarketCardView } from "./MarketCardView"

/**
 * Page[MarketCardView]
 */
export type PageMarketCardView = {
  /**
   * @type array
   */
  items: MarketCardView[]
  /**
   * @type integer
   */
  total: number
  /**
   * @type integer
   */
  limit: number
  /**
   * @type integer
   */
  offset: number
}
