/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { PositionView } from "./PositionView"

/**
 * Page[PositionView]
 */
export type PagePositionView = {
  /**
   * @type array
   */
  items: PositionView[]
  /**
   * @type integer
   */
  total: number
  /**
   * @type integer
   */
  limit: number
  /**
   * @type integer
   */
  offset: number
}
