/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ConcentrationBucket } from "./ConcentrationBucket"

/**
 * PortfolioConcentration
 * @description How few cards carry the value.\n\n`cards_for_half` is the count of positions, largest first, that reach half\nthe portfolio: one number for how exposed the whole thing is to a handful of\ncards. Unpriced holdings are counted but never valued.
 */
export type PortfolioConcentration = {
  /**
   * @pattern ^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$
   * @type string
   */
  total_value: string
  /**
   * @type integer
   */
  priced_positions: number
  /**
   * @type integer
   */
  unpriced_positions: number
  /**
   * @type array
   */
  buckets: ConcentrationBucket[]
  cards_for_half: number | null
}
