/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * PortfolioReturn
 * @description What the holdings cost against what they are worth now.\n\nMeasured only over the copies with a recorded cost, and it says how many\nthose are: a return computed over half a collection would otherwise read as\na return over all of it.
 */
export type PortfolioReturn = {
  /**
   * @pattern ^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$
   * @type string
   */
  cost_basis: string
  /**
   * @pattern ^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$
   * @type string
   */
  market_value: string
  /**
   * @pattern ^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$
   * @type string
   */
  absolute: string
  /**
   * @type number
   */
  percent: number
  /**
   * @type integer
   */
  positions: number
  /**
   * @type integer
   */
  positions_without_cost: number
}
