/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CardView } from "./CardView"

/**
 * PositionView
 * @description One held card as a position: what it cost, what it is worth now, and how\nmuch of the portfolio rests on it.\n\nCost and gain are measured over the copies carrying a recorded cost, and\n`costed_quantity` says how many those are: a copy bought before costs were\ntracked would otherwise land on the value side of the subtraction alone and\nread as pure profit.
 */
export type PositionView = {
  /**
   * @description A card with both layers: what is printed, and the species it depicts.
   * @type object
   */
  card: CardView
  /**
   * @type integer
   */
  quantity: number
  /**
   * @type integer
   */
  costed_quantity: number
  unit_cost_usd: string | null
  cost_basis: string | null
  market_value: string | null
  gain_absolute: string | null
  gain_percent: number | null
  /**
   * @type number
   */
  portfolio_share: number
}
