/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * PriceChange
 * @description Movement between the oldest reading inside a window and today.
 */
export type PriceChange = {
  /**
   * @type string, date
   */
  since: string
  /**
   * @pattern ^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$
   * @type string
   */
  from_value: string
  /**
   * @pattern ^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$
   * @type string
   */
  to_value: string
  /**
   * @pattern ^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$
   * @type string
   */
  absolute: string
  /**
   * @type number
   */
  percent: number
}
