/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * ProfileSet
 */
export type ProfileSet = {
  /**
   * @type string
   */
  set_id: string
  /**
   * @type string
   */
  set_name: string
  /**
   * @type integer
   */
  owned: number
  /**
   * @type integer
   */
  printed_total: number
}
