/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { HTTPValidationError } from "./HTTPValidationError";
import type { TradeAdvice } from "./TradeAdvice";
import type { TradeAdviceRequest } from "./TradeAdviceRequest";

/**
 * TradeAdvice
 * @description Successful Response
 */
export type ProposeTrade200 = TradeAdvice;

/**
 * HTTPValidationError
 * @description Validation Error
 */
export type ProposeTrade422 = HTTPValidationError;

/**
 * TradeAdviceRequest
 */
export type ProposeTradeMutationRequest = TradeAdviceRequest;

export type ProposeTradeMutationResponse = ProposeTrade200;

export type ProposeTradeMutation = {
  Response: ProposeTrade200;
  Request: ProposeTradeMutationRequest;
  Errors: ProposeTrade422;
};
