/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * ProposedLeg
 * @description A card in a proposal, carrying enough of itself to be drawn.\n\nThe simulator shows cards, not names, and a proposal that arrived as ids\nwould have to fetch each one back before it could render.
 */
export type ProposedLeg = {
  /**
   * @type string
   */
  card_id: string;
  /**
   * @type string
   */
  card_name: string;
  /**
   * @default ""
   * @type string | undefined
   */
  set_name?: string;
  image_url?: string | null;
  /**
   * @default "Pokemon"
   * @type string | undefined
   */
  category?: string;
  price_usd?: string | null;
  /**
   * @default 1
   * @type integer | undefined
   */
  owned?: number;
  /**
   * @default 1
   * @type integer | undefined
   */
  quantity?: number;
};
