/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CardCondition } from "./CardCondition"
import type { CardView } from "./CardView"

/**
 * PublicItemView
 * @description A narrower view than the owner\'s own.\n\nNotes are free text the user wrote for themselves, and acquisition dates\ndescribe their habits; neither belongs on a page anyone with the link can\nopen. Reusing the private view here would have published both.
 */
export type PublicItemView = {
  /**
   * @type string, uuid
   */
  id: string
  /**
   * @type integer
   */
  quantity: number
  /**
   * @type string
   */
  condition: CardCondition
  /**
   * @description A card with both layers: what is printed, and the species it depicts.
   * @type object
   */
  card: CardView
}
