/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CreateListingRequest } from "./CreateListingRequest"
import type { HTTPValidationError } from "./HTTPValidationError"
import type { TradeListingView } from "./TradeListingView"

/**
 * TradeListingView
 * @description Successful Response
 */
export type PublishListing201 = TradeListingView

/**
 * HTTPValidationError
 * @description Validation Error
 */
export type PublishListing422 = HTTPValidationError

/**
 * CreateListingRequest
 */
export type PublishListingMutationRequest = CreateListingRequest

export type PublishListingMutationResponse = PublishListing201

export type PublishListingMutation = {
  Response: PublishListing201
  Request: PublishListingMutationRequest
  Errors: PublishListing422
}
