/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { HTTPValidationError } from "./HTTPValidationError"
import type { PublicCollection } from "./PublicCollection"

export type ReadSharedCollectionPathParams = {
  /**
   * @type string
   */
  token: string
}

/**
 * PublicCollection
 * @description Successful Response
 */
export type ReadSharedCollection200 = PublicCollection

/**
 * HTTPValidationError
 * @description Validation Error
 */
export type ReadSharedCollection422 = HTTPValidationError

export type ReadSharedCollectionQueryResponse = ReadSharedCollection200

export type ReadSharedCollectionQuery = {
  Response: ReadSharedCollection200
  PathParams: ReadSharedCollectionPathParams
  Errors: ReadSharedCollection422
}
