/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { HTTPValidationError } from "./HTTPValidationError"

export type RemoveItemPathParams = {
  /**
   * @type string, uuid
   */
  item_id: string
}

/**
 * @description Successful Response
 */
export type RemoveItem204 = any

/**
 * HTTPValidationError
 * @description Validation Error
 */
export type RemoveItem422 = HTTPValidationError

export type RemoveItemMutationResponse = RemoveItem204

export type RemoveItemMutation = {
  Response: RemoveItem204
  PathParams: RemoveItemPathParams
  Errors: RemoveItem422
}
