/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { HTTPValidationError } from "./HTTPValidationError"

export type RemoveFromWishlistPathParams = {
  /**
   * @type string, uuid
   */
  item_id: string
}

/**
 * @description Successful Response
 */
export type RemoveFromWishlist204 = any

/**
 * HTTPValidationError
 * @description Validation Error
 */
export type RemoveFromWishlist422 = HTTPValidationError

export type RemoveFromWishlistMutationResponse = RemoveFromWishlist204

export type RemoveFromWishlistMutation = {
  Response: RemoveFromWishlist204
  PathParams: RemoveFromWishlistPathParams
  Errors: RemoveFromWishlist422
}
