/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { HTTPValidationError } from "./HTTPValidationError"
import type { RespondOfferRequest } from "./RespondOfferRequest"
import type { TradeOfferView } from "./TradeOfferView"

export type RespondToOfferPathParams = {
  /**
   * @type string, uuid
   */
  offer_id: string
}

/**
 * TradeOfferView
 * @description Successful Response
 */
export type RespondToOffer200 = TradeOfferView

/**
 * HTTPValidationError
 * @description Validation Error
 */
export type RespondToOffer422 = HTTPValidationError

/**
 * RespondOfferRequest
 */
export type RespondToOfferMutationRequest = RespondOfferRequest

export type RespondToOfferMutationResponse = RespondToOffer200

export type RespondToOfferMutation = {
  Response: RespondToOffer200
  Request: RespondToOfferMutationRequest
  PathParams: RespondToOfferPathParams
  Errors: RespondToOffer422
}
