/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CardView } from "./CardView"
import type { HTTPValidationError } from "./HTTPValidationError"

export type SearchCardsQueryParams = {
  q?: string | null
  set_id?: string | null
  /**
   * @minLength 1
   * @maxLength 100
   * @default 30
   * @type integer | undefined
   */
  limit?: number
}

/**
 * Response Search Cards
 * @description Successful Response
 */
export type SearchCards200 = CardView[]

/**
 * HTTPValidationError
 * @description Validation Error
 */
export type SearchCards422 = HTTPValidationError

export type SearchCardsQueryResponse = SearchCards200

export type SearchCardsQuery = {
  Response: SearchCards200
  QueryParams: SearchCardsQueryParams
  Errors: SearchCards422
}
