/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { HTTPValidationError } from "./HTTPValidationError"
import type { SpeciesView } from "./SpeciesView"

export type SearchSpeciesQueryParams = {
  name?: string | null
  type?: string | null
  generation?: number | null
  /**
   * @minLength 1
   * @maxLength 200
   * @default 50
   * @type integer | undefined
   */
  limit?: number
}

/**
 * Response Search Species
 * @description Successful Response
 */
export type SearchSpecies200 = SpeciesView[]

/**
 * HTTPValidationError
 * @description Validation Error
 */
export type SearchSpecies422 = HTTPValidationError

export type SearchSpeciesQueryResponse = SearchSpecies200

export type SearchSpeciesQuery = {
  Response: SearchSpecies200
  QueryParams: SearchSpeciesQueryParams
  Errors: SearchSpecies422
}
