/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { DirectMessageView } from "./DirectMessageView"
import type { HTTPValidationError } from "./HTTPValidationError"
import type { SendMessageRequest } from "./SendMessageRequest"

/**
 * DirectMessageView
 * @description Successful Response
 */
export type SendDirectMessage201 = DirectMessageView

/**
 * HTTPValidationError
 * @description Validation Error
 */
export type SendDirectMessage422 = HTTPValidationError

/**
 * SendMessageRequest
 */
export type SendDirectMessageMutationRequest = SendMessageRequest

export type SendDirectMessageMutationResponse = SendDirectMessage201

export type SendDirectMessageMutation = {
  Response: SendDirectMessage201
  Request: SendDirectMessageMutationRequest
  Errors: SendDirectMessage422
}
