/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ChatRequest } from "./ChatRequest"
import type { HTTPValidationError } from "./HTTPValidationError"

/**
 * @description Successful Response
 */
export type SendMessage200 = any

/**
 * HTTPValidationError
 * @description Validation Error
 */
export type SendMessage422 = HTTPValidationError

/**
 * ChatRequest
 */
export type SendMessageMutationRequest = ChatRequest

export type SendMessageMutationResponse = SendMessage200

export type SendMessageMutation = {
  Response: SendMessage200
  Request: SendMessageMutationRequest
  Errors: SendMessage422
}
