/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * SendMessageRequest
 */
export type SendMessageRequest = {
  /**
   * @type string
   */
  to_user_id: string
  /**
   * @minLength 1
   * @maxLength 2000
   * @type string
   */
  body: string
}
