/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { OwnedSlot } from "./OwnedSlot"

/**
 * SetCoverage
 */
export type SetCoverage = {
  /**
   * @type string
   */
  set_id: string
  /**
   * @type string
   */
  set_name: string
  /**
   * @type integer
   */
  printed_total: number
  /**
   * @type integer
   */
  owned: number
  /**
   * @type array
   */
  owned_slots: OwnedSlot[]
}
