/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CardView } from "./CardView"

/**
 * SetGap
 */
export type SetGap = {
  /**
   * @type string
   */
  set_id: string
  /**
   * @type string
   */
  set_name: string
  /**
   * @type integer
   */
  printed_total: number
  /**
   * @type array
   */
  missing: CardView[]
}
