/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * SetMarketView
 * @description One set as a position: how much of it is held, and what finishing costs.
 */
export type SetMarketView = {
  /**
   * @type string
   */
  set_id: string
  /**
   * @type string
   */
  set_name: string
  /**
   * @type integer
   */
  cards: number
  /**
   * @type integer
   */
  owned: number
  /**
   * @pattern ^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$
   * @type string
   */
  held_value: string
  /**
   * @pattern ^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$
   * @type string
   */
  missing_value: string
  /**
   * @pattern ^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$
   * @type string
   */
  total_value: string
}
