/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * ShareLinkView
 */
export type ShareLinkView = {
  /**
   * @type string, uuid
   */
  id: string
  /**
   * @type string
   */
  token: string
  /**
   * @type string, date-time
   */
  created_at: string
}
