/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { HTTPValidationError } from "./HTTPValidationError"
import type { TradeSimulation } from "./TradeSimulation"
import type { TradeSimulationRequest } from "./TradeSimulationRequest"

/**
 * TradeSimulation
 * @description Successful Response
 */
export type SimulateTrade200 = TradeSimulation

/**
 * HTTPValidationError
 * @description Validation Error
 */
export type SimulateTrade422 = HTTPValidationError

/**
 * TradeSimulationRequest
 */
export type SimulateTradeMutationRequest = TradeSimulationRequest

export type SimulateTradeMutationResponse = SimulateTrade200

export type SimulateTradeMutation = {
  Response: SimulateTrade200
  Request: SimulateTradeMutationRequest
  Errors: SimulateTrade422
}
