/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CardView } from "./CardView"
import type { ConditionCount } from "./ConditionCount"

/**
 * SpareCard
 * @description A card free to trade, seen by someone who might want it.
 */
export type SpareCard = {
  /**
   * @description A card with both layers: what is printed, and the species it depicts.
   * @type object
   */
  card: CardView
  /**
   * @type integer
   */
  copies: number
  price_usd: string | null
  /**
   * @type boolean
   */
  wanted: boolean
  /**
   * @type array
   */
  conditions: ConditionCount[]
}
