/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { HTTPValidationError } from "./HTTPValidationError"
import type { TriviaView } from "./TriviaView"

export type SpeciesTriviaPathParams = {
  /**
   * @type integer
   */
  species_id: number
}

/**
 * Response Species Trivia
 * @description Successful Response
 */
export type SpeciesTrivia200 = TriviaView | null

/**
 * HTTPValidationError
 * @description Validation Error
 */
export type SpeciesTrivia422 = HTTPValidationError

export type SpeciesTriviaQueryResponse = SpeciesTrivia200

export type SpeciesTriviaQuery = {
  Response: SpeciesTrivia200
  PathParams: SpeciesTriviaPathParams
  Errors: SpeciesTrivia422
}
