/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { EvolutionMemberView } from "./EvolutionMemberView"
import type { HTTPValidationError } from "./HTTPValidationError"

export type SpeciesEvolutionsPathParams = {
  /**
   * @type integer
   */
  species_id: number
}

/**
 * Response Species Evolutions
 * @description Successful Response
 */
export type SpeciesEvolutions200 = EvolutionMemberView[]

/**
 * HTTPValidationError
 * @description Validation Error
 */
export type SpeciesEvolutions422 = HTTPValidationError

export type SpeciesEvolutionsQueryResponse = SpeciesEvolutions200

export type SpeciesEvolutionsQuery = {
  Response: SpeciesEvolutions200
  PathParams: SpeciesEvolutionsPathParams
  Errors: SpeciesEvolutions422
}
