/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * ThreadView
 * @description A conversation as one of its two participants sees it.\n\n`id` is null for a conversation nobody has started. The partner is the\naddress, not the thread, so a collector can be opened and written to before\nany row exists — which is what keeps an abandoned \"Mensaje\" click from\nleaving an empty thread in everyone\'s list.
 */
export type ThreadView = {
  id: string | null
  /**
   * @type string
   */
  partner_id: string
  partner_name: string | null
  last_body: string | null
  last_at: string | null
  /**
   * @type boolean
   */
  last_mine: boolean
  /**
   * @type integer
   */
  unread: number
}
