/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * TradeLeg
 */
export type TradeLeg = {
  /**
   * @type string
   */
  card_id: string
  /**
   * @minLength 1
   * @default 1
   * @type integer | undefined
   */
  quantity?: number
}
