/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ListingCardView } from "./ListingCardView"
import type { ListingStatus } from "./ListingStatus"

/**
 * TradeListingView
 * @description A listing as one reader sees it.\n\nSides are named from the publisher, who is fixed, rather than from the\nreader, who is not. `balance` is what taking it would be worth — positive\nmeans the taker comes out ahead — and it is the same number for everyone.\n\n`available` is the publisher\'s half of the promise still standing, and\n`can_fulfil` the reader\'s: both have to be true for the listing to be\ntakeable, and a listing whose publisher has since traded away what it names\nis shown rather than hidden, so the board does not appear to lose rows.
 */
export type TradeListingView = {
  /**
   * @type string, uuid
   */
  id: string
  /**
   * @type string
   */
  owner_id: string
  owner_name: string | null
  /**
   * @type boolean
   */
  is_mine: boolean
  /**
   * @type string
   */
  status: ListingStatus
  /**
   * @type array
   */
  gives: ListingCardView[]
  /**
   * @type array
   */
  wants: ListingCardView[]
  /**
   * @pattern ^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$
   * @type string
   */
  give_value: string
  /**
   * @pattern ^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$
   * @type string
   */
  want_value: string
  /**
   * @pattern ^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$
   * @type string
   */
  balance: string
  /**
   * @type boolean
   */
  available: boolean
  /**
   * @type boolean
   */
  can_fulfil: boolean
  /**
   * @type integer
   */
  missing: number
  note: string | null
  offer_id: string | null
  /**
   * @type string, date-time
   */
  created_at: string
  taken_at: string | null
}
