/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { OfferCardView } from "./OfferCardView"
import type { OfferStatus } from "./OfferStatus"

export const tradeOfferViewDirectionEnum = {
  sent: "sent",
  received: "received",
} as const

export type TradeOfferViewDirectionEnumKey =
  (typeof tradeOfferViewDirectionEnum)[keyof typeof tradeOfferViewDirectionEnum]

/**
 * TradeOfferView
 * @description An offer told from the reader\'s side.\n\n`you_give` and `you_get` swap meaning depending on who is looking, so the\nservice resolves them per reader rather than storing them that way.
 */
export type TradeOfferView = {
  /**
   * @type string, uuid
   */
  id: string
  /**
   * @type string
   */
  status: OfferStatus
  /**
   * @type string
   */
  direction: TradeOfferViewDirectionEnumKey
  /**
   * @type string
   */
  partner_id: string
  partner_name: string | null
  /**
   * @type array
   */
  you_give: OfferCardView[]
  /**
   * @type array
   */
  you_get: OfferCardView[]
  /**
   * @pattern ^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$
   * @type string
   */
  give_value: string
  /**
   * @pattern ^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$
   * @type string
   */
  get_value: string
  /**
   * @pattern ^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$
   * @type string
   */
  balance: string
  message: string | null
  replies_to_id: string | null
  /**
   * @type string, date-time
   */
  created_at: string
  responded_at: string | null
}
