/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { PortfolioConcentration } from "./PortfolioConcentration"

/**
 * TradeSimulation
 * @description The portfolio either side of a swap that has not happened.\n\nCards with no market price are named rather than valued at zero, because a\nswap resting on them is not the even trade the totals would claim.
 */
export type TradeSimulation = {
  /**
   * @description How few cards carry the value.\n\n`cards_for_half` is the count of positions, largest first, that reach half\nthe portfolio: one number for how exposed the whole thing is to a handful of\ncards. Unpriced holdings are counted but never valued.
   * @type object
   */
  before: PortfolioConcentration
  /**
   * @description How few cards carry the value.\n\n`cards_for_half` is the count of positions, largest first, that reach half\nthe portfolio: one number for how exposed the whole thing is to a handful of\ncards. Unpriced holdings are counted but never valued.
   * @type object
   */
  after: PortfolioConcentration
  /**
   * @pattern ^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$
   * @type string
   */
  give_value: string
  /**
   * @pattern ^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$
   * @type string
   */
  receive_value: string
  /**
   * @pattern ^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$
   * @type string
   */
  value_delta: string
  /**
   * @type array
   */
  unpriced_cards: string[]
}
