/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ProposedLeg } from "./ProposedLeg";

/**
 * TradeAdvice
 * @description A swap the assistant thinks is worth simulating.\n\nIt proposes and explains; it never sends anything. The reader loads it into\nthe simulator, which is where the numbers come from.
 */
export type TradeAdvice = {
  /**
   * @type array
   */
  give: ProposedLeg[];
  /**
   * @type array
   */
  receive: ProposedLeg[];
  /**
   * @type string
   */
  rationale: string;
};
