/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { TradeCard } from "./TradeCard"

/**
 * TradeMatch
 * @description A counterparty who wants something spare, and has something wanted.\n\nOnly the cards on both sides of the overlap are named. What else the\ncounterparty holds, and what their collection is worth, stay theirs: this\nanswers whether a trade exists, not what someone owns.\n\nValues count one copy of each card. `balance` is what the trade is worth to\nthe reader — positive means they come out ahead — and it is reported rather\nthan balanced, because which cards even out a swap is the traders\' call.
 */
export type TradeMatch = {
  /**
   * @type string
   */
  partner_id: string
  partner_name: string | null
  /**
   * @type array
   */
  you_give: TradeCard[]
  /**
   * @type array
   */
  you_get: TradeCard[]
  /**
   * @pattern ^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$
   * @type string
   */
  give_value: string
  /**
   * @pattern ^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$
   * @type string
   */
  get_value: string
  /**
   * @pattern ^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$
   * @type string
   */
  balance: string
  /**
   * @type integer
   */
  unpriced: number
}
