/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CardView } from "./CardView"

/**
 * TradeCard
 * @description A card that could change hands, and how many copies are free to move.
 */
export type TradeCard = {
  /**
   * @description A card with both layers: what is printed, and the species it depicts.
   * @type object
   */
  card: CardView
  /**
   * @type integer
   */
  copies: number
  price_usd: string | null
}
