/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * TriviaView
 */
export type TriviaView = {
  /**
   * @type string
   */
  text: string
  /**
   * @type string
   */
  model: string
}
