/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CollectionItemView } from "./CollectionItemView"
import type { HTTPValidationError } from "./HTTPValidationError"
import type { UpdateItemRequest } from "./UpdateItemRequest"

export type UpdateItemPathParams = {
  /**
   * @type string, uuid
   */
  item_id: string
}

/**
 * CollectionItemView
 * @description Successful Response
 */
export type UpdateItem200 = CollectionItemView

/**
 * HTTPValidationError
 * @description Validation Error
 */
export type UpdateItem422 = HTTPValidationError

/**
 * UpdateItemRequest
 */
export type UpdateItemMutationRequest = UpdateItemRequest

export type UpdateItemMutationResponse = UpdateItem200

export type UpdateItemMutation = {
  Response: UpdateItem200
  Request: UpdateItemMutationRequest
  PathParams: UpdateItemPathParams
  Errors: UpdateItem422
}
