/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CardCondition } from "./CardCondition"

/**
 * UpdateItemRequest
 */
export type UpdateItemRequest = {
  quantity?: number | null
  condition?: CardCondition | null
  notes?: string | null
}
