/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * VisualComparison
 * @description What the model saw, kept short enough to read beside the cards.
 */
export type VisualComparison = {
  /**
   * @maxLength 400
   * @type string
   */
  summary: string
  /**
   * @type array | undefined
   */
  differences?: string[]
}
