/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CardView } from "./CardView"
import type { WishlistSource } from "./WishlistSource"

/**
 * WishlistItemView
 */
export type WishlistItemView = {
  /**
   * @type string, uuid
   */
  id: string
  /**
   * @description A card with both layers: what is printed, and the species it depicts.
   * @type object
   */
  card: CardView
  /**
   * @type integer
   */
  priority: number
  reason: string | null
  /**
   * @type string
   */
  added_by: WishlistSource
  /**
   * @type string, date-time
   */
  created_at: string
}
