/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const wishlistSourceEnum = {
  user: "user",
  agent: "agent",
} as const

export type WishlistSourceEnumKey =
  (typeof wishlistSourceEnum)[keyof typeof wishlistSourceEnum]

/**
 * WishlistSource
 */
export type WishlistSource = WishlistSourceEnumKey
