/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { HTTPValidationError } from "./HTTPValidationError"
import type { TradeOfferView } from "./TradeOfferView"

export type WithdrawOfferPathParams = {
  /**
   * @type string, uuid
   */
  offer_id: string
}

/**
 * TradeOfferView
 * @description Successful Response
 */
export type WithdrawOffer200 = TradeOfferView

/**
 * HTTPValidationError
 * @description Validation Error
 */
export type WithdrawOffer422 = HTTPValidationError

export type WithdrawOfferMutationResponse = WithdrawOffer200

export type WithdrawOfferMutation = {
  Response: WithdrawOffer200
  PathParams: WithdrawOfferPathParams
  Errors: WithdrawOffer422
}
