/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/fetch"
import type {
  AcceptListingMutationResponse,
  AcceptListingPathParams,
  AcceptListing422,
} from "../types/AcceptListing"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/fetch"

function getAcceptListingUrl(
  listing_id: AcceptListingPathParams["listing_id"]
) {
  const res = {
    method: "POST",
    url: `/api/v1/trades/listings/${listing_id}/accept` as const,
  }
  return res
}

/**
 * @description Take a listing, which agrees it: the answer is the trade it became.
 * @summary Accept Listing
 * {@link /api/v1/trades/listings/:listing_id/accept}
 */
export async function acceptListing(
  listing_id: AcceptListingPathParams["listing_id"],
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<
    AcceptListingMutationResponse,
    ResponseErrorConfig<AcceptListing422>,
    unknown
  >({
    method: "POST",
    url: getAcceptListingUrl(listing_id).url.toString(),
    ...requestConfig,
  })
  return res.data
}
