/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/fetch"
import type {
  AddCardMutationRequest,
  AddCardMutationResponse,
  AddCard422,
} from "../types/AddCard"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/fetch"

function getAddCardUrl() {
  const res = { method: "POST", url: `/api/v1/collection` as const }
  return res
}

/**
 * @summary Add Card
 * {@link /api/v1/collection}
 */
export async function addCard(
  data: AddCardMutationRequest,
  config: Partial<RequestConfig<AddCardMutationRequest>> & {
    client?: Client
  } = {}
) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = data

  const res = await request<
    AddCardMutationResponse,
    ResponseErrorConfig<AddCard422>,
    AddCardMutationRequest
  >({
    method: "POST",
    url: getAddCardUrl().url.toString(),
    data: requestData,
    ...requestConfig,
  })
  return res.data
}
