/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/fetch"
import type {
  AddToWishlistMutationRequest,
  AddToWishlistMutationResponse,
  AddToWishlist422,
} from "../types/AddToWishlist"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/fetch"

function getAddToWishlistUrl() {
  const res = { method: "POST", url: `/api/v1/wishlist` as const }
  return res
}

/**
 * @summary Add To Wishlist
 * {@link /api/v1/wishlist}
 */
export async function addToWishlist(
  data: AddToWishlistMutationRequest,
  config: Partial<RequestConfig<AddToWishlistMutationRequest>> & {
    client?: Client
  } = {}
) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = data

  const res = await request<
    AddToWishlistMutationResponse,
    ResponseErrorConfig<AddToWishlist422>,
    AddToWishlistMutationRequest
  >({
    method: "POST",
    url: getAddToWishlistUrl().url.toString(),
    data: requestData,
    ...requestConfig,
  })
  return res.data
}
