/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/fetch"
import type {
  CancelListingMutationResponse,
  CancelListingPathParams,
  CancelListing422,
} from "../types/CancelListing"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/fetch"

function getCancelListingUrl(
  listing_id: CancelListingPathParams["listing_id"]
) {
  const res = {
    method: "POST",
    url: `/api/v1/trades/listings/${listing_id}/cancel` as const,
  }
  return res
}

/**
 * @description Take a listing off the board. Only its publisher, and only while open.
 * @summary Cancel Listing
 * {@link /api/v1/trades/listings/:listing_id/cancel}
 */
export async function cancelListing(
  listing_id: CancelListingPathParams["listing_id"],
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<
    CancelListingMutationResponse,
    ResponseErrorConfig<CancelListing422>,
    unknown
  >({
    method: "POST",
    url: getCancelListingUrl(listing_id).url.toString(),
    ...requestConfig,
  })
  return res.data
}
