/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/fetch"
import type { CollectionStatsQueryResponse } from "../types/CollectionStats"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/fetch"

function getCollectionStatsUrl() {
  const res = { method: "GET", url: `/api/v1/stats` as const }
  return res
}

/**
 * @summary Collection Stats
 * {@link /api/v1/stats}
 */
export async function collectionStats(
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<
    CollectionStatsQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: "GET",
    url: getCollectionStatsUrl().url.toString(),
    ...requestConfig,
  })
  return res.data
}
