/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/fetch"
import type { CollectionActivityQueryResponse } from "../types/CollectionActivity"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/fetch"

function getCollectionActivityUrl() {
  const res = { method: "GET", url: `/api/v1/collection/activity` as const }
  return res
}

/**
 * @description Recent additions, scans and suggestions, newest first.
 * @summary Collection Activity
 * {@link /api/v1/collection/activity}
 */
export async function collectionActivity(
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<
    CollectionActivityQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: "GET",
    url: getCollectionActivityUrl().url.toString(),
    ...requestConfig,
  })
  return res.data
}
