/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/fetch"
import type {
  CompareCardsQueryResponse,
  CompareCardsQueryParams,
  CompareCards422,
} from "../types/CompareCards"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/fetch"

function getCompareCardsUrl() {
  const res = { method: "GET", url: `/api/v1/catalog/compare` as const }
  return res
}

/**
 * @description What a model sees when the two card images are put side by side.
 * @summary Compare Cards
 * {@link /api/v1/catalog/compare}
 */
export async function compareCards(
  params: CompareCardsQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<
    CompareCardsQueryResponse,
    ResponseErrorConfig<CompareCards422>,
    unknown
  >({
    method: "GET",
    url: getCompareCardsUrl().url.toString(),
    params,
    ...requestConfig,
  })
  return res.data
}
