/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/fetch"
import type {
  ConfirmScanMutationRequest,
  ConfirmScanMutationResponse,
  ConfirmScanPathParams,
  ConfirmScan422,
} from "../types/ConfirmScan"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/fetch"

function getConfirmScanUrl(scan_id: ConfirmScanPathParams["scan_id"]) {
  const res = {
    method: "POST",
    url: `/api/v1/scans/${scan_id}/confirm` as const,
  }
  return res
}

/**
 * @description Save the card the user picked from the candidates.
 * The choice is always the user's: a scan proposes, it never files anything on
 * its own.
 * @summary Confirm Scan
 * {@link /api/v1/scans/:scan_id/confirm}
 */
export async function confirmScan(
  scan_id: ConfirmScanPathParams["scan_id"],
  data: ConfirmScanMutationRequest,
  config: Partial<RequestConfig<ConfirmScanMutationRequest>> & {
    client?: Client
  } = {}
) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = data

  const res = await request<
    ConfirmScanMutationResponse,
    ResponseErrorConfig<ConfirmScan422>,
    ConfirmScanMutationRequest
  >({
    method: "POST",
    url: getConfirmScanUrl(scan_id).url.toString(),
    data: requestData,
    ...requestConfig,
  })
  return res.data
}
