/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/fetch"
import type {
  CounterOfferMutationRequest,
  CounterOfferMutationResponse,
  CounterOfferPathParams,
  CounterOffer422,
} from "../types/CounterOffer"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/fetch"

function getCounterOfferUrl(offer_id: CounterOfferPathParams["offer_id"]) {
  const res = {
    method: "POST",
    url: `/api/v1/trades/offers/${offer_id}/counter` as const,
  }
  return res
}

/**
 * @description Answer an offer with a different one, declining the original.
 * Only its recipient may, and the counter goes back to whoever sent it.
 * @summary Counter Offer
 * {@link /api/v1/trades/offers/:offer_id/counter}
 */
export async function counterOffer(
  offer_id: CounterOfferPathParams["offer_id"],
  data: CounterOfferMutationRequest,
  config: Partial<RequestConfig<CounterOfferMutationRequest>> & {
    client?: Client
  } = {}
) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = data

  const res = await request<
    CounterOfferMutationResponse,
    ResponseErrorConfig<CounterOffer422>,
    CounterOfferMutationRequest
  >({
    method: "POST",
    url: getCounterOfferUrl(offer_id).url.toString(),
    data: requestData,
    ...requestConfig,
  })
  return res.data
}
