/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/fetch"
import type { CreateShareLinkMutationResponse } from "../types/CreateShareLink"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/fetch"

function getCreateShareLinkUrl() {
  const res = { method: "POST", url: `/api/v1/share` as const }
  return res
}

/**
 * @summary Create Share Link
 * {@link /api/v1/share}
 */
export async function createShareLink(
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<
    CreateShareLinkMutationResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: "POST",
    url: getCreateShareLinkUrl().url.toString(),
    ...requestConfig,
  })
  return res.data
}
