/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/fetch"
import type {
  CreateOfferMutationRequest,
  CreateOfferMutationResponse,
  CreateOffer422,
} from "../types/CreateOffer"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/fetch"

function getCreateOfferUrl() {
  const res = { method: "POST", url: `/api/v1/trades/offers` as const }
  return res
}

/**
 * @description Propose a swap. Both sides must be cards their owner holds more than once.
 * @summary Create Offer
 * {@link /api/v1/trades/offers}
 */
export async function createOffer(
  data: CreateOfferMutationRequest,
  config: Partial<RequestConfig<CreateOfferMutationRequest>> & {
    client?: Client
  } = {}
) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = data

  const res = await request<
    CreateOfferMutationResponse,
    ResponseErrorConfig<CreateOffer422>,
    CreateOfferMutationRequest
  >({
    method: "POST",
    url: getCreateOfferUrl().url.toString(),
    data: requestData,
    ...requestConfig,
  })
  return res.data
}
