/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/fetch"
import type {
  ExportCollectionQueryResponse,
  ExportCollectionQueryParams,
  ExportCollection422,
} from "../types/ExportCollection"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/fetch"

function getExportCollectionUrl() {
  const res = { method: "GET", url: `/api/v1/collection/export` as const }
  return res
}

/**
 * @description The whole collection as a file, unpaginated: an export that stops at 200
 * rows is not an export.
 * @summary Export Collection
 * {@link /api/v1/collection/export}
 */
export async function exportCollection(
  params?: ExportCollectionQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<
    ExportCollectionQueryResponse,
    ResponseErrorConfig<ExportCollection422>,
    unknown
  >({
    method: "GET",
    url: getExportCollectionUrl().url.toString(),
    params,
    ...requestConfig,
  })
  return res.data
}
