/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/fetch"
import type {
  ForgetPreferenceMutationResponse,
  ForgetPreferencePathParams,
  ForgetPreference422,
} from "../types/ForgetPreference"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/fetch"

function getForgetPreferenceUrl(key: ForgetPreferencePathParams["key"]) {
  const res = { method: "DELETE", url: `/api/v1/preferences/${key}` as const }
  return res
}

/**
 * @summary Forget Preference
 * {@link /api/v1/preferences/:key}
 */
export async function forgetPreference(
  key: ForgetPreferencePathParams["key"],
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<
    ForgetPreferenceMutationResponse,
    ResponseErrorConfig<ForgetPreference422>,
    unknown
  >({
    method: "DELETE",
    url: getForgetPreferenceUrl(key).url.toString(),
    ...requestConfig,
  })
  return res.data
}
