/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/fetch"
import type {
  GetCardQueryResponse,
  GetCardPathParams,
  GetCard422,
} from "../types/GetCard"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/fetch"

function getGetCardUrl(card_id: GetCardPathParams["card_id"]) {
  const res = {
    method: "GET",
    url: `/api/v1/catalog/cards/${card_id}` as const,
  }
  return res
}

/**
 * @summary Get Card
 * {@link /api/v1/catalog/cards/:card_id}
 */
export async function getCard(
  card_id: GetCardPathParams["card_id"],
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<
    GetCardQueryResponse,
    ResponseErrorConfig<GetCard422>,
    unknown
  >({
    method: "GET",
    url: getGetCardUrl(card_id).url.toString(),
    ...requestConfig,
  })
  return res.data
}
