/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/fetch"
import type {
  GetCollectorQueryResponse,
  GetCollectorPathParams,
  GetCollector422,
} from "../types/GetCollector"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/fetch"

function getGetCollectorUrl(owner_id: GetCollectorPathParams["owner_id"]) {
  const res = {
    method: "GET",
    url: `/api/v1/trades/collectors/${owner_id}` as const,
  }
  return res
}

/**
 * @description One collector's public profile.
 * Counts, never money: what a collection is worth stays with whoever owns it.
 * Reading your own id returns the same shape with `is_self` set.
 * @summary Get Collector
 * {@link /api/v1/trades/collectors/:owner_id}
 */
export async function getCollector(
  owner_id: GetCollectorPathParams["owner_id"],
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<
    GetCollectorQueryResponse,
    ResponseErrorConfig<GetCollector422>,
    unknown
  >({
    method: "GET",
    url: getGetCollectorUrl(owner_id).url.toString(),
    ...requestConfig,
  })
  return res.data
}
