/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/fetch"
import type {
  GetItemQueryResponse,
  GetItemPathParams,
  GetItem422,
} from "../types/GetItem"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/fetch"

function getGetItemUrl(item_id: GetItemPathParams["item_id"]) {
  const res = { method: "GET", url: `/api/v1/collection/${item_id}` as const }
  return res
}

/**
 * @summary Get Item
 * {@link /api/v1/collection/:item_id}
 */
export async function getItem(
  item_id: GetItemPathParams["item_id"],
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<
    GetItemQueryResponse,
    ResponseErrorConfig<GetItem422>,
    unknown
  >({
    method: "GET",
    url: getGetItemUrl(item_id).url.toString(),
    ...requestConfig,
  })
  return res.data
}
