/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/fetch"
import type {
  GetScanImageQueryResponse,
  GetScanImagePathParams,
  GetScanImage422,
} from "../types/GetScanImage"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/fetch"

function getGetScanImageUrl(scan_id: GetScanImagePathParams["scan_id"]) {
  const res = { method: "GET", url: `/api/v1/scans/${scan_id}/image` as const }
  return res
}

/**
 * @description Scan photos are private, so they are streamed through auth rather than served
 * as static files. Mounting the directory would leak every user's photos.
 * @summary Get Scan Image
 * {@link /api/v1/scans/:scan_id/image}
 */
export async function getScanImage(
  scan_id: GetScanImagePathParams["scan_id"],
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<
    GetScanImageQueryResponse,
    ResponseErrorConfig<GetScanImage422>,
    unknown
  >({
    method: "GET",
    url: getGetScanImageUrl(scan_id).url.toString(),
    ...requestConfig,
  })
  return res.data
}
