/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/fetch"
import type { GetShareLinkQueryResponse } from "../types/GetShareLink"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/fetch"

function getGetShareLinkUrl() {
  const res = { method: "GET", url: `/api/v1/share` as const }
  return res
}

/**
 * @summary Get Share Link
 * {@link /api/v1/share}
 */
export async function getShareLink(
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<
    GetShareLinkQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: "GET",
    url: getGetShareLinkUrl().url.toString(),
    ...requestConfig,
  })
  return res.data
}
