/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/fetch"
import type {
  GetThreadWithQueryResponse,
  GetThreadWithPathParams,
  GetThreadWith422,
} from "../types/GetThreadWith"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/fetch"

function getGetThreadWithUrl(
  partner_id: GetThreadWithPathParams["partner_id"]
) {
  const res = {
    method: "GET",
    url: `/api/v1/messages/with/${partner_id}` as const,
  }
  return res
}

/**
 * @description The conversation with one collector, started or not.
 * @summary Get Thread With
 * {@link /api/v1/messages/with/:partner_id}
 */
export async function getThreadWith(
  partner_id: GetThreadWithPathParams["partner_id"],
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<
    GetThreadWithQueryResponse,
    ResponseErrorConfig<GetThreadWith422>,
    unknown
  >({
    method: "GET",
    url: getGetThreadWithUrl(partner_id).url.toString(),
    ...requestConfig,
  })
  return res.data
}
