/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/fetch"
import type { HealthQueryResponse } from "../types/Health"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/fetch"

function getHealthUrl() {
  const res = { method: "GET", url: `/health` as const }
  return res
}

/**
 * @summary Health
 * {@link /health}
 */
export async function health(
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<
    HealthQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({ method: "GET", url: getHealthUrl().url.toString(), ...requestConfig })
  return res.data
}
