/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/fetch"
import type {
  ListTradesQueryResponse,
  ListTradesQueryParams,
  ListTrades422,
} from "../types/ListTrades"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/fetch"

function getListTradesUrl() {
  const res = { method: "GET", url: `/api/v1/trades` as const }
  return res
}

/**
 * @description Collectors who want a spare card and hold a wanted one.
 * A match is a possibility, not an agreement: nothing here moves a card. The
 * cards named are only the two-way overlap, so what else a counterparty owns
 * stays theirs.
 * @summary List Trades
 * {@link /api/v1/trades}
 */
export async function listTrades(
  params?: ListTradesQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<
    ListTradesQueryResponse,
    ResponseErrorConfig<ListTrades422>,
    unknown
  >({
    method: "GET",
    url: getListTradesUrl().url.toString(),
    params,
    ...requestConfig,
  })
  return res.data
}
