/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/fetch"
import type { ListWishlistQueryResponse } from "../types/ListWishlist"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/fetch"

function getListWishlistUrl() {
  const res = { method: "GET", url: `/api/v1/wishlist` as const }
  return res
}

/**
 * @summary List Wishlist
 * {@link /api/v1/wishlist}
 */
export async function listWishlist(
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<
    ListWishlistQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: "GET",
    url: getListWishlistUrl().url.toString(),
    ...requestConfig,
  })
  return res.data
}
