/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/fetch"
import type {
  ListThreadsQueryResponse,
  ListThreadsQueryParams,
  ListThreads422,
} from "../types/ListThreads"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/fetch"

function getListThreadsUrl() {
  const res = { method: "GET", url: `/api/v1/messages` as const }
  return res
}

/**
 * @description Conversations the reader is in, most recently spoken in first.
 * @summary List Threads
 * {@link /api/v1/messages}
 */
export async function listThreads(
  params?: ListThreadsQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<
    ListThreadsQueryResponse,
    ResponseErrorConfig<ListThreads422>,
    unknown
  >({
    method: "GET",
    url: getListThreadsUrl().url.toString(),
    params,
    ...requestConfig,
  })
  return res.data
}
