/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/fetch"
import type {
  ListGapsQueryResponse,
  ListGapsQueryParams,
  ListGaps422,
} from "../types/ListGaps"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/fetch"

function getListGapsUrl() {
  const res = { method: "GET", url: `/api/v1/gaps` as const }
  return res
}

/**
 * @summary List Gaps
 * {@link /api/v1/gaps}
 */
export async function listGaps(
  params?: ListGapsQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<
    ListGapsQueryResponse,
    ResponseErrorConfig<ListGaps422>,
    unknown
  >({
    method: "GET",
    url: getListGapsUrl().url.toString(),
    params,
    ...requestConfig,
  })
  return res.data
}
