/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/fetch"
import type { ListConversationsQueryResponse } from "../types/ListConversations"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/fetch"

function getListConversationsUrl() {
  const res = { method: "GET", url: `/api/v1/chat` as const }
  return res
}

/**
 * @summary List Conversations
 * {@link /api/v1/chat}
 */
export async function listConversations(
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<
    ListConversationsQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: "GET",
    url: getListConversationsUrl().url.toString(),
    ...requestConfig,
  })
  return res.data
}
