/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/fetch"
import type {
  ListOffersQueryResponse,
  ListOffersQueryParams,
  ListOffers422,
} from "../types/ListOffers"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/fetch"

function getListOffersUrl() {
  const res = { method: "GET", url: `/api/v1/trades/offers` as const }
  return res
}

/**
 * @description Offers the reader is party to, sent and received, newest first.
 * @summary List Offers
 * {@link /api/v1/trades/offers}
 */
export async function listOffers(
  params?: ListOffersQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<
    ListOffersQueryResponse,
    ResponseErrorConfig<ListOffers422>,
    unknown
  >({
    method: "GET",
    url: getListOffersUrl().url.toString(),
    params,
    ...requestConfig,
  })
  return res.data
}
