/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/fetch"
import type {
  ListSparesQueryResponse,
  ListSparesPathParams,
  ListSparesQueryParams,
  ListSpares422,
} from "../types/ListSpares"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/fetch"

function getListSparesUrl(owner_id: ListSparesPathParams["owner_id"]) {
  const res = {
    method: "GET",
    url: `/api/v1/trades/collectors/${owner_id}/spares` as const,
  }
  return res
}

/**
 * @description One collector's spare cards, with the reader's wants marked.
 * Pass the reader's own id to browse what they have free to offer.
 * @summary List Spares
 * {@link /api/v1/trades/collectors/:owner_id/spares}
 */
export async function listSpares(
  owner_id: ListSparesPathParams["owner_id"],
  params?: ListSparesQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<
    ListSparesQueryResponse,
    ResponseErrorConfig<ListSpares422>,
    unknown
  >({
    method: "GET",
    url: getListSparesUrl(owner_id).url.toString(),
    params,
    ...requestConfig,
  })
  return res.data
}
