/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/fetch"
import type {
  ListCollectionQueryResponse,
  ListCollectionQueryParams,
  ListCollection422,
} from "../types/ListCollection"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/fetch"

function getListCollectionUrl() {
  const res = { method: "GET", url: `/api/v1/collection` as const }
  return res
}

/**
 * @summary List Collection
 * {@link /api/v1/collection}
 */
export async function listCollection(
  params?: ListCollectionQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<
    ListCollectionQueryResponse,
    ResponseErrorConfig<ListCollection422>,
    unknown
  >({
    method: "GET",
    url: getListCollectionUrl().url.toString(),
    params,
    ...requestConfig,
  })
  return res.data
}
