/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/fetch"
import type {
  ListCollectorsQueryResponse,
  ListCollectorsQueryParams,
  ListCollectors422,
} from "../types/ListCollectors"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/fetch"

function getListCollectorsUrl() {
  const res = { method: "GET", url: `/api/v1/trades/collectors` as const }
  return res
}

/**
 * @description Collectors with cards free to trade, and how they line up with the reader.
 * A collector appears whether or not a swap already works out. What is shown
 * about them is only what could move: how much is spare, and how much of it
 * either side wants.
 * @summary List Collectors
 * {@link /api/v1/trades/collectors}
 */
export async function listCollectors(
  params?: ListCollectorsQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<
    ListCollectorsQueryResponse,
    ResponseErrorConfig<ListCollectors422>,
    unknown
  >({
    method: "GET",
    url: getListCollectorsUrl().url.toString(),
    params,
    ...requestConfig,
  })
  return res.data
}
