/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/fetch"
import type {
  ListListingsQueryResponse,
  ListListingsQueryParams,
  ListListings422,
} from "../types/ListListings"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/fetch"

function getListListingsUrl() {
  const res = { method: "GET", url: `/api/v1/trades/listings` as const }
  return res
}

/**
 * @description The open board: swaps published to whoever can fill them.
 * Unlike an offer, a listing is addressed to nobody and every collector reads
 * the same one. What changes per reader is only whether they can take it.
 * @summary List Listings
 * {@link /api/v1/trades/listings}
 */
export async function listListings(
  params?: ListListingsQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<
    ListListingsQueryResponse,
    ResponseErrorConfig<ListListings422>,
    unknown
  >({
    method: "GET",
    url: getListListingsUrl().url.toString(),
    params,
    ...requestConfig,
  })
  return res.data
}
