/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/fetch"
import type {
  ListThreadMessagesQueryResponse,
  ListThreadMessagesPathParams,
  ListThreadMessagesQueryParams,
  ListThreadMessages422,
} from "../types/ListThreadMessages"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/fetch"

function getListThreadMessagesUrl(
  thread_id: ListThreadMessagesPathParams["thread_id"]
) {
  const res = {
    method: "GET",
    url: `/api/v1/messages/${thread_id}/messages` as const,
  }
  return res
}

/**
 * @description What was said, newest page first. Only the two participants may read it.
 * @summary List Thread Messages
 * {@link /api/v1/messages/:thread_id/messages}
 */
export async function listThreadMessages(
  thread_id: ListThreadMessagesPathParams["thread_id"],
  params?: ListThreadMessagesQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<
    ListThreadMessagesQueryResponse,
    ResponseErrorConfig<ListThreadMessages422>,
    unknown
  >({
    method: "GET",
    url: getListThreadMessagesUrl(thread_id).url.toString(),
    params,
    ...requestConfig,
  })
  return res.data
}
