/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/fetch"
import type {
  MarkThreadReadMutationResponse,
  MarkThreadReadPathParams,
  MarkThreadRead422,
} from "../types/MarkThreadRead"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/fetch"

function getMarkThreadReadUrl(
  thread_id: MarkThreadReadPathParams["thread_id"]
) {
  const res = {
    method: "POST",
    url: `/api/v1/messages/${thread_id}/read` as const,
  }
  return res
}

/**
 * @description Mark what the other one said as read.
 * @summary Mark Thread Read
 * {@link /api/v1/messages/:thread_id/read}
 */
export async function markThreadRead(
  thread_id: MarkThreadReadPathParams["thread_id"],
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<
    MarkThreadReadMutationResponse,
    ResponseErrorConfig<MarkThreadRead422>,
    unknown
  >({
    method: "POST",
    url: getMarkThreadReadUrl(thread_id).url.toString(),
    ...requestConfig,
  })
  return res.data
}
