/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/fetch"
import type { MarketSetsQueryResponse } from "../types/MarketSets"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/fetch"

function getMarketSetsUrl() {
  const res = { method: "GET", url: `/api/v1/catalog/market/sets` as const }
  return res
}

/**
 * @description Each set as a position, costliest to finish first.
 * @summary Market Sets
 * {@link /api/v1/catalog/market/sets}
 */
export async function marketSets(
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<
    MarketSetsQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({ method: "GET", url: getMarketSetsUrl().url.toString(), ...requestConfig })
  return res.data
}
