/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/fetch"
import type {
  MarketPositionsQueryResponse,
  MarketPositionsQueryParams,
  MarketPositions422,
} from "../types/MarketPositions"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/fetch"

function getMarketPositionsUrl() {
  const res = {
    method: "GET",
    url: `/api/v1/catalog/market/positions` as const,
  }
  return res
}

/**
 * @description Every held card as a position: cost, value, gain and weight in the portfolio.
 * @summary Market Positions
 * {@link /api/v1/catalog/market/positions}
 */
export async function marketPositions(
  params?: MarketPositionsQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<
    MarketPositionsQueryResponse,
    ResponseErrorConfig<MarketPositions422>,
    unknown
  >({
    method: "GET",
    url: getMarketPositionsUrl().url.toString(),
    params,
    ...requestConfig,
  })
  return res.data
}
