/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/fetch";
import type { MarkNewsSeenMutationResponse } from "../types/MarkNewsSeen";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/fetch";

function getMarkNewsSeenUrl() {
  const res = { method: "POST", url: `/api/v1/news/seen` as const };
  return res;
}

/**
 * @summary Mark News Seen
 * {@link /api/v1/news/seen}
 */
export async function markNewsSeen(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    MarkNewsSeenMutationResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: "POST",
    url: getMarkNewsSeenUrl().url.toString(),
    ...requestConfig,
  });
  return res.data;
}
