/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/fetch"
import type {
  MarketCardsQueryResponse,
  MarketCardsQueryParams,
  MarketCards422,
} from "../types/MarketCards"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/fetch"

function getMarketCardsUrl() {
  const res = { method: "GET", url: `/api/v1/catalog/market` as const }
  return res
}

/**
 * @description The whole catalog, each card marked with how many copies the reader holds.
 * @summary Market Cards
 * {@link /api/v1/catalog/market}
 */
export async function marketCards(
  params?: MarketCardsQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<
    MarketCardsQueryResponse,
    ResponseErrorConfig<MarketCards422>,
    unknown
  >({
    method: "GET",
    url: getMarketCardsUrl().url.toString(),
    params,
    ...requestConfig,
  })
  return res.data
}
