/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/fetch"
import type { MarketSummaryQueryResponse } from "../types/MarketSummary"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/fetch"

function getMarketSummaryUrl() {
  const res = { method: "GET", url: `/api/v1/catalog/market/summary` as const }
  return res
}

/**
 * @summary Market Summary
 * {@link /api/v1/catalog/market/summary}
 */
export async function marketSummary(
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<
    MarketSummaryQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: "GET",
    url: getMarketSummaryUrl().url.toString(),
    ...requestConfig,
  })
  return res.data
}
