/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/fetch"
import type { MeQueryResponse } from "../types/Me"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/fetch"

function getMeUrl() {
  const res = { method: "GET", url: `/api/v1/me` as const }
  return res
}

/**
 * @summary Me
 * {@link /api/v1/me}
 */
export async function me(
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<
    MeQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({ method: "GET", url: getMeUrl().url.toString(), ...requestConfig })
  return res.data
}
