/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/fetch";
import type {
  NewsFeedQueryResponse,
  NewsFeedQueryParams,
  NewsFeed422,
} from "../types/NewsFeed";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/fetch";

function getNewsFeedUrl() {
  const res = { method: "GET", url: `/api/v1/news` as const };
  return res;
}

/**
 * @summary News Feed
 * {@link /api/v1/news}
 */
export async function newsFeed(
  params?: NewsFeedQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    NewsFeedQueryResponse,
    ResponseErrorConfig<NewsFeed422>,
    unknown
  >({
    method: "GET",
    url: getNewsFeedUrl().url.toString(),
    params,
    ...requestConfig,
  });
  return res.data;
}
