/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/fetch"
import type { OwnedCardIdsQueryResponse } from "../types/OwnedCardIds"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/fetch"

function getOwnedCardIdsUrl() {
  const res = { method: "GET", url: `/api/v1/catalog/owned-ids` as const }
  return res
}

/**
 * @description Which catalog cards the user holds, so a card list can mark them.
 * @summary Owned Card Ids
 * {@link /api/v1/catalog/owned-ids}
 */
export async function ownedCardIds(
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<
    OwnedCardIdsQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: "GET",
    url: getOwnedCardIdsUrl().url.toString(),
    ...requestConfig,
  })
  return res.data
}
