/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/fetch";
import type {
  ProposeTradeMutationRequest,
  ProposeTradeMutationResponse,
  ProposeTrade422,
} from "../types/ProposeTrade";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/fetch";

function getProposeTradeUrl() {
  const res = { method: "POST", url: `/api/v1/advice/trade` as const };
  return res;
}

/**
 * @description One swap worth simulating, drawn from what the reader has spare and wants.
 * @summary Propose Trade
 * {@link /api/v1/advice/trade}
 */
export async function proposeTrade(
  data: ProposeTradeMutationRequest,
  config: Partial<RequestConfig<ProposeTradeMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    ProposeTradeMutationResponse,
    ResponseErrorConfig<ProposeTrade422>,
    ProposeTradeMutationRequest
  >({
    method: "POST",
    url: getProposeTradeUrl().url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
