/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/fetch"
import type {
  PublishListingMutationRequest,
  PublishListingMutationResponse,
  PublishListing422,
} from "../types/PublishListing"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/fetch"

function getPublishListingUrl() {
  const res = { method: "POST", url: `/api/v1/trades/listings` as const }
  return res
}

/**
 * @description Publish a swap. What you give must be spare; what you ask for need not be.
 * @summary Publish Listing
 * {@link /api/v1/trades/listings}
 */
export async function publishListing(
  data: PublishListingMutationRequest,
  config: Partial<RequestConfig<PublishListingMutationRequest>> & {
    client?: Client
  } = {}
) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = data

  const res = await request<
    PublishListingMutationResponse,
    ResponseErrorConfig<PublishListing422>,
    PublishListingMutationRequest
  >({
    method: "POST",
    url: getPublishListingUrl().url.toString(),
    data: requestData,
    ...requestConfig,
  })
  return res.data
}
