/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/fetch"
import type {
  ReadSharedCollectionQueryResponse,
  ReadSharedCollectionPathParams,
  ReadSharedCollection422,
} from "../types/ReadSharedCollection"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/fetch"

function getReadSharedCollectionUrl(
  token: ReadSharedCollectionPathParams["token"]
) {
  const res = { method: "GET", url: `/api/v1/public/${token}` as const }
  return res
}

/**
 * @description The only unauthenticated route in the API.
 * It answers 404 for a revoked link exactly as it does for one that never
 * existed, so a revoked token cannot be told apart from a wrong guess.
 * @summary Read Shared Collection
 * {@link /api/v1/public/:token}
 */
export async function readSharedCollection(
  token: ReadSharedCollectionPathParams["token"],
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<
    ReadSharedCollectionQueryResponse,
    ResponseErrorConfig<ReadSharedCollection422>,
    unknown
  >({
    method: "GET",
    url: getReadSharedCollectionUrl(token).url.toString(),
    ...requestConfig,
  })
  return res.data
}
