/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/fetch"
import type {
  RemoveFromWishlistMutationResponse,
  RemoveFromWishlistPathParams,
  RemoveFromWishlist422,
} from "../types/RemoveFromWishlist"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/fetch"

function getRemoveFromWishlistUrl(
  item_id: RemoveFromWishlistPathParams["item_id"]
) {
  const res = { method: "DELETE", url: `/api/v1/wishlist/${item_id}` as const }
  return res
}

/**
 * @summary Remove From Wishlist
 * {@link /api/v1/wishlist/:item_id}
 */
export async function removeFromWishlist(
  item_id: RemoveFromWishlistPathParams["item_id"],
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<
    RemoveFromWishlistMutationResponse,
    ResponseErrorConfig<RemoveFromWishlist422>,
    unknown
  >({
    method: "DELETE",
    url: getRemoveFromWishlistUrl(item_id).url.toString(),
    ...requestConfig,
  })
  return res.data
}
