/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/fetch"
import type {
  RemoveItemMutationResponse,
  RemoveItemPathParams,
  RemoveItem422,
} from "../types/RemoveItem"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/fetch"

function getRemoveItemUrl(item_id: RemoveItemPathParams["item_id"]) {
  const res = {
    method: "DELETE",
    url: `/api/v1/collection/${item_id}` as const,
  }
  return res
}

/**
 * @summary Remove Item
 * {@link /api/v1/collection/:item_id}
 */
export async function removeItem(
  item_id: RemoveItemPathParams["item_id"],
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<
    RemoveItemMutationResponse,
    ResponseErrorConfig<RemoveItem422>,
    unknown
  >({
    method: "DELETE",
    url: getRemoveItemUrl(item_id).url.toString(),
    ...requestConfig,
  })
  return res.data
}
