/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/fetch"
import type {
  RespondToOfferMutationRequest,
  RespondToOfferMutationResponse,
  RespondToOfferPathParams,
  RespondToOffer422,
} from "../types/RespondToOffer"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/fetch"

function getRespondToOfferUrl(offer_id: RespondToOfferPathParams["offer_id"]) {
  const res = {
    method: "POST",
    url: `/api/v1/trades/offers/${offer_id}/respond` as const,
  }
  return res
}

/**
 * @description Accept or decline an offer. Only its recipient may, and only once.
 * @summary Respond To Offer
 * {@link /api/v1/trades/offers/:offer_id/respond}
 */
export async function respondToOffer(
  offer_id: RespondToOfferPathParams["offer_id"],
  data: RespondToOfferMutationRequest,
  config: Partial<RequestConfig<RespondToOfferMutationRequest>> & {
    client?: Client
  } = {}
) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = data

  const res = await request<
    RespondToOfferMutationResponse,
    ResponseErrorConfig<RespondToOffer422>,
    RespondToOfferMutationRequest
  >({
    method: "POST",
    url: getRespondToOfferUrl(offer_id).url.toString(),
    data: requestData,
    ...requestConfig,
  })
  return res.data
}
