/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/fetch"
import type { RevokeShareLinkMutationResponse } from "../types/RevokeShareLink"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/fetch"

function getRevokeShareLinkUrl() {
  const res = { method: "DELETE", url: `/api/v1/share` as const }
  return res
}

/**
 * @summary Revoke Share Link
 * {@link /api/v1/share}
 */
export async function revokeShareLink(
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<
    RevokeShareLinkMutationResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: "DELETE",
    url: getRevokeShareLinkUrl().url.toString(),
    ...requestConfig,
  })
  return res.data
}
