/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/fetch"
import type {
  SearchCardsQueryResponse,
  SearchCardsQueryParams,
  SearchCards422,
} from "../types/SearchCards"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/fetch"

function getSearchCardsUrl() {
  const res = { method: "GET", url: `/api/v1/catalog/cards` as const }
  return res
}

/**
 * @summary Search Cards
 * {@link /api/v1/catalog/cards}
 */
export async function searchCards(
  params?: SearchCardsQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<
    SearchCardsQueryResponse,
    ResponseErrorConfig<SearchCards422>,
    unknown
  >({
    method: "GET",
    url: getSearchCardsUrl().url.toString(),
    params,
    ...requestConfig,
  })
  return res.data
}
