/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/fetch"
import type {
  SearchSpeciesQueryResponse,
  SearchSpeciesQueryParams,
  SearchSpecies422,
} from "../types/SearchSpecies"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/fetch"

function getSearchSpeciesUrl() {
  const res = { method: "GET", url: `/api/v1/catalog/species` as const }
  return res
}

/**
 * @summary Search Species
 * {@link /api/v1/catalog/species}
 */
export async function searchSpecies(
  params?: SearchSpeciesQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<
    SearchSpeciesQueryResponse,
    ResponseErrorConfig<SearchSpecies422>,
    unknown
  >({
    method: "GET",
    url: getSearchSpeciesUrl().url.toString(),
    params,
    ...requestConfig,
  })
  return res.data
}
