/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/fetch"
import type {
  SimulateTradeMutationRequest,
  SimulateTradeMutationResponse,
  SimulateTrade422,
} from "../types/SimulateTrade"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/fetch"

function getSimulateTradeUrl() {
  const res = {
    method: "POST",
    url: `/api/v1/catalog/market/simulate` as const,
  }
  return res
}

/**
 * @description What a swap would do to the portfolio. Reads only; nothing is traded.
 * @summary Simulate Trade
 * {@link /api/v1/catalog/market/simulate}
 */
export async function simulateTrade(
  data: SimulateTradeMutationRequest,
  config: Partial<RequestConfig<SimulateTradeMutationRequest>> & {
    client?: Client
  } = {}
) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = data

  const res = await request<
    SimulateTradeMutationResponse,
    ResponseErrorConfig<SimulateTrade422>,
    SimulateTradeMutationRequest
  >({
    method: "POST",
    url: getSimulateTradeUrl().url.toString(),
    data: requestData,
    ...requestConfig,
  })
  return res.data
}
