/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/fetch"
import type {
  SpeciesEvolutionsQueryResponse,
  SpeciesEvolutionsPathParams,
  SpeciesEvolutions422,
} from "../types/SpeciesEvolutions"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/fetch"

function getSpeciesEvolutionsUrl(
  species_id: SpeciesEvolutionsPathParams["species_id"]
) {
  const res = {
    method: "GET",
    url: `/api/v1/catalog/species/${species_id}/evolutions` as const,
  }
  return res
}

/**
 * @description The evolution family this species belongs to, in dex order.
 * Empty for a species with no family, so the caller renders nothing rather
 * than a panel that only says a Pokemon evolves into no one.
 * @summary Species Evolutions
 * {@link /api/v1/catalog/species/:species_id/evolutions}
 */
export async function speciesEvolutions(
  species_id: SpeciesEvolutionsPathParams["species_id"],
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<
    SpeciesEvolutionsQueryResponse,
    ResponseErrorConfig<SpeciesEvolutions422>,
    unknown
  >({
    method: "GET",
    url: getSpeciesEvolutionsUrl(species_id).url.toString(),
    ...requestConfig,
  })
  return res.data
}
