/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/fetch"
import type {
  WithdrawOfferMutationResponse,
  WithdrawOfferPathParams,
  WithdrawOffer422,
} from "../types/WithdrawOffer"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/fetch"

function getWithdrawOfferUrl(offer_id: WithdrawOfferPathParams["offer_id"]) {
  const res = {
    method: "POST",
    url: `/api/v1/trades/offers/${offer_id}/withdraw` as const,
  }
  return res
}

/**
 * @description Pull back an offer. Only its author, and only while it is unanswered.
 * @summary Withdraw Offer
 * {@link /api/v1/trades/offers/:offer_id/withdraw}
 */
export async function withdrawOffer(
  offer_id: WithdrawOfferPathParams["offer_id"],
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<
    WithdrawOfferMutationResponse,
    ResponseErrorConfig<WithdrawOffer422>,
    unknown
  >({
    method: "POST",
    url: getWithdrawOfferUrl(offer_id).url.toString(),
    ...requestConfig,
  })
  return res.data
}
