/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  AddToWishlistMutationRequest,
  AddToWishlistMutationResponse,
  AddToWishlist422,
} from "../types/AddToWishlist"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios"
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query"
import { addToWishlist } from "../clients/addToWishlist"
import { mutationOptions, useMutation } from "@tanstack/react-query"

export const addToWishlistMutationKey = () =>
  [{ url: "/api/v1/wishlist" }] as const

export type AddToWishlistMutationKey = ReturnType<
  typeof addToWishlistMutationKey
>

export function addToWishlistMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig<AddToWishlistMutationRequest>> & {
    client?: Client
  } = {}
) {
  const mutationKey = addToWishlistMutationKey()
  return mutationOptions<
    AddToWishlistMutationResponse,
    ResponseErrorConfig<AddToWishlist422>,
    { data: AddToWishlistMutationRequest },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ data }) => {
      return addToWishlist(data, config)
    },
  })
}

/**
 * @summary Add To Wishlist
 * {@link /api/v1/wishlist}
 */
export function useAddToWishlist<TContext>(
  options: {
    mutation?: UseMutationOptions<
      AddToWishlistMutationResponse,
      ResponseErrorConfig<AddToWishlist422>,
      { data: AddToWishlistMutationRequest },
      TContext
    > & { client?: QueryClient }
    client?: Partial<RequestConfig<AddToWishlistMutationRequest>> & {
      client?: Client
    }
  } = {}
) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation
  const mutationKey = mutationOptions.mutationKey ?? addToWishlistMutationKey()

  const baseOptions = addToWishlistMutationOptions(
    config
  ) as UseMutationOptions<
    AddToWishlistMutationResponse,
    ResponseErrorConfig<AddToWishlist422>,
    { data: AddToWishlistMutationRequest },
    TContext
  >

  return useMutation<
    AddToWishlistMutationResponse,
    ResponseErrorConfig<AddToWishlist422>,
    { data: AddToWishlistMutationRequest },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient
  ) as UseMutationResult<
    AddToWishlistMutationResponse,
    ResponseErrorConfig<AddToWishlist422>,
    { data: AddToWishlistMutationRequest },
    TContext
  >
}
