/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  AcceptListingMutationResponse,
  AcceptListingPathParams,
  AcceptListing422,
} from "../types/AcceptListing"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios"
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query"
import { acceptListing } from "../clients/acceptListing"
import { mutationOptions, useMutation } from "@tanstack/react-query"

export const acceptListingMutationKey = () =>
  [{ url: "/api/v1/trades/listings/:listing_id/accept" }] as const

export type AcceptListingMutationKey = ReturnType<
  typeof acceptListingMutationKey
>

export function acceptListingMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const mutationKey = acceptListingMutationKey()
  return mutationOptions<
    AcceptListingMutationResponse,
    ResponseErrorConfig<AcceptListing422>,
    { listing_id: AcceptListingPathParams["listing_id"] },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ listing_id }) => {
      return acceptListing(listing_id, config)
    },
  })
}

/**
 * @description Take a listing, which agrees it: the answer is the trade it became.
 * @summary Accept Listing
 * {@link /api/v1/trades/listings/:listing_id/accept}
 */
export function useAcceptListing<TContext>(
  options: {
    mutation?: UseMutationOptions<
      AcceptListingMutationResponse,
      ResponseErrorConfig<AcceptListing422>,
      { listing_id: AcceptListingPathParams["listing_id"] },
      TContext
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {}
) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation
  const mutationKey = mutationOptions.mutationKey ?? acceptListingMutationKey()

  const baseOptions = acceptListingMutationOptions(
    config
  ) as UseMutationOptions<
    AcceptListingMutationResponse,
    ResponseErrorConfig<AcceptListing422>,
    { listing_id: AcceptListingPathParams["listing_id"] },
    TContext
  >

  return useMutation<
    AcceptListingMutationResponse,
    ResponseErrorConfig<AcceptListing422>,
    { listing_id: AcceptListingPathParams["listing_id"] },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient
  ) as UseMutationResult<
    AcceptListingMutationResponse,
    ResponseErrorConfig<AcceptListing422>,
    { listing_id: AcceptListingPathParams["listing_id"] },
    TContext
  >
}
