/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  AddCardMutationRequest,
  AddCardMutationResponse,
  AddCard422,
} from "../types/AddCard"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios"
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query"
import { addCard } from "../clients/addCard"
import { mutationOptions, useMutation } from "@tanstack/react-query"

export const addCardMutationKey = () => [{ url: "/api/v1/collection" }] as const

export type AddCardMutationKey = ReturnType<typeof addCardMutationKey>

export function addCardMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig<AddCardMutationRequest>> & {
    client?: Client
  } = {}
) {
  const mutationKey = addCardMutationKey()
  return mutationOptions<
    AddCardMutationResponse,
    ResponseErrorConfig<AddCard422>,
    { data: AddCardMutationRequest },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ data }) => {
      return addCard(data, config)
    },
  })
}

/**
 * @summary Add Card
 * {@link /api/v1/collection}
 */
export function useAddCard<TContext>(
  options: {
    mutation?: UseMutationOptions<
      AddCardMutationResponse,
      ResponseErrorConfig<AddCard422>,
      { data: AddCardMutationRequest },
      TContext
    > & { client?: QueryClient }
    client?: Partial<RequestConfig<AddCardMutationRequest>> & {
      client?: Client
    }
  } = {}
) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation
  const mutationKey = mutationOptions.mutationKey ?? addCardMutationKey()

  const baseOptions = addCardMutationOptions(config) as UseMutationOptions<
    AddCardMutationResponse,
    ResponseErrorConfig<AddCard422>,
    { data: AddCardMutationRequest },
    TContext
  >

  return useMutation<
    AddCardMutationResponse,
    ResponseErrorConfig<AddCard422>,
    { data: AddCardMutationRequest },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient
  ) as UseMutationResult<
    AddCardMutationResponse,
    ResponseErrorConfig<AddCard422>,
    { data: AddCardMutationRequest },
    TContext
  >
}
