/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CollectionStatsQueryResponse } from "../types/CollectionStats"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios"
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query"
import { collectionStats } from "../clients/collectionStats"
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query"

export const collectionStatsSuspenseQueryKey = () =>
  [{ url: "/api/v1/stats" }] as const

export type CollectionStatsSuspenseQueryKey = ReturnType<
  typeof collectionStatsSuspenseQueryKey
>

export function collectionStatsSuspenseQueryOptions(
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = collectionStatsSuspenseQueryKey()
  return queryOptions<
    CollectionStatsQueryResponse,
    ResponseErrorConfig<Error>,
    CollectionStatsQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return collectionStats({ ...config, signal: config.signal ?? signal })
    },
  })
}

/**
 * @summary Collection Stats
 * {@link /api/v1/stats}
 */
export function useCollectionStatsSuspense<
  TData = CollectionStatsQueryResponse,
  TQueryKey extends QueryKey = CollectionStatsSuspenseQueryKey,
>(
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        CollectionStatsQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey =
    resolvedOptions?.queryKey ?? collectionStatsSuspenseQueryKey()

  const query = useSuspenseQuery(
    {
      ...collectionStatsSuspenseQueryOptions(config),
      ...resolvedOptions,
      queryKey,
    } as unknown as UseSuspenseQueryOptions,
    queryClient
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey
  }

  query.queryKey = queryKey as TQueryKey

  return query
}
