/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  ConfirmScanMutationRequest,
  ConfirmScanMutationResponse,
  ConfirmScanPathParams,
  ConfirmScan422,
} from "../types/ConfirmScan"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios"
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query"
import { confirmScan } from "../clients/confirmScan"
import { mutationOptions, useMutation } from "@tanstack/react-query"

export const confirmScanMutationKey = () =>
  [{ url: "/api/v1/scans/:scan_id/confirm" }] as const

export type ConfirmScanMutationKey = ReturnType<typeof confirmScanMutationKey>

export function confirmScanMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig<ConfirmScanMutationRequest>> & {
    client?: Client
  } = {}
) {
  const mutationKey = confirmScanMutationKey()
  return mutationOptions<
    ConfirmScanMutationResponse,
    ResponseErrorConfig<ConfirmScan422>,
    {
      scan_id: ConfirmScanPathParams["scan_id"]
      data: ConfirmScanMutationRequest
    },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ scan_id, data }) => {
      return confirmScan(scan_id, data, config)
    },
  })
}

/**
 * @description Save the card the user picked from the candidates.
 * The choice is always the user's: a scan proposes, it never files anything on
 * its own.
 * @summary Confirm Scan
 * {@link /api/v1/scans/:scan_id/confirm}
 */
export function useConfirmScan<TContext>(
  options: {
    mutation?: UseMutationOptions<
      ConfirmScanMutationResponse,
      ResponseErrorConfig<ConfirmScan422>,
      {
        scan_id: ConfirmScanPathParams["scan_id"]
        data: ConfirmScanMutationRequest
      },
      TContext
    > & { client?: QueryClient }
    client?: Partial<RequestConfig<ConfirmScanMutationRequest>> & {
      client?: Client
    }
  } = {}
) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation
  const mutationKey = mutationOptions.mutationKey ?? confirmScanMutationKey()

  const baseOptions = confirmScanMutationOptions(config) as UseMutationOptions<
    ConfirmScanMutationResponse,
    ResponseErrorConfig<ConfirmScan422>,
    {
      scan_id: ConfirmScanPathParams["scan_id"]
      data: ConfirmScanMutationRequest
    },
    TContext
  >

  return useMutation<
    ConfirmScanMutationResponse,
    ResponseErrorConfig<ConfirmScan422>,
    {
      scan_id: ConfirmScanPathParams["scan_id"]
      data: ConfirmScanMutationRequest
    },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient
  ) as UseMutationResult<
    ConfirmScanMutationResponse,
    ResponseErrorConfig<ConfirmScan422>,
    {
      scan_id: ConfirmScanPathParams["scan_id"]
      data: ConfirmScanMutationRequest
    },
    TContext
  >
}
