/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  CancelListingMutationResponse,
  CancelListingPathParams,
  CancelListing422,
} from "../types/CancelListing"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios"
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query"
import { cancelListing } from "../clients/cancelListing"
import { mutationOptions, useMutation } from "@tanstack/react-query"

export const cancelListingMutationKey = () =>
  [{ url: "/api/v1/trades/listings/:listing_id/cancel" }] as const

export type CancelListingMutationKey = ReturnType<
  typeof cancelListingMutationKey
>

export function cancelListingMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const mutationKey = cancelListingMutationKey()
  return mutationOptions<
    CancelListingMutationResponse,
    ResponseErrorConfig<CancelListing422>,
    { listing_id: CancelListingPathParams["listing_id"] },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ listing_id }) => {
      return cancelListing(listing_id, config)
    },
  })
}

/**
 * @description Take a listing off the board. Only its publisher, and only while open.
 * @summary Cancel Listing
 * {@link /api/v1/trades/listings/:listing_id/cancel}
 */
export function useCancelListing<TContext>(
  options: {
    mutation?: UseMutationOptions<
      CancelListingMutationResponse,
      ResponseErrorConfig<CancelListing422>,
      { listing_id: CancelListingPathParams["listing_id"] },
      TContext
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {}
) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation
  const mutationKey = mutationOptions.mutationKey ?? cancelListingMutationKey()

  const baseOptions = cancelListingMutationOptions(
    config
  ) as UseMutationOptions<
    CancelListingMutationResponse,
    ResponseErrorConfig<CancelListing422>,
    { listing_id: CancelListingPathParams["listing_id"] },
    TContext
  >

  return useMutation<
    CancelListingMutationResponse,
    ResponseErrorConfig<CancelListing422>,
    { listing_id: CancelListingPathParams["listing_id"] },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient
  ) as UseMutationResult<
    CancelListingMutationResponse,
    ResponseErrorConfig<CancelListing422>,
    { listing_id: CancelListingPathParams["listing_id"] },
    TContext
  >
}
