/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CollectionStatsQueryResponse } from "../types/CollectionStats"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios"
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query"
import { collectionStats } from "../clients/collectionStats"
import { queryOptions, useQuery } from "@tanstack/react-query"

export const collectionStatsQueryKey = () => [{ url: "/api/v1/stats" }] as const

export type CollectionStatsQueryKey = ReturnType<typeof collectionStatsQueryKey>

export function collectionStatsQueryOptions(
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = collectionStatsQueryKey()
  return queryOptions<
    CollectionStatsQueryResponse,
    ResponseErrorConfig<Error>,
    CollectionStatsQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return collectionStats({ ...config, signal: config.signal ?? signal })
    },
  })
}

/**
 * @summary Collection Stats
 * {@link /api/v1/stats}
 */
export function useCollectionStats<
  TData = CollectionStatsQueryResponse,
  TQueryData = CollectionStatsQueryResponse,
  TQueryKey extends QueryKey = CollectionStatsQueryKey,
>(
  options: {
    query?: Partial<
      QueryObserverOptions<
        CollectionStatsQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey = resolvedOptions?.queryKey ?? collectionStatsQueryKey()

  const query = useQuery(
    {
      ...collectionStatsQueryOptions(config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey
  }

  query.queryKey = queryKey as TQueryKey

  return query
}
