/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CreateShareLinkMutationResponse } from "../types/CreateShareLink"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios"
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query"
import { createShareLink } from "../clients/createShareLink"
import { mutationOptions, useMutation } from "@tanstack/react-query"

export const createShareLinkMutationKey = () =>
  [{ url: "/api/v1/share" }] as const

export type CreateShareLinkMutationKey = ReturnType<
  typeof createShareLinkMutationKey
>

export function createShareLinkMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const mutationKey = createShareLinkMutationKey()
  return mutationOptions<
    CreateShareLinkMutationResponse,
    ResponseErrorConfig<Error>,
    void,
    TContext
  >({
    mutationKey,
    mutationFn: async () => {
      return createShareLink(config)
    },
  })
}

/**
 * @summary Create Share Link
 * {@link /api/v1/share}
 */
export function useCreateShareLink<TContext>(
  options: {
    mutation?: UseMutationOptions<
      CreateShareLinkMutationResponse,
      ResponseErrorConfig<Error>,
      void,
      TContext
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {}
) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation
  const mutationKey =
    mutationOptions.mutationKey ?? createShareLinkMutationKey()

  const baseOptions = createShareLinkMutationOptions(
    config
  ) as UseMutationOptions<
    CreateShareLinkMutationResponse,
    ResponseErrorConfig<Error>,
    void,
    TContext
  >

  return useMutation<
    CreateShareLinkMutationResponse,
    ResponseErrorConfig<Error>,
    void,
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient
  ) as UseMutationResult<
    CreateShareLinkMutationResponse,
    ResponseErrorConfig<Error>,
    void,
    TContext
  >
}
