/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CollectionActivityQueryResponse } from "../types/CollectionActivity"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios"
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query"
import { collectionActivity } from "../clients/collectionActivity"
import { queryOptions, useQuery } from "@tanstack/react-query"

export const collectionActivityQueryKey = () =>
  [{ url: "/api/v1/collection/activity" }] as const

export type CollectionActivityQueryKey = ReturnType<
  typeof collectionActivityQueryKey
>

export function collectionActivityQueryOptions(
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = collectionActivityQueryKey()
  return queryOptions<
    CollectionActivityQueryResponse,
    ResponseErrorConfig<Error>,
    CollectionActivityQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return collectionActivity({ ...config, signal: config.signal ?? signal })
    },
  })
}

/**
 * @description Recent additions, scans and suggestions, newest first.
 * @summary Collection Activity
 * {@link /api/v1/collection/activity}
 */
export function useCollectionActivity<
  TData = CollectionActivityQueryResponse,
  TQueryData = CollectionActivityQueryResponse,
  TQueryKey extends QueryKey = CollectionActivityQueryKey,
>(
  options: {
    query?: Partial<
      QueryObserverOptions<
        CollectionActivityQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey = resolvedOptions?.queryKey ?? collectionActivityQueryKey()

  const query = useQuery(
    {
      ...collectionActivityQueryOptions(config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey
  }

  query.queryKey = queryKey as TQueryKey

  return query
}
