/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CollectionActivityQueryResponse } from "../types/CollectionActivity"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios"
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query"
import { collectionActivity } from "../clients/collectionActivity"
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query"

export const collectionActivitySuspenseQueryKey = () =>
  [{ url: "/api/v1/collection/activity" }] as const

export type CollectionActivitySuspenseQueryKey = ReturnType<
  typeof collectionActivitySuspenseQueryKey
>

export function collectionActivitySuspenseQueryOptions(
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = collectionActivitySuspenseQueryKey()
  return queryOptions<
    CollectionActivityQueryResponse,
    ResponseErrorConfig<Error>,
    CollectionActivityQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return collectionActivity({ ...config, signal: config.signal ?? signal })
    },
  })
}

/**
 * @description Recent additions, scans and suggestions, newest first.
 * @summary Collection Activity
 * {@link /api/v1/collection/activity}
 */
export function useCollectionActivitySuspense<
  TData = CollectionActivityQueryResponse,
  TQueryKey extends QueryKey = CollectionActivitySuspenseQueryKey,
>(
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        CollectionActivityQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey =
    resolvedOptions?.queryKey ?? collectionActivitySuspenseQueryKey()

  const query = useSuspenseQuery(
    {
      ...collectionActivitySuspenseQueryOptions(config),
      ...resolvedOptions,
      queryKey,
    } as unknown as UseSuspenseQueryOptions,
    queryClient
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey
  }

  query.queryKey = queryKey as TQueryKey

  return query
}
