/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  CounterOfferMutationRequest,
  CounterOfferMutationResponse,
  CounterOfferPathParams,
  CounterOffer422,
} from "../types/CounterOffer"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios"
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query"
import { counterOffer } from "../clients/counterOffer"
import { mutationOptions, useMutation } from "@tanstack/react-query"

export const counterOfferMutationKey = () =>
  [{ url: "/api/v1/trades/offers/:offer_id/counter" }] as const

export type CounterOfferMutationKey = ReturnType<typeof counterOfferMutationKey>

export function counterOfferMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig<CounterOfferMutationRequest>> & {
    client?: Client
  } = {}
) {
  const mutationKey = counterOfferMutationKey()
  return mutationOptions<
    CounterOfferMutationResponse,
    ResponseErrorConfig<CounterOffer422>,
    {
      offer_id: CounterOfferPathParams["offer_id"]
      data: CounterOfferMutationRequest
    },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ offer_id, data }) => {
      return counterOffer(offer_id, data, config)
    },
  })
}

/**
 * @description Answer an offer with a different one, declining the original.
 * Only its recipient may, and the counter goes back to whoever sent it.
 * @summary Counter Offer
 * {@link /api/v1/trades/offers/:offer_id/counter}
 */
export function useCounterOffer<TContext>(
  options: {
    mutation?: UseMutationOptions<
      CounterOfferMutationResponse,
      ResponseErrorConfig<CounterOffer422>,
      {
        offer_id: CounterOfferPathParams["offer_id"]
        data: CounterOfferMutationRequest
      },
      TContext
    > & { client?: QueryClient }
    client?: Partial<RequestConfig<CounterOfferMutationRequest>> & {
      client?: Client
    }
  } = {}
) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation
  const mutationKey = mutationOptions.mutationKey ?? counterOfferMutationKey()

  const baseOptions = counterOfferMutationOptions(config) as UseMutationOptions<
    CounterOfferMutationResponse,
    ResponseErrorConfig<CounterOffer422>,
    {
      offer_id: CounterOfferPathParams["offer_id"]
      data: CounterOfferMutationRequest
    },
    TContext
  >

  return useMutation<
    CounterOfferMutationResponse,
    ResponseErrorConfig<CounterOffer422>,
    {
      offer_id: CounterOfferPathParams["offer_id"]
      data: CounterOfferMutationRequest
    },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient
  ) as UseMutationResult<
    CounterOfferMutationResponse,
    ResponseErrorConfig<CounterOffer422>,
    {
      offer_id: CounterOfferPathParams["offer_id"]
      data: CounterOfferMutationRequest
    },
    TContext
  >
}
