/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  CompareCardsQueryResponse,
  CompareCardsQueryParams,
  CompareCards422,
} from "../types/CompareCards"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios"
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query"
import { compareCards } from "../clients/compareCards"
import { queryOptions, useQuery } from "@tanstack/react-query"

export const compareCardsQueryKey = (params: CompareCardsQueryParams) =>
  [{ url: "/api/v1/catalog/compare" }, ...(params ? [params] : [])] as const

export type CompareCardsQueryKey = ReturnType<typeof compareCardsQueryKey>

export function compareCardsQueryOptions(
  params: CompareCardsQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = compareCardsQueryKey(params)
  return queryOptions<
    CompareCardsQueryResponse,
    ResponseErrorConfig<CompareCards422>,
    CompareCardsQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return compareCards(params, {
        ...config,
        signal: config.signal ?? signal,
      })
    },
  })
}

/**
 * @description What a model sees when the two card images are put side by side.
 * @summary Compare Cards
 * {@link /api/v1/catalog/compare}
 */
export function useCompareCards<
  TData = CompareCardsQueryResponse,
  TQueryData = CompareCardsQueryResponse,
  TQueryKey extends QueryKey = CompareCardsQueryKey,
>(
  params: CompareCardsQueryParams,
  options: {
    query?: Partial<
      QueryObserverOptions<
        CompareCardsQueryResponse,
        ResponseErrorConfig<CompareCards422>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey = resolvedOptions?.queryKey ?? compareCardsQueryKey(params)

  const query = useQuery(
    {
      ...compareCardsQueryOptions(params, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient
  ) as UseQueryResult<TData, ResponseErrorConfig<CompareCards422>> & {
    queryKey: TQueryKey
  }

  query.queryKey = queryKey as TQueryKey

  return query
}
