/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  CardMarketContextQueryResponse,
  CardMarketContextPathParams,
  CardMarketContext422,
} from "../types/CardMarketContext"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios"
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query"
import { cardMarketContext } from "../clients/cardMarketContext"
import { queryOptions, useQuery } from "@tanstack/react-query"

export const cardMarketContextQueryKey = (
  card_id: CardMarketContextPathParams["card_id"] | undefined
) =>
  [
    {
      url: "/api/v1/catalog/cards/:card_id/context",
      params: { card_id: card_id },
    },
  ] as const

export type CardMarketContextQueryKey = ReturnType<
  typeof cardMarketContextQueryKey
>

export function cardMarketContextQueryOptions(
  card_id: CardMarketContextPathParams["card_id"] | undefined,
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = cardMarketContextQueryKey(card_id)
  return queryOptions<
    CardMarketContextQueryResponse,
    ResponseErrorConfig<CardMarketContext422>,
    CardMarketContextQueryResponse,
    typeof queryKey
  >({
    enabled: !!card_id,
    queryKey,
    queryFn: async ({ signal }) => {
      return cardMarketContext(card_id!, {
        ...config,
        signal: config.signal ?? signal,
      })
    },
  })
}

/**
 * @summary Card Market Context
 * {@link /api/v1/catalog/cards/:card_id/context}
 */
export function useCardMarketContext<
  TData = CardMarketContextQueryResponse,
  TQueryData = CardMarketContextQueryResponse,
  TQueryKey extends QueryKey = CardMarketContextQueryKey,
>(
  card_id: CardMarketContextPathParams["card_id"] | undefined,
  options: {
    query?: Partial<
      QueryObserverOptions<
        CardMarketContextQueryResponse,
        ResponseErrorConfig<CardMarketContext422>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey =
    resolvedOptions?.queryKey ?? cardMarketContextQueryKey(card_id)

  const query = useQuery(
    {
      ...cardMarketContextQueryOptions(card_id, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient
  ) as UseQueryResult<TData, ResponseErrorConfig<CardMarketContext422>> & {
    queryKey: TQueryKey
  }

  query.queryKey = queryKey as TQueryKey

  return query
}
