/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  CardMarketContextQueryResponse,
  CardMarketContextPathParams,
  CardMarketContext422,
} from "../types/CardMarketContext"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios"
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query"
import { cardMarketContext } from "../clients/cardMarketContext"
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query"

export const cardMarketContextSuspenseQueryKey = (
  card_id: CardMarketContextPathParams["card_id"] | undefined
) =>
  [
    {
      url: "/api/v1/catalog/cards/:card_id/context",
      params: { card_id: card_id },
    },
  ] as const

export type CardMarketContextSuspenseQueryKey = ReturnType<
  typeof cardMarketContextSuspenseQueryKey
>

export function cardMarketContextSuspenseQueryOptions(
  card_id: CardMarketContextPathParams["card_id"],
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = cardMarketContextSuspenseQueryKey(card_id)
  return queryOptions<
    CardMarketContextQueryResponse,
    ResponseErrorConfig<CardMarketContext422>,
    CardMarketContextQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return cardMarketContext(card_id, {
        ...config,
        signal: config.signal ?? signal,
      })
    },
  })
}

/**
 * @summary Card Market Context
 * {@link /api/v1/catalog/cards/:card_id/context}
 */
export function useCardMarketContextSuspense<
  TData = CardMarketContextQueryResponse,
  TQueryKey extends QueryKey = CardMarketContextSuspenseQueryKey,
>(
  card_id: CardMarketContextPathParams["card_id"],
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        CardMarketContextQueryResponse,
        ResponseErrorConfig<CardMarketContext422>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey =
    resolvedOptions?.queryKey ?? cardMarketContextSuspenseQueryKey(card_id)

  const query = useSuspenseQuery(
    {
      ...cardMarketContextSuspenseQueryOptions(card_id, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as UseSuspenseQueryOptions,
    queryClient
  ) as UseSuspenseQueryResult<
    TData,
    ResponseErrorConfig<CardMarketContext422>
  > & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}
