/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  ExportCollectionQueryResponse,
  ExportCollectionQueryParams,
  ExportCollection422,
} from "../types/ExportCollection"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios"
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query"
import { exportCollection } from "../clients/exportCollection"
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query"

export const exportCollectionSuspenseQueryKey = (
  params?: ExportCollectionQueryParams
) =>
  [{ url: "/api/v1/collection/export" }, ...(params ? [params] : [])] as const

export type ExportCollectionSuspenseQueryKey = ReturnType<
  typeof exportCollectionSuspenseQueryKey
>

export function exportCollectionSuspenseQueryOptions(
  params?: ExportCollectionQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = exportCollectionSuspenseQueryKey(params)
  return queryOptions<
    ExportCollectionQueryResponse,
    ResponseErrorConfig<ExportCollection422>,
    ExportCollectionQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return exportCollection(params, {
        ...config,
        signal: config.signal ?? signal,
      })
    },
  })
}

/**
 * @description The whole collection as a file, unpaginated: an export that stops at 200
 * rows is not an export.
 * @summary Export Collection
 * {@link /api/v1/collection/export}
 */
export function useExportCollectionSuspense<
  TData = ExportCollectionQueryResponse,
  TQueryKey extends QueryKey = ExportCollectionSuspenseQueryKey,
>(
  params?: ExportCollectionQueryParams,
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        ExportCollectionQueryResponse,
        ResponseErrorConfig<ExportCollection422>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey =
    resolvedOptions?.queryKey ?? exportCollectionSuspenseQueryKey(params)

  const query = useSuspenseQuery(
    {
      ...exportCollectionSuspenseQueryOptions(params, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as UseSuspenseQueryOptions,
    queryClient
  ) as UseSuspenseQueryResult<
    TData,
    ResponseErrorConfig<ExportCollection422>
  > & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}
