/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  ExportCollectionQueryResponse,
  ExportCollectionQueryParams,
  ExportCollection422,
} from "../types/ExportCollection"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios"
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query"
import { exportCollection } from "../clients/exportCollection"
import { queryOptions, useQuery } from "@tanstack/react-query"

export const exportCollectionQueryKey = (
  params?: ExportCollectionQueryParams
) =>
  [{ url: "/api/v1/collection/export" }, ...(params ? [params] : [])] as const

export type ExportCollectionQueryKey = ReturnType<
  typeof exportCollectionQueryKey
>

export function exportCollectionQueryOptions(
  params?: ExportCollectionQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = exportCollectionQueryKey(params)
  return queryOptions<
    ExportCollectionQueryResponse,
    ResponseErrorConfig<ExportCollection422>,
    ExportCollectionQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return exportCollection(params, {
        ...config,
        signal: config.signal ?? signal,
      })
    },
  })
}

/**
 * @description The whole collection as a file, unpaginated: an export that stops at 200
 * rows is not an export.
 * @summary Export Collection
 * {@link /api/v1/collection/export}
 */
export function useExportCollection<
  TData = ExportCollectionQueryResponse,
  TQueryData = ExportCollectionQueryResponse,
  TQueryKey extends QueryKey = ExportCollectionQueryKey,
>(
  params?: ExportCollectionQueryParams,
  options: {
    query?: Partial<
      QueryObserverOptions<
        ExportCollectionQueryResponse,
        ResponseErrorConfig<ExportCollection422>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey = resolvedOptions?.queryKey ?? exportCollectionQueryKey(params)

  const query = useQuery(
    {
      ...exportCollectionQueryOptions(params, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient
  ) as UseQueryResult<TData, ResponseErrorConfig<ExportCollection422>> & {
    queryKey: TQueryKey
  }

  query.queryKey = queryKey as TQueryKey

  return query
}
