/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  ForgetPreferenceMutationResponse,
  ForgetPreferencePathParams,
  ForgetPreference422,
} from "../types/ForgetPreference"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios"
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query"
import { forgetPreference } from "../clients/forgetPreference"
import { mutationOptions, useMutation } from "@tanstack/react-query"

export const forgetPreferenceMutationKey = () =>
  [{ url: "/api/v1/preferences/:key" }] as const

export type ForgetPreferenceMutationKey = ReturnType<
  typeof forgetPreferenceMutationKey
>

export function forgetPreferenceMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const mutationKey = forgetPreferenceMutationKey()
  return mutationOptions<
    ForgetPreferenceMutationResponse,
    ResponseErrorConfig<ForgetPreference422>,
    { key: ForgetPreferencePathParams["key"] },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ key }) => {
      return forgetPreference(key, config)
    },
  })
}

/**
 * @summary Forget Preference
 * {@link /api/v1/preferences/:key}
 */
export function useForgetPreference<TContext>(
  options: {
    mutation?: UseMutationOptions<
      ForgetPreferenceMutationResponse,
      ResponseErrorConfig<ForgetPreference422>,
      { key: ForgetPreferencePathParams["key"] },
      TContext
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {}
) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation
  const mutationKey =
    mutationOptions.mutationKey ?? forgetPreferenceMutationKey()

  const baseOptions = forgetPreferenceMutationOptions(
    config
  ) as UseMutationOptions<
    ForgetPreferenceMutationResponse,
    ResponseErrorConfig<ForgetPreference422>,
    { key: ForgetPreferencePathParams["key"] },
    TContext
  >

  return useMutation<
    ForgetPreferenceMutationResponse,
    ResponseErrorConfig<ForgetPreference422>,
    { key: ForgetPreferencePathParams["key"] },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient
  ) as UseMutationResult<
    ForgetPreferenceMutationResponse,
    ResponseErrorConfig<ForgetPreference422>,
    { key: ForgetPreferencePathParams["key"] },
    TContext
  >
}
