/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  GetScanImageQueryResponse,
  GetScanImagePathParams,
  GetScanImage422,
} from "../types/GetScanImage"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios"
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query"
import { getScanImage } from "../clients/getScanImage"
import { queryOptions, useQuery } from "@tanstack/react-query"

export const getScanImageQueryKey = (
  scan_id: GetScanImagePathParams["scan_id"] | undefined
) =>
  [
    { url: "/api/v1/scans/:scan_id/image", params: { scan_id: scan_id } },
  ] as const

export type GetScanImageQueryKey = ReturnType<typeof getScanImageQueryKey>

export function getScanImageQueryOptions(
  scan_id: GetScanImagePathParams["scan_id"] | undefined,
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = getScanImageQueryKey(scan_id)
  return queryOptions<
    GetScanImageQueryResponse,
    ResponseErrorConfig<GetScanImage422>,
    GetScanImageQueryResponse,
    typeof queryKey
  >({
    enabled: !!scan_id,
    queryKey,
    queryFn: async ({ signal }) => {
      return getScanImage(scan_id!, {
        ...config,
        signal: config.signal ?? signal,
      })
    },
  })
}

/**
 * @description Scan photos are private, so they are streamed through auth rather than served
 * as static files. Mounting the directory would leak every user's photos.
 * @summary Get Scan Image
 * {@link /api/v1/scans/:scan_id/image}
 */
export function useGetScanImage<
  TData = GetScanImageQueryResponse,
  TQueryData = GetScanImageQueryResponse,
  TQueryKey extends QueryKey = GetScanImageQueryKey,
>(
  scan_id: GetScanImagePathParams["scan_id"] | undefined,
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetScanImageQueryResponse,
        ResponseErrorConfig<GetScanImage422>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey = resolvedOptions?.queryKey ?? getScanImageQueryKey(scan_id)

  const query = useQuery(
    {
      ...getScanImageQueryOptions(scan_id, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient
  ) as UseQueryResult<TData, ResponseErrorConfig<GetScanImage422>> & {
    queryKey: TQueryKey
  }

  query.queryKey = queryKey as TQueryKey

  return query
}
