/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  GetCollectorQueryResponse,
  GetCollectorPathParams,
  GetCollector422,
} from "../types/GetCollector"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios"
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query"
import { getCollector } from "../clients/getCollector"
import { queryOptions, useQuery } from "@tanstack/react-query"

export const getCollectorQueryKey = (
  owner_id: GetCollectorPathParams["owner_id"] | undefined
) =>
  [
    {
      url: "/api/v1/trades/collectors/:owner_id",
      params: { owner_id: owner_id },
    },
  ] as const

export type GetCollectorQueryKey = ReturnType<typeof getCollectorQueryKey>

export function getCollectorQueryOptions(
  owner_id: GetCollectorPathParams["owner_id"] | undefined,
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = getCollectorQueryKey(owner_id)
  return queryOptions<
    GetCollectorQueryResponse,
    ResponseErrorConfig<GetCollector422>,
    GetCollectorQueryResponse,
    typeof queryKey
  >({
    enabled: !!owner_id,
    queryKey,
    queryFn: async ({ signal }) => {
      return getCollector(owner_id!, {
        ...config,
        signal: config.signal ?? signal,
      })
    },
  })
}

/**
 * @description One collector's public profile.
 * Counts, never money: what a collection is worth stays with whoever owns it.
 * Reading your own id returns the same shape with `is_self` set.
 * @summary Get Collector
 * {@link /api/v1/trades/collectors/:owner_id}
 */
export function useGetCollector<
  TData = GetCollectorQueryResponse,
  TQueryData = GetCollectorQueryResponse,
  TQueryKey extends QueryKey = GetCollectorQueryKey,
>(
  owner_id: GetCollectorPathParams["owner_id"] | undefined,
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetCollectorQueryResponse,
        ResponseErrorConfig<GetCollector422>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey = resolvedOptions?.queryKey ?? getCollectorQueryKey(owner_id)

  const query = useQuery(
    {
      ...getCollectorQueryOptions(owner_id, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient
  ) as UseQueryResult<TData, ResponseErrorConfig<GetCollector422>> & {
    queryKey: TQueryKey
  }

  query.queryKey = queryKey as TQueryKey

  return query
}
