/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  GetConversationQueryResponse,
  GetConversationPathParams,
  GetConversation422,
} from "../types/GetConversation"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios"
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query"
import { getConversation } from "../clients/getConversation"
import { queryOptions, useQuery } from "@tanstack/react-query"

export const getConversationQueryKey = (
  conversation_id: GetConversationPathParams["conversation_id"] | undefined
) =>
  [
    {
      url: "/api/v1/chat/:conversation_id",
      params: { conversation_id: conversation_id },
    },
  ] as const

export type GetConversationQueryKey = ReturnType<typeof getConversationQueryKey>

export function getConversationQueryOptions(
  conversation_id: GetConversationPathParams["conversation_id"] | undefined,
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = getConversationQueryKey(conversation_id)
  return queryOptions<
    GetConversationQueryResponse,
    ResponseErrorConfig<GetConversation422>,
    GetConversationQueryResponse,
    typeof queryKey
  >({
    enabled: !!conversation_id,
    queryKey,
    queryFn: async ({ signal }) => {
      return getConversation(conversation_id!, {
        ...config,
        signal: config.signal ?? signal,
      })
    },
  })
}

/**
 * @summary Get Conversation
 * {@link /api/v1/chat/:conversation_id}
 */
export function useGetConversation<
  TData = GetConversationQueryResponse,
  TQueryData = GetConversationQueryResponse,
  TQueryKey extends QueryKey = GetConversationQueryKey,
>(
  conversation_id: GetConversationPathParams["conversation_id"] | undefined,
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetConversationQueryResponse,
        ResponseErrorConfig<GetConversation422>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey =
    resolvedOptions?.queryKey ?? getConversationQueryKey(conversation_id)

  const query = useQuery(
    {
      ...getConversationQueryOptions(conversation_id, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient
  ) as UseQueryResult<TData, ResponseErrorConfig<GetConversation422>> & {
    queryKey: TQueryKey
  }

  query.queryKey = queryKey as TQueryKey

  return query
}
