/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  GetConversationQueryResponse,
  GetConversationPathParams,
  GetConversation422,
} from "../types/GetConversation"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios"
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query"
import { getConversation } from "../clients/getConversation"
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query"

export const getConversationSuspenseQueryKey = (
  conversation_id: GetConversationPathParams["conversation_id"] | undefined
) =>
  [
    {
      url: "/api/v1/chat/:conversation_id",
      params: { conversation_id: conversation_id },
    },
  ] as const

export type GetConversationSuspenseQueryKey = ReturnType<
  typeof getConversationSuspenseQueryKey
>

export function getConversationSuspenseQueryOptions(
  conversation_id: GetConversationPathParams["conversation_id"],
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = getConversationSuspenseQueryKey(conversation_id)
  return queryOptions<
    GetConversationQueryResponse,
    ResponseErrorConfig<GetConversation422>,
    GetConversationQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getConversation(conversation_id, {
        ...config,
        signal: config.signal ?? signal,
      })
    },
  })
}

/**
 * @summary Get Conversation
 * {@link /api/v1/chat/:conversation_id}
 */
export function useGetConversationSuspense<
  TData = GetConversationQueryResponse,
  TQueryKey extends QueryKey = GetConversationSuspenseQueryKey,
>(
  conversation_id: GetConversationPathParams["conversation_id"],
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetConversationQueryResponse,
        ResponseErrorConfig<GetConversation422>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey =
    resolvedOptions?.queryKey ??
    getConversationSuspenseQueryKey(conversation_id)

  const query = useSuspenseQuery(
    {
      ...getConversationSuspenseQueryOptions(conversation_id, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as UseSuspenseQueryOptions,
    queryClient
  ) as UseSuspenseQueryResult<
    TData,
    ResponseErrorConfig<GetConversation422>
  > & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}
