/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { GetShareLinkQueryResponse } from "../types/GetShareLink"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios"
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query"
import { getShareLink } from "../clients/getShareLink"
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query"

export const getShareLinkSuspenseQueryKey = () =>
  [{ url: "/api/v1/share" }] as const

export type GetShareLinkSuspenseQueryKey = ReturnType<
  typeof getShareLinkSuspenseQueryKey
>

export function getShareLinkSuspenseQueryOptions(
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = getShareLinkSuspenseQueryKey()
  return queryOptions<
    GetShareLinkQueryResponse,
    ResponseErrorConfig<Error>,
    GetShareLinkQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getShareLink({ ...config, signal: config.signal ?? signal })
    },
  })
}

/**
 * @summary Get Share Link
 * {@link /api/v1/share}
 */
export function useGetShareLinkSuspense<
  TData = GetShareLinkQueryResponse,
  TQueryKey extends QueryKey = GetShareLinkSuspenseQueryKey,
>(
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetShareLinkQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey = resolvedOptions?.queryKey ?? getShareLinkSuspenseQueryKey()

  const query = useSuspenseQuery(
    {
      ...getShareLinkSuspenseQueryOptions(config),
      ...resolvedOptions,
      queryKey,
    } as unknown as UseSuspenseQueryOptions,
    queryClient
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey
  }

  query.queryKey = queryKey as TQueryKey

  return query
}
