/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  GetItemQueryResponse,
  GetItemPathParams,
  GetItem422,
} from "../types/GetItem"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios"
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query"
import { getItem } from "../clients/getItem"
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query"

export const getItemSuspenseQueryKey = (
  item_id: GetItemPathParams["item_id"] | undefined
) =>
  [
    { url: "/api/v1/collection/:item_id", params: { item_id: item_id } },
  ] as const

export type GetItemSuspenseQueryKey = ReturnType<typeof getItemSuspenseQueryKey>

export function getItemSuspenseQueryOptions(
  item_id: GetItemPathParams["item_id"],
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = getItemSuspenseQueryKey(item_id)
  return queryOptions<
    GetItemQueryResponse,
    ResponseErrorConfig<GetItem422>,
    GetItemQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getItem(item_id, { ...config, signal: config.signal ?? signal })
    },
  })
}

/**
 * @summary Get Item
 * {@link /api/v1/collection/:item_id}
 */
export function useGetItemSuspense<
  TData = GetItemQueryResponse,
  TQueryKey extends QueryKey = GetItemSuspenseQueryKey,
>(
  item_id: GetItemPathParams["item_id"],
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetItemQueryResponse,
        ResponseErrorConfig<GetItem422>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey = resolvedOptions?.queryKey ?? getItemSuspenseQueryKey(item_id)

  const query = useSuspenseQuery(
    {
      ...getItemSuspenseQueryOptions(item_id, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as UseSuspenseQueryOptions,
    queryClient
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<GetItem422>> & {
    queryKey: TQueryKey
  }

  query.queryKey = queryKey as TQueryKey

  return query
}
