/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  GetCollectorQueryResponse,
  GetCollectorPathParams,
  GetCollector422,
} from "../types/GetCollector"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios"
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query"
import { getCollector } from "../clients/getCollector"
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query"

export const getCollectorSuspenseQueryKey = (
  owner_id: GetCollectorPathParams["owner_id"] | undefined
) =>
  [
    {
      url: "/api/v1/trades/collectors/:owner_id",
      params: { owner_id: owner_id },
    },
  ] as const

export type GetCollectorSuspenseQueryKey = ReturnType<
  typeof getCollectorSuspenseQueryKey
>

export function getCollectorSuspenseQueryOptions(
  owner_id: GetCollectorPathParams["owner_id"],
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = getCollectorSuspenseQueryKey(owner_id)
  return queryOptions<
    GetCollectorQueryResponse,
    ResponseErrorConfig<GetCollector422>,
    GetCollectorQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getCollector(owner_id, {
        ...config,
        signal: config.signal ?? signal,
      })
    },
  })
}

/**
 * @description One collector's public profile.
 * Counts, never money: what a collection is worth stays with whoever owns it.
 * Reading your own id returns the same shape with `is_self` set.
 * @summary Get Collector
 * {@link /api/v1/trades/collectors/:owner_id}
 */
export function useGetCollectorSuspense<
  TData = GetCollectorQueryResponse,
  TQueryKey extends QueryKey = GetCollectorSuspenseQueryKey,
>(
  owner_id: GetCollectorPathParams["owner_id"],
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetCollectorQueryResponse,
        ResponseErrorConfig<GetCollector422>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey =
    resolvedOptions?.queryKey ?? getCollectorSuspenseQueryKey(owner_id)

  const query = useSuspenseQuery(
    {
      ...getCollectorSuspenseQueryOptions(owner_id, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as UseSuspenseQueryOptions,
    queryClient
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<GetCollector422>> & {
    queryKey: TQueryKey
  }

  query.queryKey = queryKey as TQueryKey

  return query
}
