/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  GetItemQueryResponse,
  GetItemPathParams,
  GetItem422,
} from "../types/GetItem"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios"
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query"
import { getItem } from "../clients/getItem"
import { queryOptions, useQuery } from "@tanstack/react-query"

export const getItemQueryKey = (
  item_id: GetItemPathParams["item_id"] | undefined
) =>
  [
    { url: "/api/v1/collection/:item_id", params: { item_id: item_id } },
  ] as const

export type GetItemQueryKey = ReturnType<typeof getItemQueryKey>

export function getItemQueryOptions(
  item_id: GetItemPathParams["item_id"] | undefined,
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = getItemQueryKey(item_id)
  return queryOptions<
    GetItemQueryResponse,
    ResponseErrorConfig<GetItem422>,
    GetItemQueryResponse,
    typeof queryKey
  >({
    enabled: !!item_id,
    queryKey,
    queryFn: async ({ signal }) => {
      return getItem(item_id!, { ...config, signal: config.signal ?? signal })
    },
  })
}

/**
 * @summary Get Item
 * {@link /api/v1/collection/:item_id}
 */
export function useGetItem<
  TData = GetItemQueryResponse,
  TQueryData = GetItemQueryResponse,
  TQueryKey extends QueryKey = GetItemQueryKey,
>(
  item_id: GetItemPathParams["item_id"] | undefined,
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetItemQueryResponse,
        ResponseErrorConfig<GetItem422>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey = resolvedOptions?.queryKey ?? getItemQueryKey(item_id)

  const query = useQuery(
    {
      ...getItemQueryOptions(item_id, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient
  ) as UseQueryResult<TData, ResponseErrorConfig<GetItem422>> & {
    queryKey: TQueryKey
  }

  query.queryKey = queryKey as TQueryKey

  return query
}
