/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  GetCardQueryResponse,
  GetCardPathParams,
  GetCard422,
} from "../types/GetCard"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios"
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query"
import { getCard } from "../clients/getCard"
import { queryOptions, useQuery } from "@tanstack/react-query"

export const getCardQueryKey = (
  card_id: GetCardPathParams["card_id"] | undefined
) =>
  [
    { url: "/api/v1/catalog/cards/:card_id", params: { card_id: card_id } },
  ] as const

export type GetCardQueryKey = ReturnType<typeof getCardQueryKey>

export function getCardQueryOptions(
  card_id: GetCardPathParams["card_id"] | undefined,
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = getCardQueryKey(card_id)
  return queryOptions<
    GetCardQueryResponse,
    ResponseErrorConfig<GetCard422>,
    GetCardQueryResponse,
    typeof queryKey
  >({
    enabled: !!card_id,
    queryKey,
    queryFn: async ({ signal }) => {
      return getCard(card_id!, { ...config, signal: config.signal ?? signal })
    },
  })
}

/**
 * @summary Get Card
 * {@link /api/v1/catalog/cards/:card_id}
 */
export function useGetCard<
  TData = GetCardQueryResponse,
  TQueryData = GetCardQueryResponse,
  TQueryKey extends QueryKey = GetCardQueryKey,
>(
  card_id: GetCardPathParams["card_id"] | undefined,
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetCardQueryResponse,
        ResponseErrorConfig<GetCard422>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey = resolvedOptions?.queryKey ?? getCardQueryKey(card_id)

  const query = useQuery(
    {
      ...getCardQueryOptions(card_id, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient
  ) as UseQueryResult<TData, ResponseErrorConfig<GetCard422>> & {
    queryKey: TQueryKey
  }

  query.queryKey = queryKey as TQueryKey

  return query
}
