/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { GetShareLinkQueryResponse } from "../types/GetShareLink"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios"
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query"
import { getShareLink } from "../clients/getShareLink"
import { queryOptions, useQuery } from "@tanstack/react-query"

export const getShareLinkQueryKey = () => [{ url: "/api/v1/share" }] as const

export type GetShareLinkQueryKey = ReturnType<typeof getShareLinkQueryKey>

export function getShareLinkQueryOptions(
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = getShareLinkQueryKey()
  return queryOptions<
    GetShareLinkQueryResponse,
    ResponseErrorConfig<Error>,
    GetShareLinkQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getShareLink({ ...config, signal: config.signal ?? signal })
    },
  })
}

/**
 * @summary Get Share Link
 * {@link /api/v1/share}
 */
export function useGetShareLink<
  TData = GetShareLinkQueryResponse,
  TQueryData = GetShareLinkQueryResponse,
  TQueryKey extends QueryKey = GetShareLinkQueryKey,
>(
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetShareLinkQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey = resolvedOptions?.queryKey ?? getShareLinkQueryKey()

  const query = useQuery(
    {
      ...getShareLinkQueryOptions(config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey
  }

  query.queryKey = queryKey as TQueryKey

  return query
}
