/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  GetCardQueryResponse,
  GetCardPathParams,
  GetCard422,
} from "../types/GetCard"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios"
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query"
import { getCard } from "../clients/getCard"
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query"

export const getCardSuspenseQueryKey = (
  card_id: GetCardPathParams["card_id"] | undefined
) =>
  [
    { url: "/api/v1/catalog/cards/:card_id", params: { card_id: card_id } },
  ] as const

export type GetCardSuspenseQueryKey = ReturnType<typeof getCardSuspenseQueryKey>

export function getCardSuspenseQueryOptions(
  card_id: GetCardPathParams["card_id"],
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = getCardSuspenseQueryKey(card_id)
  return queryOptions<
    GetCardQueryResponse,
    ResponseErrorConfig<GetCard422>,
    GetCardQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getCard(card_id, { ...config, signal: config.signal ?? signal })
    },
  })
}

/**
 * @summary Get Card
 * {@link /api/v1/catalog/cards/:card_id}
 */
export function useGetCardSuspense<
  TData = GetCardQueryResponse,
  TQueryKey extends QueryKey = GetCardSuspenseQueryKey,
>(
  card_id: GetCardPathParams["card_id"],
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetCardQueryResponse,
        ResponseErrorConfig<GetCard422>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey = resolvedOptions?.queryKey ?? getCardSuspenseQueryKey(card_id)

  const query = useSuspenseQuery(
    {
      ...getCardSuspenseQueryOptions(card_id, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as UseSuspenseQueryOptions,
    queryClient
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<GetCard422>> & {
    queryKey: TQueryKey
  }

  query.queryKey = queryKey as TQueryKey

  return query
}
