/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  GetScanImageQueryResponse,
  GetScanImagePathParams,
  GetScanImage422,
} from "../types/GetScanImage"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios"
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query"
import { getScanImage } from "../clients/getScanImage"
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query"

export const getScanImageSuspenseQueryKey = (
  scan_id: GetScanImagePathParams["scan_id"] | undefined
) =>
  [
    { url: "/api/v1/scans/:scan_id/image", params: { scan_id: scan_id } },
  ] as const

export type GetScanImageSuspenseQueryKey = ReturnType<
  typeof getScanImageSuspenseQueryKey
>

export function getScanImageSuspenseQueryOptions(
  scan_id: GetScanImagePathParams["scan_id"],
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = getScanImageSuspenseQueryKey(scan_id)
  return queryOptions<
    GetScanImageQueryResponse,
    ResponseErrorConfig<GetScanImage422>,
    GetScanImageQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getScanImage(scan_id, {
        ...config,
        signal: config.signal ?? signal,
      })
    },
  })
}

/**
 * @description Scan photos are private, so they are streamed through auth rather than served
 * as static files. Mounting the directory would leak every user's photos.
 * @summary Get Scan Image
 * {@link /api/v1/scans/:scan_id/image}
 */
export function useGetScanImageSuspense<
  TData = GetScanImageQueryResponse,
  TQueryKey extends QueryKey = GetScanImageSuspenseQueryKey,
>(
  scan_id: GetScanImagePathParams["scan_id"],
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetScanImageQueryResponse,
        ResponseErrorConfig<GetScanImage422>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey =
    resolvedOptions?.queryKey ?? getScanImageSuspenseQueryKey(scan_id)

  const query = useSuspenseQuery(
    {
      ...getScanImageSuspenseQueryOptions(scan_id, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as UseSuspenseQueryOptions,
    queryClient
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<GetScanImage422>> & {
    queryKey: TQueryKey
  }

  query.queryKey = queryKey as TQueryKey

  return query
}
