/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  ListThreadsQueryResponse,
  ListThreadsQueryParams,
  ListThreads422,
} from "../types/ListThreads"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios"
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query"
import { listThreads } from "../clients/listThreads"
import { queryOptions, useQuery } from "@tanstack/react-query"

export const listThreadsQueryKey = (params?: ListThreadsQueryParams) =>
  [{ url: "/api/v1/messages" }, ...(params ? [params] : [])] as const

export type ListThreadsQueryKey = ReturnType<typeof listThreadsQueryKey>

export function listThreadsQueryOptions(
  params?: ListThreadsQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = listThreadsQueryKey(params)
  return queryOptions<
    ListThreadsQueryResponse,
    ResponseErrorConfig<ListThreads422>,
    ListThreadsQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return listThreads(params, {
        ...config,
        signal: config.signal ?? signal,
      })
    },
  })
}

/**
 * @description Conversations the reader is in, most recently spoken in first.
 * @summary List Threads
 * {@link /api/v1/messages}
 */
export function useListThreads<
  TData = ListThreadsQueryResponse,
  TQueryData = ListThreadsQueryResponse,
  TQueryKey extends QueryKey = ListThreadsQueryKey,
>(
  params?: ListThreadsQueryParams,
  options: {
    query?: Partial<
      QueryObserverOptions<
        ListThreadsQueryResponse,
        ResponseErrorConfig<ListThreads422>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey = resolvedOptions?.queryKey ?? listThreadsQueryKey(params)

  const query = useQuery(
    {
      ...listThreadsQueryOptions(params, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient
  ) as UseQueryResult<TData, ResponseErrorConfig<ListThreads422>> & {
    queryKey: TQueryKey
  }

  query.queryKey = queryKey as TQueryKey

  return query
}
