/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  ListCollectionQueryResponse,
  ListCollectionQueryParams,
  ListCollection422,
} from "../types/ListCollection"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios"
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query"
import { listCollection } from "../clients/listCollection"
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query"

export const listCollectionSuspenseQueryKey = (
  params?: ListCollectionQueryParams
) => [{ url: "/api/v1/collection" }, ...(params ? [params] : [])] as const

export type ListCollectionSuspenseQueryKey = ReturnType<
  typeof listCollectionSuspenseQueryKey
>

export function listCollectionSuspenseQueryOptions(
  params?: ListCollectionQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = listCollectionSuspenseQueryKey(params)
  return queryOptions<
    ListCollectionQueryResponse,
    ResponseErrorConfig<ListCollection422>,
    ListCollectionQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return listCollection(params, {
        ...config,
        signal: config.signal ?? signal,
      })
    },
  })
}

/**
 * @summary List Collection
 * {@link /api/v1/collection}
 */
export function useListCollectionSuspense<
  TData = ListCollectionQueryResponse,
  TQueryKey extends QueryKey = ListCollectionSuspenseQueryKey,
>(
  params?: ListCollectionQueryParams,
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        ListCollectionQueryResponse,
        ResponseErrorConfig<ListCollection422>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey =
    resolvedOptions?.queryKey ?? listCollectionSuspenseQueryKey(params)

  const query = useSuspenseQuery(
    {
      ...listCollectionSuspenseQueryOptions(params, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as UseSuspenseQueryOptions,
    queryClient
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<ListCollection422>> & {
    queryKey: TQueryKey
  }

  query.queryKey = queryKey as TQueryKey

  return query
}
