/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  ListCollectorsQueryResponse,
  ListCollectorsQueryParams,
  ListCollectors422,
} from "../types/ListCollectors"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios"
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query"
import { listCollectors } from "../clients/listCollectors"
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query"

export const listCollectorsSuspenseQueryKey = (
  params?: ListCollectorsQueryParams
) =>
  [{ url: "/api/v1/trades/collectors" }, ...(params ? [params] : [])] as const

export type ListCollectorsSuspenseQueryKey = ReturnType<
  typeof listCollectorsSuspenseQueryKey
>

export function listCollectorsSuspenseQueryOptions(
  params?: ListCollectorsQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = listCollectorsSuspenseQueryKey(params)
  return queryOptions<
    ListCollectorsQueryResponse,
    ResponseErrorConfig<ListCollectors422>,
    ListCollectorsQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return listCollectors(params, {
        ...config,
        signal: config.signal ?? signal,
      })
    },
  })
}

/**
 * @description Collectors with cards free to trade, and how they line up with the reader.
 * A collector appears whether or not a swap already works out. What is shown
 * about them is only what could move: how much is spare, and how much of it
 * either side wants.
 * @summary List Collectors
 * {@link /api/v1/trades/collectors}
 */
export function useListCollectorsSuspense<
  TData = ListCollectorsQueryResponse,
  TQueryKey extends QueryKey = ListCollectorsSuspenseQueryKey,
>(
  params?: ListCollectorsQueryParams,
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        ListCollectorsQueryResponse,
        ResponseErrorConfig<ListCollectors422>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey =
    resolvedOptions?.queryKey ?? listCollectorsSuspenseQueryKey(params)

  const query = useSuspenseQuery(
    {
      ...listCollectorsSuspenseQueryOptions(params, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as UseSuspenseQueryOptions,
    queryClient
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<ListCollectors422>> & {
    queryKey: TQueryKey
  }

  query.queryKey = queryKey as TQueryKey

  return query
}
