/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  ListSparesQueryResponse,
  ListSparesPathParams,
  ListSparesQueryParams,
  ListSpares422,
} from "../types/ListSpares"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios"
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query"
import { listSpares } from "../clients/listSpares"
import { queryOptions, useQuery } from "@tanstack/react-query"

export const listSparesQueryKey = (
  owner_id: ListSparesPathParams["owner_id"] | undefined,
  params?: ListSparesQueryParams
) =>
  [
    {
      url: "/api/v1/trades/collectors/:owner_id/spares",
      params: { owner_id: owner_id },
    },
    ...(params ? [params] : []),
  ] as const

export type ListSparesQueryKey = ReturnType<typeof listSparesQueryKey>

export function listSparesQueryOptions(
  owner_id: ListSparesPathParams["owner_id"] | undefined,
  params?: ListSparesQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = listSparesQueryKey(owner_id, params)
  return queryOptions<
    ListSparesQueryResponse,
    ResponseErrorConfig<ListSpares422>,
    ListSparesQueryResponse,
    typeof queryKey
  >({
    enabled: !!owner_id,
    queryKey,
    queryFn: async ({ signal }) => {
      return listSpares(owner_id!, params, {
        ...config,
        signal: config.signal ?? signal,
      })
    },
  })
}

/**
 * @description One collector's spare cards, with the reader's wants marked.
 * Pass the reader's own id to browse what they have free to offer.
 * @summary List Spares
 * {@link /api/v1/trades/collectors/:owner_id/spares}
 */
export function useListSpares<
  TData = ListSparesQueryResponse,
  TQueryData = ListSparesQueryResponse,
  TQueryKey extends QueryKey = ListSparesQueryKey,
>(
  owner_id: ListSparesPathParams["owner_id"] | undefined,
  params?: ListSparesQueryParams,
  options: {
    query?: Partial<
      QueryObserverOptions<
        ListSparesQueryResponse,
        ResponseErrorConfig<ListSpares422>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey =
    resolvedOptions?.queryKey ?? listSparesQueryKey(owner_id, params)

  const query = useQuery(
    {
      ...listSparesQueryOptions(owner_id, params, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient
  ) as UseQueryResult<TData, ResponseErrorConfig<ListSpares422>> & {
    queryKey: TQueryKey
  }

  query.queryKey = queryKey as TQueryKey

  return query
}
