/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ListPreferencesQueryResponse } from "../types/ListPreferences"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios"
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query"
import { listPreferences } from "../clients/listPreferences"
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query"

export const listPreferencesSuspenseQueryKey = () =>
  [{ url: "/api/v1/preferences" }] as const

export type ListPreferencesSuspenseQueryKey = ReturnType<
  typeof listPreferencesSuspenseQueryKey
>

export function listPreferencesSuspenseQueryOptions(
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = listPreferencesSuspenseQueryKey()
  return queryOptions<
    ListPreferencesQueryResponse,
    ResponseErrorConfig<Error>,
    ListPreferencesQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return listPreferences({ ...config, signal: config.signal ?? signal })
    },
  })
}

/**
 * @summary List Preferences
 * {@link /api/v1/preferences}
 */
export function useListPreferencesSuspense<
  TData = ListPreferencesQueryResponse,
  TQueryKey extends QueryKey = ListPreferencesSuspenseQueryKey,
>(
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        ListPreferencesQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey =
    resolvedOptions?.queryKey ?? listPreferencesSuspenseQueryKey()

  const query = useSuspenseQuery(
    {
      ...listPreferencesSuspenseQueryOptions(config),
      ...resolvedOptions,
      queryKey,
    } as unknown as UseSuspenseQueryOptions,
    queryClient
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey
  }

  query.queryKey = queryKey as TQueryKey

  return query
}
