/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ListWishlistQueryResponse } from "../types/ListWishlist"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios"
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query"
import { listWishlist } from "../clients/listWishlist"
import { queryOptions, useQuery } from "@tanstack/react-query"

export const listWishlistQueryKey = () => [{ url: "/api/v1/wishlist" }] as const

export type ListWishlistQueryKey = ReturnType<typeof listWishlistQueryKey>

export function listWishlistQueryOptions(
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = listWishlistQueryKey()
  return queryOptions<
    ListWishlistQueryResponse,
    ResponseErrorConfig<Error>,
    ListWishlistQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return listWishlist({ ...config, signal: config.signal ?? signal })
    },
  })
}

/**
 * @summary List Wishlist
 * {@link /api/v1/wishlist}
 */
export function useListWishlist<
  TData = ListWishlistQueryResponse,
  TQueryData = ListWishlistQueryResponse,
  TQueryKey extends QueryKey = ListWishlistQueryKey,
>(
  options: {
    query?: Partial<
      QueryObserverOptions<
        ListWishlistQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey = resolvedOptions?.queryKey ?? listWishlistQueryKey()

  const query = useQuery(
    {
      ...listWishlistQueryOptions(config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey
  }

  query.queryKey = queryKey as TQueryKey

  return query
}
