/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ListConversationsQueryResponse } from "../types/ListConversations"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios"
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query"
import { listConversations } from "../clients/listConversations"
import { queryOptions, useQuery } from "@tanstack/react-query"

export const listConversationsQueryKey = () =>
  [{ url: "/api/v1/chat" }] as const

export type ListConversationsQueryKey = ReturnType<
  typeof listConversationsQueryKey
>

export function listConversationsQueryOptions(
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = listConversationsQueryKey()
  return queryOptions<
    ListConversationsQueryResponse,
    ResponseErrorConfig<Error>,
    ListConversationsQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return listConversations({ ...config, signal: config.signal ?? signal })
    },
  })
}

/**
 * @summary List Conversations
 * {@link /api/v1/chat}
 */
export function useListConversations<
  TData = ListConversationsQueryResponse,
  TQueryData = ListConversationsQueryResponse,
  TQueryKey extends QueryKey = ListConversationsQueryKey,
>(
  options: {
    query?: Partial<
      QueryObserverOptions<
        ListConversationsQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey = resolvedOptions?.queryKey ?? listConversationsQueryKey()

  const query = useQuery(
    {
      ...listConversationsQueryOptions(config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey
  }

  query.queryKey = queryKey as TQueryKey

  return query
}
