/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ListPreferencesQueryResponse } from "../types/ListPreferences"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios"
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query"
import { listPreferences } from "../clients/listPreferences"
import { queryOptions, useQuery } from "@tanstack/react-query"

export const listPreferencesQueryKey = () =>
  [{ url: "/api/v1/preferences" }] as const

export type ListPreferencesQueryKey = ReturnType<typeof listPreferencesQueryKey>

export function listPreferencesQueryOptions(
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = listPreferencesQueryKey()
  return queryOptions<
    ListPreferencesQueryResponse,
    ResponseErrorConfig<Error>,
    ListPreferencesQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return listPreferences({ ...config, signal: config.signal ?? signal })
    },
  })
}

/**
 * @summary List Preferences
 * {@link /api/v1/preferences}
 */
export function useListPreferences<
  TData = ListPreferencesQueryResponse,
  TQueryData = ListPreferencesQueryResponse,
  TQueryKey extends QueryKey = ListPreferencesQueryKey,
>(
  options: {
    query?: Partial<
      QueryObserverOptions<
        ListPreferencesQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey = resolvedOptions?.queryKey ?? listPreferencesQueryKey()

  const query = useQuery(
    {
      ...listPreferencesQueryOptions(config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey
  }

  query.queryKey = queryKey as TQueryKey

  return query
}
