/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  ListListingsQueryResponse,
  ListListingsQueryParams,
  ListListings422,
} from "../types/ListListings"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios"
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query"
import { listListings } from "../clients/listListings"
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query"

export const listListingsSuspenseQueryKey = (
  params?: ListListingsQueryParams
) => [{ url: "/api/v1/trades/listings" }, ...(params ? [params] : [])] as const

export type ListListingsSuspenseQueryKey = ReturnType<
  typeof listListingsSuspenseQueryKey
>

export function listListingsSuspenseQueryOptions(
  params?: ListListingsQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = listListingsSuspenseQueryKey(params)
  return queryOptions<
    ListListingsQueryResponse,
    ResponseErrorConfig<ListListings422>,
    ListListingsQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return listListings(params, {
        ...config,
        signal: config.signal ?? signal,
      })
    },
  })
}

/**
 * @description The open board: swaps published to whoever can fill them.
 * Unlike an offer, a listing is addressed to nobody and every collector reads
 * the same one. What changes per reader is only whether they can take it.
 * @summary List Listings
 * {@link /api/v1/trades/listings}
 */
export function useListListingsSuspense<
  TData = ListListingsQueryResponse,
  TQueryKey extends QueryKey = ListListingsSuspenseQueryKey,
>(
  params?: ListListingsQueryParams,
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        ListListingsQueryResponse,
        ResponseErrorConfig<ListListings422>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey =
    resolvedOptions?.queryKey ?? listListingsSuspenseQueryKey(params)

  const query = useSuspenseQuery(
    {
      ...listListingsSuspenseQueryOptions(params, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as UseSuspenseQueryOptions,
    queryClient
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<ListListings422>> & {
    queryKey: TQueryKey
  }

  query.queryKey = queryKey as TQueryKey

  return query
}
