/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  ListCollectorsQueryResponse,
  ListCollectorsQueryParams,
  ListCollectors422,
} from "../types/ListCollectors"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios"
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query"
import { listCollectors } from "../clients/listCollectors"
import { queryOptions, useQuery } from "@tanstack/react-query"

export const listCollectorsQueryKey = (params?: ListCollectorsQueryParams) =>
  [{ url: "/api/v1/trades/collectors" }, ...(params ? [params] : [])] as const

export type ListCollectorsQueryKey = ReturnType<typeof listCollectorsQueryKey>

export function listCollectorsQueryOptions(
  params?: ListCollectorsQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = listCollectorsQueryKey(params)
  return queryOptions<
    ListCollectorsQueryResponse,
    ResponseErrorConfig<ListCollectors422>,
    ListCollectorsQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return listCollectors(params, {
        ...config,
        signal: config.signal ?? signal,
      })
    },
  })
}

/**
 * @description Collectors with cards free to trade, and how they line up with the reader.
 * A collector appears whether or not a swap already works out. What is shown
 * about them is only what could move: how much is spare, and how much of it
 * either side wants.
 * @summary List Collectors
 * {@link /api/v1/trades/collectors}
 */
export function useListCollectors<
  TData = ListCollectorsQueryResponse,
  TQueryData = ListCollectorsQueryResponse,
  TQueryKey extends QueryKey = ListCollectorsQueryKey,
>(
  params?: ListCollectorsQueryParams,
  options: {
    query?: Partial<
      QueryObserverOptions<
        ListCollectorsQueryResponse,
        ResponseErrorConfig<ListCollectors422>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey = resolvedOptions?.queryKey ?? listCollectorsQueryKey(params)

  const query = useQuery(
    {
      ...listCollectorsQueryOptions(params, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient
  ) as UseQueryResult<TData, ResponseErrorConfig<ListCollectors422>> & {
    queryKey: TQueryKey
  }

  query.queryKey = queryKey as TQueryKey

  return query
}
