/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  ListTradesQueryResponse,
  ListTradesQueryParams,
  ListTrades422,
} from "../types/ListTrades"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios"
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query"
import { listTrades } from "../clients/listTrades"
import { queryOptions, useQuery } from "@tanstack/react-query"

export const listTradesQueryKey = (params?: ListTradesQueryParams) =>
  [{ url: "/api/v1/trades" }, ...(params ? [params] : [])] as const

export type ListTradesQueryKey = ReturnType<typeof listTradesQueryKey>

export function listTradesQueryOptions(
  params?: ListTradesQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = listTradesQueryKey(params)
  return queryOptions<
    ListTradesQueryResponse,
    ResponseErrorConfig<ListTrades422>,
    ListTradesQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return listTrades(params, { ...config, signal: config.signal ?? signal })
    },
  })
}

/**
 * @description Collectors who want a spare card and hold a wanted one.
 * A match is a possibility, not an agreement: nothing here moves a card. The
 * cards named are only the two-way overlap, so what else a counterparty owns
 * stays theirs.
 * @summary List Trades
 * {@link /api/v1/trades}
 */
export function useListTrades<
  TData = ListTradesQueryResponse,
  TQueryData = ListTradesQueryResponse,
  TQueryKey extends QueryKey = ListTradesQueryKey,
>(
  params?: ListTradesQueryParams,
  options: {
    query?: Partial<
      QueryObserverOptions<
        ListTradesQueryResponse,
        ResponseErrorConfig<ListTrades422>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey = resolvedOptions?.queryKey ?? listTradesQueryKey(params)

  const query = useQuery(
    {
      ...listTradesQueryOptions(params, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient
  ) as UseQueryResult<TData, ResponseErrorConfig<ListTrades422>> & {
    queryKey: TQueryKey
  }

  query.queryKey = queryKey as TQueryKey

  return query
}
