/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  ListOffersQueryResponse,
  ListOffersQueryParams,
  ListOffers422,
} from "../types/ListOffers"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios"
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query"
import { listOffers } from "../clients/listOffers"
import { queryOptions, useQuery } from "@tanstack/react-query"

export const listOffersQueryKey = (params?: ListOffersQueryParams) =>
  [{ url: "/api/v1/trades/offers" }, ...(params ? [params] : [])] as const

export type ListOffersQueryKey = ReturnType<typeof listOffersQueryKey>

export function listOffersQueryOptions(
  params?: ListOffersQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = listOffersQueryKey(params)
  return queryOptions<
    ListOffersQueryResponse,
    ResponseErrorConfig<ListOffers422>,
    ListOffersQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return listOffers(params, { ...config, signal: config.signal ?? signal })
    },
  })
}

/**
 * @description Offers the reader is party to, sent and received, newest first.
 * @summary List Offers
 * {@link /api/v1/trades/offers}
 */
export function useListOffers<
  TData = ListOffersQueryResponse,
  TQueryData = ListOffersQueryResponse,
  TQueryKey extends QueryKey = ListOffersQueryKey,
>(
  params?: ListOffersQueryParams,
  options: {
    query?: Partial<
      QueryObserverOptions<
        ListOffersQueryResponse,
        ResponseErrorConfig<ListOffers422>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey = resolvedOptions?.queryKey ?? listOffersQueryKey(params)

  const query = useQuery(
    {
      ...listOffersQueryOptions(params, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient
  ) as UseQueryResult<TData, ResponseErrorConfig<ListOffers422>> & {
    queryKey: TQueryKey
  }

  query.queryKey = queryKey as TQueryKey

  return query
}
