/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  ListThreadMessagesQueryResponse,
  ListThreadMessagesPathParams,
  ListThreadMessagesQueryParams,
  ListThreadMessages422,
} from "../types/ListThreadMessages"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios"
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query"
import { listThreadMessages } from "../clients/listThreadMessages"
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query"

export const listThreadMessagesSuspenseQueryKey = (
  thread_id: ListThreadMessagesPathParams["thread_id"] | undefined,
  params?: ListThreadMessagesQueryParams
) =>
  [
    {
      url: "/api/v1/messages/:thread_id/messages",
      params: { thread_id: thread_id },
    },
    ...(params ? [params] : []),
  ] as const

export type ListThreadMessagesSuspenseQueryKey = ReturnType<
  typeof listThreadMessagesSuspenseQueryKey
>

export function listThreadMessagesSuspenseQueryOptions(
  thread_id: ListThreadMessagesPathParams["thread_id"],
  params?: ListThreadMessagesQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = listThreadMessagesSuspenseQueryKey(thread_id, params)
  return queryOptions<
    ListThreadMessagesQueryResponse,
    ResponseErrorConfig<ListThreadMessages422>,
    ListThreadMessagesQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return listThreadMessages(thread_id, params, {
        ...config,
        signal: config.signal ?? signal,
      })
    },
  })
}

/**
 * @description What was said, newest page first. Only the two participants may read it.
 * @summary List Thread Messages
 * {@link /api/v1/messages/:thread_id/messages}
 */
export function useListThreadMessagesSuspense<
  TData = ListThreadMessagesQueryResponse,
  TQueryKey extends QueryKey = ListThreadMessagesSuspenseQueryKey,
>(
  thread_id: ListThreadMessagesPathParams["thread_id"],
  params?: ListThreadMessagesQueryParams,
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        ListThreadMessagesQueryResponse,
        ResponseErrorConfig<ListThreadMessages422>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey =
    resolvedOptions?.queryKey ??
    listThreadMessagesSuspenseQueryKey(thread_id, params)

  const query = useSuspenseQuery(
    {
      ...listThreadMessagesSuspenseQueryOptions(thread_id, params, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as UseSuspenseQueryOptions,
    queryClient
  ) as UseSuspenseQueryResult<
    TData,
    ResponseErrorConfig<ListThreadMessages422>
  > & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}
