/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  ListCollectionQueryResponse,
  ListCollectionQueryParams,
  ListCollection422,
} from "../types/ListCollection"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios"
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query"
import { listCollection } from "../clients/listCollection"
import { queryOptions, useQuery } from "@tanstack/react-query"

export const listCollectionQueryKey = (params?: ListCollectionQueryParams) =>
  [{ url: "/api/v1/collection" }, ...(params ? [params] : [])] as const

export type ListCollectionQueryKey = ReturnType<typeof listCollectionQueryKey>

export function listCollectionQueryOptions(
  params?: ListCollectionQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = listCollectionQueryKey(params)
  return queryOptions<
    ListCollectionQueryResponse,
    ResponseErrorConfig<ListCollection422>,
    ListCollectionQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return listCollection(params, {
        ...config,
        signal: config.signal ?? signal,
      })
    },
  })
}

/**
 * @summary List Collection
 * {@link /api/v1/collection}
 */
export function useListCollection<
  TData = ListCollectionQueryResponse,
  TQueryData = ListCollectionQueryResponse,
  TQueryKey extends QueryKey = ListCollectionQueryKey,
>(
  params?: ListCollectionQueryParams,
  options: {
    query?: Partial<
      QueryObserverOptions<
        ListCollectionQueryResponse,
        ResponseErrorConfig<ListCollection422>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey = resolvedOptions?.queryKey ?? listCollectionQueryKey(params)

  const query = useQuery(
    {
      ...listCollectionQueryOptions(params, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient
  ) as UseQueryResult<TData, ResponseErrorConfig<ListCollection422>> & {
    queryKey: TQueryKey
  }

  query.queryKey = queryKey as TQueryKey

  return query
}
