/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  ListGapsQueryResponse,
  ListGapsQueryParams,
  ListGaps422,
} from "../types/ListGaps"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios"
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query"
import { listGaps } from "../clients/listGaps"
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query"

export const listGapsSuspenseQueryKey = (params?: ListGapsQueryParams) =>
  [{ url: "/api/v1/gaps" }, ...(params ? [params] : [])] as const

export type ListGapsSuspenseQueryKey = ReturnType<
  typeof listGapsSuspenseQueryKey
>

export function listGapsSuspenseQueryOptions(
  params?: ListGapsQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = listGapsSuspenseQueryKey(params)
  return queryOptions<
    ListGapsQueryResponse,
    ResponseErrorConfig<ListGaps422>,
    ListGapsQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return listGaps(params, { ...config, signal: config.signal ?? signal })
    },
  })
}

/**
 * @summary List Gaps
 * {@link /api/v1/gaps}
 */
export function useListGapsSuspense<
  TData = ListGapsQueryResponse,
  TQueryKey extends QueryKey = ListGapsSuspenseQueryKey,
>(
  params?: ListGapsQueryParams,
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        ListGapsQueryResponse,
        ResponseErrorConfig<ListGaps422>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey = resolvedOptions?.queryKey ?? listGapsSuspenseQueryKey(params)

  const query = useSuspenseQuery(
    {
      ...listGapsSuspenseQueryOptions(params, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as UseSuspenseQueryOptions,
    queryClient
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<ListGaps422>> & {
    queryKey: TQueryKey
  }

  query.queryKey = queryKey as TQueryKey

  return query
}
