/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  ListTradesQueryResponse,
  ListTradesQueryParams,
  ListTrades422,
} from "../types/ListTrades"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios"
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query"
import { listTrades } from "../clients/listTrades"
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query"

export const listTradesSuspenseQueryKey = (params?: ListTradesQueryParams) =>
  [{ url: "/api/v1/trades" }, ...(params ? [params] : [])] as const

export type ListTradesSuspenseQueryKey = ReturnType<
  typeof listTradesSuspenseQueryKey
>

export function listTradesSuspenseQueryOptions(
  params?: ListTradesQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = listTradesSuspenseQueryKey(params)
  return queryOptions<
    ListTradesQueryResponse,
    ResponseErrorConfig<ListTrades422>,
    ListTradesQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return listTrades(params, { ...config, signal: config.signal ?? signal })
    },
  })
}

/**
 * @description Collectors who want a spare card and hold a wanted one.
 * A match is a possibility, not an agreement: nothing here moves a card. The
 * cards named are only the two-way overlap, so what else a counterparty owns
 * stays theirs.
 * @summary List Trades
 * {@link /api/v1/trades}
 */
export function useListTradesSuspense<
  TData = ListTradesQueryResponse,
  TQueryKey extends QueryKey = ListTradesSuspenseQueryKey,
>(
  params?: ListTradesQueryParams,
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        ListTradesQueryResponse,
        ResponseErrorConfig<ListTrades422>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey =
    resolvedOptions?.queryKey ?? listTradesSuspenseQueryKey(params)

  const query = useSuspenseQuery(
    {
      ...listTradesSuspenseQueryOptions(params, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as UseSuspenseQueryOptions,
    queryClient
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<ListTrades422>> & {
    queryKey: TQueryKey
  }

  query.queryKey = queryKey as TQueryKey

  return query
}
