/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { MarketConcentrationQueryResponse } from "../types/MarketConcentration"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios"
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query"
import { marketConcentration } from "../clients/marketConcentration"
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query"

export const marketConcentrationSuspenseQueryKey = () =>
  [{ url: "/api/v1/catalog/market/concentration" }] as const

export type MarketConcentrationSuspenseQueryKey = ReturnType<
  typeof marketConcentrationSuspenseQueryKey
>

export function marketConcentrationSuspenseQueryOptions(
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = marketConcentrationSuspenseQueryKey()
  return queryOptions<
    MarketConcentrationQueryResponse,
    ResponseErrorConfig<Error>,
    MarketConcentrationQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return marketConcentration({
        ...config,
        signal: config.signal ?? signal,
      })
    },
  })
}

/**
 * @description How few cards carry the value of the portfolio.
 * @summary Market Concentration
 * {@link /api/v1/catalog/market/concentration}
 */
export function useMarketConcentrationSuspense<
  TData = MarketConcentrationQueryResponse,
  TQueryKey extends QueryKey = MarketConcentrationSuspenseQueryKey,
>(
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        MarketConcentrationQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey =
    resolvedOptions?.queryKey ?? marketConcentrationSuspenseQueryKey()

  const query = useSuspenseQuery(
    {
      ...marketConcentrationSuspenseQueryOptions(config),
      ...resolvedOptions,
      queryKey,
    } as unknown as UseSuspenseQueryOptions,
    queryClient
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey
  }

  query.queryKey = queryKey as TQueryKey

  return query
}
