/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { MeQueryResponse } from "../types/Me"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios"
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query"
import { me } from "../clients/me"
import { queryOptions, useQuery } from "@tanstack/react-query"

export const meQueryKey = () => [{ url: "/api/v1/me" }] as const

export type MeQueryKey = ReturnType<typeof meQueryKey>

export function meQueryOptions(
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = meQueryKey()
  return queryOptions<
    MeQueryResponse,
    ResponseErrorConfig<Error>,
    MeQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return me({ ...config, signal: config.signal ?? signal })
    },
  })
}

/**
 * @summary Me
 * {@link /api/v1/me}
 */
export function useMe<
  TData = MeQueryResponse,
  TQueryData = MeQueryResponse,
  TQueryKey extends QueryKey = MeQueryKey,
>(
  options: {
    query?: Partial<
      QueryObserverOptions<
        MeQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey = resolvedOptions?.queryKey ?? meQueryKey()

  const query = useQuery(
    {
      ...meQueryOptions(config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey
  }

  query.queryKey = queryKey as TQueryKey

  return query
}
