/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { MarketSummaryQueryResponse } from "../types/MarketSummary"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios"
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query"
import { marketSummary } from "../clients/marketSummary"
import { queryOptions, useQuery } from "@tanstack/react-query"

export const marketSummaryQueryKey = () =>
  [{ url: "/api/v1/catalog/market/summary" }] as const

export type MarketSummaryQueryKey = ReturnType<typeof marketSummaryQueryKey>

export function marketSummaryQueryOptions(
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = marketSummaryQueryKey()
  return queryOptions<
    MarketSummaryQueryResponse,
    ResponseErrorConfig<Error>,
    MarketSummaryQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return marketSummary({ ...config, signal: config.signal ?? signal })
    },
  })
}

/**
 * @summary Market Summary
 * {@link /api/v1/catalog/market/summary}
 */
export function useMarketSummary<
  TData = MarketSummaryQueryResponse,
  TQueryData = MarketSummaryQueryResponse,
  TQueryKey extends QueryKey = MarketSummaryQueryKey,
>(
  options: {
    query?: Partial<
      QueryObserverOptions<
        MarketSummaryQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey = resolvedOptions?.queryKey ?? marketSummaryQueryKey()

  const query = useQuery(
    {
      ...marketSummaryQueryOptions(config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey
  }

  query.queryKey = queryKey as TQueryKey

  return query
}
