/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { MarketConcentrationQueryResponse } from "../types/MarketConcentration"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios"
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query"
import { marketConcentration } from "../clients/marketConcentration"
import { queryOptions, useQuery } from "@tanstack/react-query"

export const marketConcentrationQueryKey = () =>
  [{ url: "/api/v1/catalog/market/concentration" }] as const

export type MarketConcentrationQueryKey = ReturnType<
  typeof marketConcentrationQueryKey
>

export function marketConcentrationQueryOptions(
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = marketConcentrationQueryKey()
  return queryOptions<
    MarketConcentrationQueryResponse,
    ResponseErrorConfig<Error>,
    MarketConcentrationQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return marketConcentration({
        ...config,
        signal: config.signal ?? signal,
      })
    },
  })
}

/**
 * @description How few cards carry the value of the portfolio.
 * @summary Market Concentration
 * {@link /api/v1/catalog/market/concentration}
 */
export function useMarketConcentration<
  TData = MarketConcentrationQueryResponse,
  TQueryData = MarketConcentrationQueryResponse,
  TQueryKey extends QueryKey = MarketConcentrationQueryKey,
>(
  options: {
    query?: Partial<
      QueryObserverOptions<
        MarketConcentrationQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey = resolvedOptions?.queryKey ?? marketConcentrationQueryKey()

  const query = useQuery(
    {
      ...marketConcentrationQueryOptions(config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey
  }

  query.queryKey = queryKey as TQueryKey

  return query
}
