/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { MarkNewsSeenMutationResponse } from "../types/MarkNewsSeen";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { markNewsSeen } from "../clients/markNewsSeen";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const markNewsSeenMutationKey = () =>
  [{ url: "/api/v1/news/seen" }] as const;

export type MarkNewsSeenMutationKey = ReturnType<
  typeof markNewsSeenMutationKey
>;

export function markNewsSeenMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const mutationKey = markNewsSeenMutationKey();
  return mutationOptions<
    MarkNewsSeenMutationResponse,
    ResponseErrorConfig<Error>,
    void,
    TContext
  >({
    mutationKey,
    mutationFn: async () => {
      return markNewsSeen(config);
    },
  });
}

/**
 * @summary Mark News Seen
 * {@link /api/v1/news/seen}
 */
export function useMarkNewsSeen<TContext>(
  options: {
    mutation?: UseMutationOptions<
      MarkNewsSeenMutationResponse,
      ResponseErrorConfig<Error>,
      void,
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? markNewsSeenMutationKey();

  const baseOptions = markNewsSeenMutationOptions(config) as UseMutationOptions<
    MarkNewsSeenMutationResponse,
    ResponseErrorConfig<Error>,
    void,
    TContext
  >;

  return useMutation<
    MarkNewsSeenMutationResponse,
    ResponseErrorConfig<Error>,
    void,
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    MarkNewsSeenMutationResponse,
    ResponseErrorConfig<Error>,
    void,
    TContext
  >;
}
