/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { MarketSetsQueryResponse } from "../types/MarketSets"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios"
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query"
import { marketSets } from "../clients/marketSets"
import { queryOptions, useQuery } from "@tanstack/react-query"

export const marketSetsQueryKey = () =>
  [{ url: "/api/v1/catalog/market/sets" }] as const

export type MarketSetsQueryKey = ReturnType<typeof marketSetsQueryKey>

export function marketSetsQueryOptions(
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = marketSetsQueryKey()
  return queryOptions<
    MarketSetsQueryResponse,
    ResponseErrorConfig<Error>,
    MarketSetsQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return marketSets({ ...config, signal: config.signal ?? signal })
    },
  })
}

/**
 * @description Each set as a position, costliest to finish first.
 * @summary Market Sets
 * {@link /api/v1/catalog/market/sets}
 */
export function useMarketSets<
  TData = MarketSetsQueryResponse,
  TQueryData = MarketSetsQueryResponse,
  TQueryKey extends QueryKey = MarketSetsQueryKey,
>(
  options: {
    query?: Partial<
      QueryObserverOptions<
        MarketSetsQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey = resolvedOptions?.queryKey ?? marketSetsQueryKey()

  const query = useQuery(
    {
      ...marketSetsQueryOptions(config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey
  }

  query.queryKey = queryKey as TQueryKey

  return query
}
