/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { MarketSummaryQueryResponse } from "../types/MarketSummary"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios"
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query"
import { marketSummary } from "../clients/marketSummary"
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query"

export const marketSummarySuspenseQueryKey = () =>
  [{ url: "/api/v1/catalog/market/summary" }] as const

export type MarketSummarySuspenseQueryKey = ReturnType<
  typeof marketSummarySuspenseQueryKey
>

export function marketSummarySuspenseQueryOptions(
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = marketSummarySuspenseQueryKey()
  return queryOptions<
    MarketSummaryQueryResponse,
    ResponseErrorConfig<Error>,
    MarketSummaryQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return marketSummary({ ...config, signal: config.signal ?? signal })
    },
  })
}

/**
 * @summary Market Summary
 * {@link /api/v1/catalog/market/summary}
 */
export function useMarketSummarySuspense<
  TData = MarketSummaryQueryResponse,
  TQueryKey extends QueryKey = MarketSummarySuspenseQueryKey,
>(
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        MarketSummaryQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey = resolvedOptions?.queryKey ?? marketSummarySuspenseQueryKey()

  const query = useSuspenseQuery(
    {
      ...marketSummarySuspenseQueryOptions(config),
      ...resolvedOptions,
      queryKey,
    } as unknown as UseSuspenseQueryOptions,
    queryClient
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey
  }

  query.queryKey = queryKey as TQueryKey

  return query
}
