/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  MarketCardsQueryResponse,
  MarketCardsQueryParams,
  MarketCards422,
} from "../types/MarketCards"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios"
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query"
import { marketCards } from "../clients/marketCards"
import { queryOptions, useQuery } from "@tanstack/react-query"

export const marketCardsQueryKey = (params?: MarketCardsQueryParams) =>
  [{ url: "/api/v1/catalog/market" }, ...(params ? [params] : [])] as const

export type MarketCardsQueryKey = ReturnType<typeof marketCardsQueryKey>

export function marketCardsQueryOptions(
  params?: MarketCardsQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = marketCardsQueryKey(params)
  return queryOptions<
    MarketCardsQueryResponse,
    ResponseErrorConfig<MarketCards422>,
    MarketCardsQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return marketCards(params, { ...config, signal: config.signal ?? signal })
    },
  })
}

/**
 * @description The whole catalog, each card marked with how many copies the reader holds.
 * @summary Market Cards
 * {@link /api/v1/catalog/market}
 */
export function useMarketCards<
  TData = MarketCardsQueryResponse,
  TQueryData = MarketCardsQueryResponse,
  TQueryKey extends QueryKey = MarketCardsQueryKey,
>(
  params?: MarketCardsQueryParams,
  options: {
    query?: Partial<
      QueryObserverOptions<
        MarketCardsQueryResponse,
        ResponseErrorConfig<MarketCards422>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey = resolvedOptions?.queryKey ?? marketCardsQueryKey(params)

  const query = useQuery(
    {
      ...marketCardsQueryOptions(params, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient
  ) as UseQueryResult<TData, ResponseErrorConfig<MarketCards422>> & {
    queryKey: TQueryKey
  }

  query.queryKey = queryKey as TQueryKey

  return query
}
