/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { MarketSetsQueryResponse } from "../types/MarketSets"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios"
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query"
import { marketSets } from "../clients/marketSets"
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query"

export const marketSetsSuspenseQueryKey = () =>
  [{ url: "/api/v1/catalog/market/sets" }] as const

export type MarketSetsSuspenseQueryKey = ReturnType<
  typeof marketSetsSuspenseQueryKey
>

export function marketSetsSuspenseQueryOptions(
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = marketSetsSuspenseQueryKey()
  return queryOptions<
    MarketSetsQueryResponse,
    ResponseErrorConfig<Error>,
    MarketSetsQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return marketSets({ ...config, signal: config.signal ?? signal })
    },
  })
}

/**
 * @description Each set as a position, costliest to finish first.
 * @summary Market Sets
 * {@link /api/v1/catalog/market/sets}
 */
export function useMarketSetsSuspense<
  TData = MarketSetsQueryResponse,
  TQueryKey extends QueryKey = MarketSetsSuspenseQueryKey,
>(
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        MarketSetsQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey = resolvedOptions?.queryKey ?? marketSetsSuspenseQueryKey()

  const query = useSuspenseQuery(
    {
      ...marketSetsSuspenseQueryOptions(config),
      ...resolvedOptions,
      queryKey,
    } as unknown as UseSuspenseQueryOptions,
    queryClient
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey
  }

  query.queryKey = queryKey as TQueryKey

  return query
}
