/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  MarketCardsQueryResponse,
  MarketCardsQueryParams,
  MarketCards422,
} from "../types/MarketCards"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios"
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query"
import { marketCards } from "../clients/marketCards"
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query"

export const marketCardsSuspenseQueryKey = (params?: MarketCardsQueryParams) =>
  [{ url: "/api/v1/catalog/market" }, ...(params ? [params] : [])] as const

export type MarketCardsSuspenseQueryKey = ReturnType<
  typeof marketCardsSuspenseQueryKey
>

export function marketCardsSuspenseQueryOptions(
  params?: MarketCardsQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = marketCardsSuspenseQueryKey(params)
  return queryOptions<
    MarketCardsQueryResponse,
    ResponseErrorConfig<MarketCards422>,
    MarketCardsQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return marketCards(params, { ...config, signal: config.signal ?? signal })
    },
  })
}

/**
 * @description The whole catalog, each card marked with how many copies the reader holds.
 * @summary Market Cards
 * {@link /api/v1/catalog/market}
 */
export function useMarketCardsSuspense<
  TData = MarketCardsQueryResponse,
  TQueryKey extends QueryKey = MarketCardsSuspenseQueryKey,
>(
  params?: MarketCardsQueryParams,
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        MarketCardsQueryResponse,
        ResponseErrorConfig<MarketCards422>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey =
    resolvedOptions?.queryKey ?? marketCardsSuspenseQueryKey(params)

  const query = useSuspenseQuery(
    {
      ...marketCardsSuspenseQueryOptions(params, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as UseSuspenseQueryOptions,
    queryClient
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<MarketCards422>> & {
    queryKey: TQueryKey
  }

  query.queryKey = queryKey as TQueryKey

  return query
}
