/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { MeQueryResponse } from "../types/Me"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios"
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query"
import { me } from "../clients/me"
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query"

export const meSuspenseQueryKey = () => [{ url: "/api/v1/me" }] as const

export type MeSuspenseQueryKey = ReturnType<typeof meSuspenseQueryKey>

export function meSuspenseQueryOptions(
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = meSuspenseQueryKey()
  return queryOptions<
    MeQueryResponse,
    ResponseErrorConfig<Error>,
    MeQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return me({ ...config, signal: config.signal ?? signal })
    },
  })
}

/**
 * @summary Me
 * {@link /api/v1/me}
 */
export function useMeSuspense<
  TData = MeQueryResponse,
  TQueryKey extends QueryKey = MeSuspenseQueryKey,
>(
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        MeQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey = resolvedOptions?.queryKey ?? meSuspenseQueryKey()

  const query = useSuspenseQuery(
    {
      ...meSuspenseQueryOptions(config),
      ...resolvedOptions,
      queryKey,
    } as unknown as UseSuspenseQueryOptions,
    queryClient
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey
  }

  query.queryKey = queryKey as TQueryKey

  return query
}
