/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  NewsFeedQueryResponse,
  NewsFeedQueryParams,
  NewsFeed422,
} from "../types/NewsFeed";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { newsFeed } from "../clients/newsFeed";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const newsFeedQueryKey = (params?: NewsFeedQueryParams) =>
  [{ url: "/api/v1/news" }, ...(params ? [params] : [])] as const;

export type NewsFeedQueryKey = ReturnType<typeof newsFeedQueryKey>;

export function newsFeedQueryOptions(
  params?: NewsFeedQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = newsFeedQueryKey(params);
  return queryOptions<
    NewsFeedQueryResponse,
    ResponseErrorConfig<NewsFeed422>,
    NewsFeedQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return newsFeed(params, { ...config, signal: config.signal ?? signal });
    },
  });
}

/**
 * @summary News Feed
 * {@link /api/v1/news}
 */
export function useNewsFeed<
  TData = NewsFeedQueryResponse,
  TQueryData = NewsFeedQueryResponse,
  TQueryKey extends QueryKey = NewsFeedQueryKey,
>(
  params?: NewsFeedQueryParams,
  options: {
    query?: Partial<
      QueryObserverOptions<
        NewsFeedQueryResponse,
        ResponseErrorConfig<NewsFeed422>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey = resolvedOptions?.queryKey ?? newsFeedQueryKey(params);

  const query = useQuery(
    {
      ...newsFeedQueryOptions(params, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<NewsFeed422>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
