/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  NewsFeedQueryResponse,
  NewsFeedQueryParams,
  NewsFeed422,
} from "../types/NewsFeed";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { newsFeed } from "../clients/newsFeed";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const newsFeedSuspenseQueryKey = (params?: NewsFeedQueryParams) =>
  [{ url: "/api/v1/news" }, ...(params ? [params] : [])] as const;

export type NewsFeedSuspenseQueryKey = ReturnType<
  typeof newsFeedSuspenseQueryKey
>;

export function newsFeedSuspenseQueryOptions(
  params?: NewsFeedQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = newsFeedSuspenseQueryKey(params);
  return queryOptions<
    NewsFeedQueryResponse,
    ResponseErrorConfig<NewsFeed422>,
    NewsFeedQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return newsFeed(params, { ...config, signal: config.signal ?? signal });
    },
  });
}

/**
 * @summary News Feed
 * {@link /api/v1/news}
 */
export function useNewsFeedSuspense<
  TData = NewsFeedQueryResponse,
  TQueryKey extends QueryKey = NewsFeedSuspenseQueryKey,
>(
  params?: NewsFeedQueryParams,
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        NewsFeedQueryResponse,
        ResponseErrorConfig<NewsFeed422>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey =
    resolvedOptions?.queryKey ?? newsFeedSuspenseQueryKey(params);

  const query = useSuspenseQuery(
    {
      ...newsFeedSuspenseQueryOptions(params, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as UseSuspenseQueryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<NewsFeed422>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
