/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { OwnedCardIdsQueryResponse } from "../types/OwnedCardIds"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios"
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query"
import { ownedCardIds } from "../clients/ownedCardIds"
import { queryOptions, useQuery } from "@tanstack/react-query"

export const ownedCardIdsQueryKey = () =>
  [{ url: "/api/v1/catalog/owned-ids" }] as const

export type OwnedCardIdsQueryKey = ReturnType<typeof ownedCardIdsQueryKey>

export function ownedCardIdsQueryOptions(
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = ownedCardIdsQueryKey()
  return queryOptions<
    OwnedCardIdsQueryResponse,
    ResponseErrorConfig<Error>,
    OwnedCardIdsQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return ownedCardIds({ ...config, signal: config.signal ?? signal })
    },
  })
}

/**
 * @description Which catalog cards the user holds, so a card list can mark them.
 * @summary Owned Card Ids
 * {@link /api/v1/catalog/owned-ids}
 */
export function useOwnedCardIds<
  TData = OwnedCardIdsQueryResponse,
  TQueryData = OwnedCardIdsQueryResponse,
  TQueryKey extends QueryKey = OwnedCardIdsQueryKey,
>(
  options: {
    query?: Partial<
      QueryObserverOptions<
        OwnedCardIdsQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey = resolvedOptions?.queryKey ?? ownedCardIdsQueryKey()

  const query = useQuery(
    {
      ...ownedCardIdsQueryOptions(config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey
  }

  query.queryKey = queryKey as TQueryKey

  return query
}
