/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { OwnedCardIdsQueryResponse } from "../types/OwnedCardIds"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios"
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query"
import { ownedCardIds } from "../clients/ownedCardIds"
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query"

export const ownedCardIdsSuspenseQueryKey = () =>
  [{ url: "/api/v1/catalog/owned-ids" }] as const

export type OwnedCardIdsSuspenseQueryKey = ReturnType<
  typeof ownedCardIdsSuspenseQueryKey
>

export function ownedCardIdsSuspenseQueryOptions(
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = ownedCardIdsSuspenseQueryKey()
  return queryOptions<
    OwnedCardIdsQueryResponse,
    ResponseErrorConfig<Error>,
    OwnedCardIdsQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return ownedCardIds({ ...config, signal: config.signal ?? signal })
    },
  })
}

/**
 * @description Which catalog cards the user holds, so a card list can mark them.
 * @summary Owned Card Ids
 * {@link /api/v1/catalog/owned-ids}
 */
export function useOwnedCardIdsSuspense<
  TData = OwnedCardIdsQueryResponse,
  TQueryKey extends QueryKey = OwnedCardIdsSuspenseQueryKey,
>(
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        OwnedCardIdsQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey = resolvedOptions?.queryKey ?? ownedCardIdsSuspenseQueryKey()

  const query = useSuspenseQuery(
    {
      ...ownedCardIdsSuspenseQueryOptions(config),
      ...resolvedOptions,
      queryKey,
    } as unknown as UseSuspenseQueryOptions,
    queryClient
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey
  }

  query.queryKey = queryKey as TQueryKey

  return query
}
