/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  ProposeTradeMutationRequest,
  ProposeTradeMutationResponse,
  ProposeTrade422,
} from "../types/ProposeTrade";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { proposeTrade } from "../clients/proposeTrade";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const proposeTradeMutationKey = () =>
  [{ url: "/api/v1/advice/trade" }] as const;

export type ProposeTradeMutationKey = ReturnType<
  typeof proposeTradeMutationKey
>;

export function proposeTradeMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig<ProposeTradeMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const mutationKey = proposeTradeMutationKey();
  return mutationOptions<
    ProposeTradeMutationResponse,
    ResponseErrorConfig<ProposeTrade422>,
    { data: ProposeTradeMutationRequest },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ data }) => {
      return proposeTrade(data, config);
    },
  });
}

/**
 * @description One swap worth simulating, drawn from what the reader has spare and wants.
 * @summary Propose Trade
 * {@link /api/v1/advice/trade}
 */
export function useProposeTrade<TContext>(
  options: {
    mutation?: UseMutationOptions<
      ProposeTradeMutationResponse,
      ResponseErrorConfig<ProposeTrade422>,
      { data: ProposeTradeMutationRequest },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<ProposeTradeMutationRequest>> & {
      client?: Client;
    };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? proposeTradeMutationKey();

  const baseOptions = proposeTradeMutationOptions(config) as UseMutationOptions<
    ProposeTradeMutationResponse,
    ResponseErrorConfig<ProposeTrade422>,
    { data: ProposeTradeMutationRequest },
    TContext
  >;

  return useMutation<
    ProposeTradeMutationResponse,
    ResponseErrorConfig<ProposeTrade422>,
    { data: ProposeTradeMutationRequest },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    ProposeTradeMutationResponse,
    ResponseErrorConfig<ProposeTrade422>,
    { data: ProposeTradeMutationRequest },
    TContext
  >;
}
