/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RevokeShareLinkMutationResponse } from "../types/RevokeShareLink"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios"
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query"
import { revokeShareLink } from "../clients/revokeShareLink"
import { mutationOptions, useMutation } from "@tanstack/react-query"

export const revokeShareLinkMutationKey = () =>
  [{ url: "/api/v1/share" }] as const

export type RevokeShareLinkMutationKey = ReturnType<
  typeof revokeShareLinkMutationKey
>

export function revokeShareLinkMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const mutationKey = revokeShareLinkMutationKey()
  return mutationOptions<
    RevokeShareLinkMutationResponse,
    ResponseErrorConfig<Error>,
    void,
    TContext
  >({
    mutationKey,
    mutationFn: async () => {
      return revokeShareLink(config)
    },
  })
}

/**
 * @summary Revoke Share Link
 * {@link /api/v1/share}
 */
export function useRevokeShareLink<TContext>(
  options: {
    mutation?: UseMutationOptions<
      RevokeShareLinkMutationResponse,
      ResponseErrorConfig<Error>,
      void,
      TContext
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {}
) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation
  const mutationKey =
    mutationOptions.mutationKey ?? revokeShareLinkMutationKey()

  const baseOptions = revokeShareLinkMutationOptions(
    config
  ) as UseMutationOptions<
    RevokeShareLinkMutationResponse,
    ResponseErrorConfig<Error>,
    void,
    TContext
  >

  return useMutation<
    RevokeShareLinkMutationResponse,
    ResponseErrorConfig<Error>,
    void,
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient
  ) as UseMutationResult<
    RevokeShareLinkMutationResponse,
    ResponseErrorConfig<Error>,
    void,
    TContext
  >
}
