/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  ReadSharedCollectionQueryResponse,
  ReadSharedCollectionPathParams,
  ReadSharedCollection422,
} from "../types/ReadSharedCollection"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios"
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query"
import { readSharedCollection } from "../clients/readSharedCollection"
import { queryOptions, useQuery } from "@tanstack/react-query"

export const readSharedCollectionQueryKey = (
  token: ReadSharedCollectionPathParams["token"] | undefined
) => [{ url: "/api/v1/public/:token", params: { token: token } }] as const

export type ReadSharedCollectionQueryKey = ReturnType<
  typeof readSharedCollectionQueryKey
>

export function readSharedCollectionQueryOptions(
  token: ReadSharedCollectionPathParams["token"] | undefined,
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = readSharedCollectionQueryKey(token)
  return queryOptions<
    ReadSharedCollectionQueryResponse,
    ResponseErrorConfig<ReadSharedCollection422>,
    ReadSharedCollectionQueryResponse,
    typeof queryKey
  >({
    enabled: !!token,
    queryKey,
    queryFn: async ({ signal }) => {
      return readSharedCollection(token!, {
        ...config,
        signal: config.signal ?? signal,
      })
    },
  })
}

/**
 * @description The only unauthenticated route in the API.
 * It answers 404 for a revoked link exactly as it does for one that never
 * existed, so a revoked token cannot be told apart from a wrong guess.
 * @summary Read Shared Collection
 * {@link /api/v1/public/:token}
 */
export function useReadSharedCollection<
  TData = ReadSharedCollectionQueryResponse,
  TQueryData = ReadSharedCollectionQueryResponse,
  TQueryKey extends QueryKey = ReadSharedCollectionQueryKey,
>(
  token: ReadSharedCollectionPathParams["token"] | undefined,
  options: {
    query?: Partial<
      QueryObserverOptions<
        ReadSharedCollectionQueryResponse,
        ResponseErrorConfig<ReadSharedCollection422>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey =
    resolvedOptions?.queryKey ?? readSharedCollectionQueryKey(token)

  const query = useQuery(
    {
      ...readSharedCollectionQueryOptions(token, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient
  ) as UseQueryResult<TData, ResponseErrorConfig<ReadSharedCollection422>> & {
    queryKey: TQueryKey
  }

  query.queryKey = queryKey as TQueryKey

  return query
}
