/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  RespondToOfferMutationRequest,
  RespondToOfferMutationResponse,
  RespondToOfferPathParams,
  RespondToOffer422,
} from "../types/RespondToOffer"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios"
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query"
import { respondToOffer } from "../clients/respondToOffer"
import { mutationOptions, useMutation } from "@tanstack/react-query"

export const respondToOfferMutationKey = () =>
  [{ url: "/api/v1/trades/offers/:offer_id/respond" }] as const

export type RespondToOfferMutationKey = ReturnType<
  typeof respondToOfferMutationKey
>

export function respondToOfferMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig<RespondToOfferMutationRequest>> & {
    client?: Client
  } = {}
) {
  const mutationKey = respondToOfferMutationKey()
  return mutationOptions<
    RespondToOfferMutationResponse,
    ResponseErrorConfig<RespondToOffer422>,
    {
      offer_id: RespondToOfferPathParams["offer_id"]
      data: RespondToOfferMutationRequest
    },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ offer_id, data }) => {
      return respondToOffer(offer_id, data, config)
    },
  })
}

/**
 * @description Accept or decline an offer. Only its recipient may, and only once.
 * @summary Respond To Offer
 * {@link /api/v1/trades/offers/:offer_id/respond}
 */
export function useRespondToOffer<TContext>(
  options: {
    mutation?: UseMutationOptions<
      RespondToOfferMutationResponse,
      ResponseErrorConfig<RespondToOffer422>,
      {
        offer_id: RespondToOfferPathParams["offer_id"]
        data: RespondToOfferMutationRequest
      },
      TContext
    > & { client?: QueryClient }
    client?: Partial<RequestConfig<RespondToOfferMutationRequest>> & {
      client?: Client
    }
  } = {}
) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation
  const mutationKey = mutationOptions.mutationKey ?? respondToOfferMutationKey()

  const baseOptions = respondToOfferMutationOptions(
    config
  ) as UseMutationOptions<
    RespondToOfferMutationResponse,
    ResponseErrorConfig<RespondToOffer422>,
    {
      offer_id: RespondToOfferPathParams["offer_id"]
      data: RespondToOfferMutationRequest
    },
    TContext
  >

  return useMutation<
    RespondToOfferMutationResponse,
    ResponseErrorConfig<RespondToOffer422>,
    {
      offer_id: RespondToOfferPathParams["offer_id"]
      data: RespondToOfferMutationRequest
    },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient
  ) as UseMutationResult<
    RespondToOfferMutationResponse,
    ResponseErrorConfig<RespondToOffer422>,
    {
      offer_id: RespondToOfferPathParams["offer_id"]
      data: RespondToOfferMutationRequest
    },
    TContext
  >
}
