/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  ReadSharedCollectionQueryResponse,
  ReadSharedCollectionPathParams,
  ReadSharedCollection422,
} from "../types/ReadSharedCollection"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios"
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query"
import { readSharedCollection } from "../clients/readSharedCollection"
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query"

export const readSharedCollectionSuspenseQueryKey = (
  token: ReadSharedCollectionPathParams["token"] | undefined
) => [{ url: "/api/v1/public/:token", params: { token: token } }] as const

export type ReadSharedCollectionSuspenseQueryKey = ReturnType<
  typeof readSharedCollectionSuspenseQueryKey
>

export function readSharedCollectionSuspenseQueryOptions(
  token: ReadSharedCollectionPathParams["token"],
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = readSharedCollectionSuspenseQueryKey(token)
  return queryOptions<
    ReadSharedCollectionQueryResponse,
    ResponseErrorConfig<ReadSharedCollection422>,
    ReadSharedCollectionQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return readSharedCollection(token, {
        ...config,
        signal: config.signal ?? signal,
      })
    },
  })
}

/**
 * @description The only unauthenticated route in the API.
 * It answers 404 for a revoked link exactly as it does for one that never
 * existed, so a revoked token cannot be told apart from a wrong guess.
 * @summary Read Shared Collection
 * {@link /api/v1/public/:token}
 */
export function useReadSharedCollectionSuspense<
  TData = ReadSharedCollectionQueryResponse,
  TQueryKey extends QueryKey = ReadSharedCollectionSuspenseQueryKey,
>(
  token: ReadSharedCollectionPathParams["token"],
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        ReadSharedCollectionQueryResponse,
        ResponseErrorConfig<ReadSharedCollection422>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey =
    resolvedOptions?.queryKey ?? readSharedCollectionSuspenseQueryKey(token)

  const query = useSuspenseQuery(
    {
      ...readSharedCollectionSuspenseQueryOptions(token, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as UseSuspenseQueryOptions,
    queryClient
  ) as UseSuspenseQueryResult<
    TData,
    ResponseErrorConfig<ReadSharedCollection422>
  > & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}
