/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  SearchSpeciesQueryResponse,
  SearchSpeciesQueryParams,
  SearchSpecies422,
} from "../types/SearchSpecies"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios"
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query"
import { searchSpecies } from "../clients/searchSpecies"
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query"

export const searchSpeciesSuspenseQueryKey = (
  params?: SearchSpeciesQueryParams
) => [{ url: "/api/v1/catalog/species" }, ...(params ? [params] : [])] as const

export type SearchSpeciesSuspenseQueryKey = ReturnType<
  typeof searchSpeciesSuspenseQueryKey
>

export function searchSpeciesSuspenseQueryOptions(
  params?: SearchSpeciesQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = searchSpeciesSuspenseQueryKey(params)
  return queryOptions<
    SearchSpeciesQueryResponse,
    ResponseErrorConfig<SearchSpecies422>,
    SearchSpeciesQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return searchSpecies(params, {
        ...config,
        signal: config.signal ?? signal,
      })
    },
  })
}

/**
 * @summary Search Species
 * {@link /api/v1/catalog/species}
 */
export function useSearchSpeciesSuspense<
  TData = SearchSpeciesQueryResponse,
  TQueryKey extends QueryKey = SearchSpeciesSuspenseQueryKey,
>(
  params?: SearchSpeciesQueryParams,
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        SearchSpeciesQueryResponse,
        ResponseErrorConfig<SearchSpecies422>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey =
    resolvedOptions?.queryKey ?? searchSpeciesSuspenseQueryKey(params)

  const query = useSuspenseQuery(
    {
      ...searchSpeciesSuspenseQueryOptions(params, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as UseSuspenseQueryOptions,
    queryClient
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<SearchSpecies422>> & {
    queryKey: TQueryKey
  }

  query.queryKey = queryKey as TQueryKey

  return query
}
