/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  SearchCardsQueryResponse,
  SearchCardsQueryParams,
  SearchCards422,
} from "../types/SearchCards"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios"
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query"
import { searchCards } from "../clients/searchCards"
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query"

export const searchCardsSuspenseQueryKey = (params?: SearchCardsQueryParams) =>
  [{ url: "/api/v1/catalog/cards" }, ...(params ? [params] : [])] as const

export type SearchCardsSuspenseQueryKey = ReturnType<
  typeof searchCardsSuspenseQueryKey
>

export function searchCardsSuspenseQueryOptions(
  params?: SearchCardsQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = searchCardsSuspenseQueryKey(params)
  return queryOptions<
    SearchCardsQueryResponse,
    ResponseErrorConfig<SearchCards422>,
    SearchCardsQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return searchCards(params, { ...config, signal: config.signal ?? signal })
    },
  })
}

/**
 * @summary Search Cards
 * {@link /api/v1/catalog/cards}
 */
export function useSearchCardsSuspense<
  TData = SearchCardsQueryResponse,
  TQueryKey extends QueryKey = SearchCardsSuspenseQueryKey,
>(
  params?: SearchCardsQueryParams,
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        SearchCardsQueryResponse,
        ResponseErrorConfig<SearchCards422>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey =
    resolvedOptions?.queryKey ?? searchCardsSuspenseQueryKey(params)

  const query = useSuspenseQuery(
    {
      ...searchCardsSuspenseQueryOptions(params, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as UseSuspenseQueryOptions,
    queryClient
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<SearchCards422>> & {
    queryKey: TQueryKey
  }

  query.queryKey = queryKey as TQueryKey

  return query
}
