/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  SpeciesTriviaQueryResponse,
  SpeciesTriviaPathParams,
  SpeciesTrivia422,
} from "../types/SpeciesTrivia"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios"
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query"
import { speciesTrivia } from "../clients/speciesTrivia"
import { queryOptions, useQuery } from "@tanstack/react-query"

export const speciesTriviaQueryKey = (
  species_id: SpeciesTriviaPathParams["species_id"] | undefined
) =>
  [
    {
      url: "/api/v1/catalog/species/:species_id/trivia",
      params: { species_id: species_id },
    },
  ] as const

export type SpeciesTriviaQueryKey = ReturnType<typeof speciesTriviaQueryKey>

export function speciesTriviaQueryOptions(
  species_id: SpeciesTriviaPathParams["species_id"] | undefined,
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = speciesTriviaQueryKey(species_id)
  return queryOptions<
    SpeciesTriviaQueryResponse,
    ResponseErrorConfig<SpeciesTrivia422>,
    SpeciesTriviaQueryResponse,
    typeof queryKey
  >({
    enabled: !!species_id,
    queryKey,
    queryFn: async ({ signal }) => {
      return speciesTrivia(species_id!, {
        ...config,
        signal: config.signal ?? signal,
      })
    },
  })
}

/**
 * @description A blurb about the species, generated once and shared by every reader.
 * @summary Species Trivia
 * {@link /api/v1/catalog/species/:species_id/trivia}
 */
export function useSpeciesTrivia<
  TData = SpeciesTriviaQueryResponse,
  TQueryData = SpeciesTriviaQueryResponse,
  TQueryKey extends QueryKey = SpeciesTriviaQueryKey,
>(
  species_id: SpeciesTriviaPathParams["species_id"] | undefined,
  options: {
    query?: Partial<
      QueryObserverOptions<
        SpeciesTriviaQueryResponse,
        ResponseErrorConfig<SpeciesTrivia422>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey =
    resolvedOptions?.queryKey ?? speciesTriviaQueryKey(species_id)

  const query = useQuery(
    {
      ...speciesTriviaQueryOptions(species_id, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient
  ) as UseQueryResult<TData, ResponseErrorConfig<SpeciesTrivia422>> & {
    queryKey: TQueryKey
  }

  query.queryKey = queryKey as TQueryKey

  return query
}
