/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  SimulateTradeMutationRequest,
  SimulateTradeMutationResponse,
  SimulateTrade422,
} from "../types/SimulateTrade"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios"
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query"
import { simulateTrade } from "../clients/simulateTrade"
import { mutationOptions, useMutation } from "@tanstack/react-query"

export const simulateTradeMutationKey = () =>
  [{ url: "/api/v1/catalog/market/simulate" }] as const

export type SimulateTradeMutationKey = ReturnType<
  typeof simulateTradeMutationKey
>

export function simulateTradeMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig<SimulateTradeMutationRequest>> & {
    client?: Client
  } = {}
) {
  const mutationKey = simulateTradeMutationKey()
  return mutationOptions<
    SimulateTradeMutationResponse,
    ResponseErrorConfig<SimulateTrade422>,
    { data: SimulateTradeMutationRequest },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ data }) => {
      return simulateTrade(data, config)
    },
  })
}

/**
 * @description What a swap would do to the portfolio. Reads only; nothing is traded.
 * @summary Simulate Trade
 * {@link /api/v1/catalog/market/simulate}
 */
export function useSimulateTrade<TContext>(
  options: {
    mutation?: UseMutationOptions<
      SimulateTradeMutationResponse,
      ResponseErrorConfig<SimulateTrade422>,
      { data: SimulateTradeMutationRequest },
      TContext
    > & { client?: QueryClient }
    client?: Partial<RequestConfig<SimulateTradeMutationRequest>> & {
      client?: Client
    }
  } = {}
) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation
  const mutationKey = mutationOptions.mutationKey ?? simulateTradeMutationKey()

  const baseOptions = simulateTradeMutationOptions(
    config
  ) as UseMutationOptions<
    SimulateTradeMutationResponse,
    ResponseErrorConfig<SimulateTrade422>,
    { data: SimulateTradeMutationRequest },
    TContext
  >

  return useMutation<
    SimulateTradeMutationResponse,
    ResponseErrorConfig<SimulateTrade422>,
    { data: SimulateTradeMutationRequest },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient
  ) as UseMutationResult<
    SimulateTradeMutationResponse,
    ResponseErrorConfig<SimulateTrade422>,
    { data: SimulateTradeMutationRequest },
    TContext
  >
}
