/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  SearchSpeciesQueryResponse,
  SearchSpeciesQueryParams,
  SearchSpecies422,
} from "../types/SearchSpecies"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios"
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query"
import { searchSpecies } from "../clients/searchSpecies"
import { queryOptions, useQuery } from "@tanstack/react-query"

export const searchSpeciesQueryKey = (params?: SearchSpeciesQueryParams) =>
  [{ url: "/api/v1/catalog/species" }, ...(params ? [params] : [])] as const

export type SearchSpeciesQueryKey = ReturnType<typeof searchSpeciesQueryKey>

export function searchSpeciesQueryOptions(
  params?: SearchSpeciesQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = searchSpeciesQueryKey(params)
  return queryOptions<
    SearchSpeciesQueryResponse,
    ResponseErrorConfig<SearchSpecies422>,
    SearchSpeciesQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return searchSpecies(params, {
        ...config,
        signal: config.signal ?? signal,
      })
    },
  })
}

/**
 * @summary Search Species
 * {@link /api/v1/catalog/species}
 */
export function useSearchSpecies<
  TData = SearchSpeciesQueryResponse,
  TQueryData = SearchSpeciesQueryResponse,
  TQueryKey extends QueryKey = SearchSpeciesQueryKey,
>(
  params?: SearchSpeciesQueryParams,
  options: {
    query?: Partial<
      QueryObserverOptions<
        SearchSpeciesQueryResponse,
        ResponseErrorConfig<SearchSpecies422>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey = resolvedOptions?.queryKey ?? searchSpeciesQueryKey(params)

  const query = useQuery(
    {
      ...searchSpeciesQueryOptions(params, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient
  ) as UseQueryResult<TData, ResponseErrorConfig<SearchSpecies422>> & {
    queryKey: TQueryKey
  }

  query.queryKey = queryKey as TQueryKey

  return query
}
