/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  SpeciesTriviaQueryResponse,
  SpeciesTriviaPathParams,
  SpeciesTrivia422,
} from "../types/SpeciesTrivia"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios"
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query"
import { speciesTrivia } from "../clients/speciesTrivia"
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query"

export const speciesTriviaSuspenseQueryKey = (
  species_id: SpeciesTriviaPathParams["species_id"] | undefined
) =>
  [
    {
      url: "/api/v1/catalog/species/:species_id/trivia",
      params: { species_id: species_id },
    },
  ] as const

export type SpeciesTriviaSuspenseQueryKey = ReturnType<
  typeof speciesTriviaSuspenseQueryKey
>

export function speciesTriviaSuspenseQueryOptions(
  species_id: SpeciesTriviaPathParams["species_id"],
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = speciesTriviaSuspenseQueryKey(species_id)
  return queryOptions<
    SpeciesTriviaQueryResponse,
    ResponseErrorConfig<SpeciesTrivia422>,
    SpeciesTriviaQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return speciesTrivia(species_id, {
        ...config,
        signal: config.signal ?? signal,
      })
    },
  })
}

/**
 * @description A blurb about the species, generated once and shared by every reader.
 * @summary Species Trivia
 * {@link /api/v1/catalog/species/:species_id/trivia}
 */
export function useSpeciesTriviaSuspense<
  TData = SpeciesTriviaQueryResponse,
  TQueryKey extends QueryKey = SpeciesTriviaSuspenseQueryKey,
>(
  species_id: SpeciesTriviaPathParams["species_id"],
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        SpeciesTriviaQueryResponse,
        ResponseErrorConfig<SpeciesTrivia422>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey =
    resolvedOptions?.queryKey ?? speciesTriviaSuspenseQueryKey(species_id)

  const query = useSuspenseQuery(
    {
      ...speciesTriviaSuspenseQueryOptions(species_id, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as UseSuspenseQueryOptions,
    queryClient
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<SpeciesTrivia422>> & {
    queryKey: TQueryKey
  }

  query.queryKey = queryKey as TQueryKey

  return query
}
