/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  SearchCardsQueryResponse,
  SearchCardsQueryParams,
  SearchCards422,
} from "../types/SearchCards"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios"
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query"
import { searchCards } from "../clients/searchCards"
import { queryOptions, useQuery } from "@tanstack/react-query"

export const searchCardsQueryKey = (params?: SearchCardsQueryParams) =>
  [{ url: "/api/v1/catalog/cards" }, ...(params ? [params] : [])] as const

export type SearchCardsQueryKey = ReturnType<typeof searchCardsQueryKey>

export function searchCardsQueryOptions(
  params?: SearchCardsQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = searchCardsQueryKey(params)
  return queryOptions<
    SearchCardsQueryResponse,
    ResponseErrorConfig<SearchCards422>,
    SearchCardsQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return searchCards(params, { ...config, signal: config.signal ?? signal })
    },
  })
}

/**
 * @summary Search Cards
 * {@link /api/v1/catalog/cards}
 */
export function useSearchCards<
  TData = SearchCardsQueryResponse,
  TQueryData = SearchCardsQueryResponse,
  TQueryKey extends QueryKey = SearchCardsQueryKey,
>(
  params?: SearchCardsQueryParams,
  options: {
    query?: Partial<
      QueryObserverOptions<
        SearchCardsQueryResponse,
        ResponseErrorConfig<SearchCards422>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey = resolvedOptions?.queryKey ?? searchCardsQueryKey(params)

  const query = useQuery(
    {
      ...searchCardsQueryOptions(params, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient
  ) as UseQueryResult<TData, ResponseErrorConfig<SearchCards422>> & {
    queryKey: TQueryKey
  }

  query.queryKey = queryKey as TQueryKey

  return query
}
