/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  SpeciesEvolutionsQueryResponse,
  SpeciesEvolutionsPathParams,
  SpeciesEvolutions422,
} from "../types/SpeciesEvolutions"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios"
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query"
import { speciesEvolutions } from "../clients/speciesEvolutions"
import { queryOptions, useQuery } from "@tanstack/react-query"

export const speciesEvolutionsQueryKey = (
  species_id: SpeciesEvolutionsPathParams["species_id"] | undefined
) =>
  [
    {
      url: "/api/v1/catalog/species/:species_id/evolutions",
      params: { species_id: species_id },
    },
  ] as const

export type SpeciesEvolutionsQueryKey = ReturnType<
  typeof speciesEvolutionsQueryKey
>

export function speciesEvolutionsQueryOptions(
  species_id: SpeciesEvolutionsPathParams["species_id"] | undefined,
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = speciesEvolutionsQueryKey(species_id)
  return queryOptions<
    SpeciesEvolutionsQueryResponse,
    ResponseErrorConfig<SpeciesEvolutions422>,
    SpeciesEvolutionsQueryResponse,
    typeof queryKey
  >({
    enabled: !!species_id,
    queryKey,
    queryFn: async ({ signal }) => {
      return speciesEvolutions(species_id!, {
        ...config,
        signal: config.signal ?? signal,
      })
    },
  })
}

/**
 * @description The evolution family this species belongs to, in dex order.
 * Empty for a species with no family, so the caller renders nothing rather
 * than a panel that only says a Pokemon evolves into no one.
 * @summary Species Evolutions
 * {@link /api/v1/catalog/species/:species_id/evolutions}
 */
export function useSpeciesEvolutions<
  TData = SpeciesEvolutionsQueryResponse,
  TQueryData = SpeciesEvolutionsQueryResponse,
  TQueryKey extends QueryKey = SpeciesEvolutionsQueryKey,
>(
  species_id: SpeciesEvolutionsPathParams["species_id"] | undefined,
  options: {
    query?: Partial<
      QueryObserverOptions<
        SpeciesEvolutionsQueryResponse,
        ResponseErrorConfig<SpeciesEvolutions422>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey =
    resolvedOptions?.queryKey ?? speciesEvolutionsQueryKey(species_id)

  const query = useQuery(
    {
      ...speciesEvolutionsQueryOptions(species_id, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient
  ) as UseQueryResult<TData, ResponseErrorConfig<SpeciesEvolutions422>> & {
    queryKey: TQueryKey
  }

  query.queryKey = queryKey as TQueryKey

  return query
}
