/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  SpeciesEvolutionsQueryResponse,
  SpeciesEvolutionsPathParams,
  SpeciesEvolutions422,
} from "../types/SpeciesEvolutions"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios"
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query"
import { speciesEvolutions } from "../clients/speciesEvolutions"
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query"

export const speciesEvolutionsSuspenseQueryKey = (
  species_id: SpeciesEvolutionsPathParams["species_id"] | undefined
) =>
  [
    {
      url: "/api/v1/catalog/species/:species_id/evolutions",
      params: { species_id: species_id },
    },
  ] as const

export type SpeciesEvolutionsSuspenseQueryKey = ReturnType<
  typeof speciesEvolutionsSuspenseQueryKey
>

export function speciesEvolutionsSuspenseQueryOptions(
  species_id: SpeciesEvolutionsPathParams["species_id"],
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = speciesEvolutionsSuspenseQueryKey(species_id)
  return queryOptions<
    SpeciesEvolutionsQueryResponse,
    ResponseErrorConfig<SpeciesEvolutions422>,
    SpeciesEvolutionsQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return speciesEvolutions(species_id, {
        ...config,
        signal: config.signal ?? signal,
      })
    },
  })
}

/**
 * @description The evolution family this species belongs to, in dex order.
 * Empty for a species with no family, so the caller renders nothing rather
 * than a panel that only says a Pokemon evolves into no one.
 * @summary Species Evolutions
 * {@link /api/v1/catalog/species/:species_id/evolutions}
 */
export function useSpeciesEvolutionsSuspense<
  TData = SpeciesEvolutionsQueryResponse,
  TQueryKey extends QueryKey = SpeciesEvolutionsSuspenseQueryKey,
>(
  species_id: SpeciesEvolutionsPathParams["species_id"],
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        SpeciesEvolutionsQueryResponse,
        ResponseErrorConfig<SpeciesEvolutions422>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey =
    resolvedOptions?.queryKey ?? speciesEvolutionsSuspenseQueryKey(species_id)

  const query = useSuspenseQuery(
    {
      ...speciesEvolutionsSuspenseQueryOptions(species_id, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as UseSuspenseQueryOptions,
    queryClient
  ) as UseSuspenseQueryResult<
    TData,
    ResponseErrorConfig<SpeciesEvolutions422>
  > & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}
