/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  UpdateItemMutationRequest,
  UpdateItemMutationResponse,
  UpdateItemPathParams,
  UpdateItem422,
} from "../types/UpdateItem"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios"
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query"
import { updateItem } from "../clients/updateItem"
import { mutationOptions, useMutation } from "@tanstack/react-query"

export const updateItemMutationKey = () =>
  [{ url: "/api/v1/collection/:item_id" }] as const

export type UpdateItemMutationKey = ReturnType<typeof updateItemMutationKey>

export function updateItemMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig<UpdateItemMutationRequest>> & {
    client?: Client
  } = {}
) {
  const mutationKey = updateItemMutationKey()
  return mutationOptions<
    UpdateItemMutationResponse,
    ResponseErrorConfig<UpdateItem422>,
    {
      item_id: UpdateItemPathParams["item_id"]
      data: UpdateItemMutationRequest
    },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ item_id, data }) => {
      return updateItem(item_id, data, config)
    },
  })
}

/**
 * @summary Update Item
 * {@link /api/v1/collection/:item_id}
 */
export function useUpdateItem<TContext>(
  options: {
    mutation?: UseMutationOptions<
      UpdateItemMutationResponse,
      ResponseErrorConfig<UpdateItem422>,
      {
        item_id: UpdateItemPathParams["item_id"]
        data: UpdateItemMutationRequest
      },
      TContext
    > & { client?: QueryClient }
    client?: Partial<RequestConfig<UpdateItemMutationRequest>> & {
      client?: Client
    }
  } = {}
) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation
  const mutationKey = mutationOptions.mutationKey ?? updateItemMutationKey()

  const baseOptions = updateItemMutationOptions(config) as UseMutationOptions<
    UpdateItemMutationResponse,
    ResponseErrorConfig<UpdateItem422>,
    {
      item_id: UpdateItemPathParams["item_id"]
      data: UpdateItemMutationRequest
    },
    TContext
  >

  return useMutation<
    UpdateItemMutationResponse,
    ResponseErrorConfig<UpdateItem422>,
    {
      item_id: UpdateItemPathParams["item_id"]
      data: UpdateItemMutationRequest
    },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient
  ) as UseMutationResult<
    UpdateItemMutationResponse,
    ResponseErrorConfig<UpdateItem422>,
    {
      item_id: UpdateItemPathParams["item_id"]
      data: UpdateItemMutationRequest
    },
    TContext
  >
}
