/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  WithdrawOfferMutationResponse,
  WithdrawOfferPathParams,
  WithdrawOffer422,
} from "../types/WithdrawOffer"
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios"
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query"
import { withdrawOffer } from "../clients/withdrawOffer"
import { mutationOptions, useMutation } from "@tanstack/react-query"

export const withdrawOfferMutationKey = () =>
  [{ url: "/api/v1/trades/offers/:offer_id/withdraw" }] as const

export type WithdrawOfferMutationKey = ReturnType<
  typeof withdrawOfferMutationKey
>

export function withdrawOfferMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const mutationKey = withdrawOfferMutationKey()
  return mutationOptions<
    WithdrawOfferMutationResponse,
    ResponseErrorConfig<WithdrawOffer422>,
    { offer_id: WithdrawOfferPathParams["offer_id"] },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ offer_id }) => {
      return withdrawOffer(offer_id, config)
    },
  })
}

/**
 * @description Pull back an offer. Only its author, and only while it is unanswered.
 * @summary Withdraw Offer
 * {@link /api/v1/trades/offers/:offer_id/withdraw}
 */
export function useWithdrawOffer<TContext>(
  options: {
    mutation?: UseMutationOptions<
      WithdrawOfferMutationResponse,
      ResponseErrorConfig<WithdrawOffer422>,
      { offer_id: WithdrawOfferPathParams["offer_id"] },
      TContext
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {}
) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation
  const mutationKey = mutationOptions.mutationKey ?? withdrawOfferMutationKey()

  const baseOptions = withdrawOfferMutationOptions(
    config
  ) as UseMutationOptions<
    WithdrawOfferMutationResponse,
    ResponseErrorConfig<WithdrawOffer422>,
    { offer_id: WithdrawOfferPathParams["offer_id"] },
    TContext
  >

  return useMutation<
    WithdrawOfferMutationResponse,
    ResponseErrorConfig<WithdrawOffer422>,
    { offer_id: WithdrawOfferPathParams["offer_id"] },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient
  ) as UseMutationResult<
    WithdrawOfferMutationResponse,
    ResponseErrorConfig<WithdrawOffer422>,
    { offer_id: WithdrawOfferPathParams["offer_id"] },
    TContext
  >
}
