/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4"

/**
 * @description One thing that happened, flattened from the tables that record it.
 */
export const activityEntrySchema = z
  .object({
    kind: z.enum(["added", "scanned", "suggested"]),
    at: z.iso.datetime(),
    card_id: z.union([z.string(), z.null()]),
    card_name: z.union([z.string(), z.null()]),
    image_url: z.union([z.string(), z.null()]),
    quantity: z.union([z.int(), z.null()]),
    value_usd: z.union([z.number(), z.null()]),
    detail: z.union([z.string(), z.null()]),
  })
  .describe(
    "One thing that happened, flattened from the tables that record it."
  )
