/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { cardConditionSchema } from "./cardConditionSchema"
import { z } from "zod/v4"

export const addCardRequestSchema = z.object({
  card_id: z.string(),
  get condition() {
    return cardConditionSchema.default("near_mint").optional()
  },
  quantity: z.optional(z.int().min(1).default(1)),
  language: z.optional(z.string().max(8).default("en")),
  is_graded: z.optional(z.boolean().default(false)),
  grade: z.optional(z.union([z.number(), z.null()])),
  notes: z.optional(z.union([z.string(), z.null()])),
  unit_cost_usd: z.optional(
    z.union([
      z.number(),
      z
        .string()
        .regex(
          /^(?!^[-+.]*$)[+-]?0*(?:\d{0,8}|(?=[\d.]{1,11}0*$)\d{0,8}\.\d{0,2}0*$)/
        ),
      z.null(),
    ])
  ),
})
