/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { HTTPValidationErrorSchema } from "./HTTPValidationErrorSchema"
import { addCardRequestSchema } from "./addCardRequestSchema"
import { collectionItemViewSchema } from "./collectionItemViewSchema"
import { z } from "zod/v4"

/**
 * @description Successful Response
 */
export const addCard201Schema = z.lazy(() => collectionItemViewSchema)

/**
 * @description Validation Error
 */
export const addCard422Schema = z.lazy(() => HTTPValidationErrorSchema)

export const addCardMutationRequestSchema = z.lazy(() => addCardRequestSchema)

export const addCardMutationResponseSchema = z.lazy(() => addCard201Schema)
