/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { HTTPValidationErrorSchema } from "./HTTPValidationErrorSchema"
import { addWishlistRequestSchema } from "./addWishlistRequestSchema"
import { wishlistItemViewSchema } from "./wishlistItemViewSchema"
import { z } from "zod/v4"

/**
 * @description Successful Response
 */
export const addToWishlist201Schema = z.lazy(() => wishlistItemViewSchema)

/**
 * @description Validation Error
 */
export const addToWishlist422Schema = z.lazy(() => HTTPValidationErrorSchema)

export const addToWishlistMutationRequestSchema = z.lazy(
  () => addWishlistRequestSchema
)

export const addToWishlistMutationResponseSchema = z.lazy(
  () => addToWishlist201Schema
)
