/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4"

export const addWishlistRequestSchema = z.object({
  card_id: z.string(),
  reason: z.optional(z.union([z.string(), z.null()])),
  priority: z.optional(z.int().min(0).max(3).default(0)),
})
