/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { HTTPValidationErrorSchema } from "./HTTPValidationErrorSchema"
import { priceChangeSchema } from "./priceChangeSchema"
import { z } from "zod/v4"

/**
 * @description Where one card sits in its set: what it is worth relative to the rest, and\nhow much of that set the reader already holds.
 */
export const cardMarketContextSchema = z
  .object({
    price_rank: z.union([z.int(), z.null()]),
    priced_in_set: z.int(),
    cards_in_set: z.int(),
    owned_in_set: z.int(),
    set_value: z.string().regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/),
    owned: z.int(),
    item_id: z.union([z.uuid(), z.null()]),
    get change() {
      return z.union([priceChangeSchema, z.null()]).optional()
    },
  })
  .describe(
    "Where one card sits in its set: what it is worth relative to the rest, and\nhow much of that set the reader already holds."
  )

export const cardMarketContextPathParamsSchema = z.object({
  card_id: z.string(),
})

/**
 * @description Successful Response
 */
export const cardMarketContext200Schema = z
  .lazy(() => cardMarketContextSchema)
  .describe(
    "Where one card sits in its set: what it is worth relative to the rest, and\nhow much of that set the reader already holds."
  )

/**
 * @description Validation Error
 */
export const cardMarketContext422Schema = z.lazy(
  () => HTTPValidationErrorSchema
)

export const cardMarketContextQueryResponseSchema = z.lazy(
  () => cardMarketContext200Schema
)
