/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4"

/**
 * @description What is PRINTED on the card. It does not identify: it transcribes.\n\nMerging transcription and identification is what makes these features\nhallucinate a card that fits what the model thinks it saw.
 */
export const cardReadingSchema = z
  .object({
    name: z.optional(z.union([z.string(), z.null()])),
    collector_number: z.optional(z.union([z.string(), z.null()])),
    set_total: z.optional(z.union([z.int(), z.null()])),
    set_symbol_text: z.optional(z.union([z.string(), z.null()])),
    hp: z.optional(z.union([z.int(), z.null()])),
    rarity_symbol: z.optional(
      z.union([z.enum(["circle", "diamond", "star", "none"]), z.null()])
    ),
    variant_hints: z.optional(z.array(z.string())),
    confidence: z.optional(z.enum(["high", "medium", "low"]).default("low")),
  })
  .describe(
    "What is PRINTED on the card. It does not identify: it transcribes.\n\nMerging transcription and identification is what makes these features\nhallucinate a card that fits what the model thinks it saw."
  )
