/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4"

export const cardSetViewSchema = z.object({
  id: z.string(),
  name: z.string(),
  series: z.union([z.string(), z.null()]),
  printed_total: z.int(),
  release_date: z.union([z.iso.date(), z.null()]),
  logo_url: z.union([z.string(), z.null()]),
})
