/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4"

export const chatRequestSchema = z.object({
  message: z.string().min(1).max(2000),
  conversation_id: z.optional(z.union([z.uuid(), z.null()])),
})
