/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4"

/**
 * @description Another collector, described only by what could move between you.\n\nTheir collection stays theirs: what is published is how much is spare and\nhow much of it either of you is short of.
 */
export const collectorViewSchema = z
  .object({
    user_id: z.string(),
    name: z.union([z.string(), z.null()]),
    spares: z.int(),
    you_want: z.int(),
    they_want: z.int(),
  })
  .describe(
    "Another collector, described only by what could move between you.\n\nTheir collection stays theirs: what is published is how much is spare and\nhow much of it either of you is short of."
  )
