/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { activityEntrySchema } from "./activityEntrySchema"
import { z } from "zod/v4"

/**
 * @description Successful Response
 */
export const collectionActivity200Schema = z.array(
  z
    .lazy(() => activityEntrySchema)
    .describe(
      "One thing that happened, flattened from the tables that record it."
    )
)

export const collectionActivityQueryResponseSchema = z.lazy(
  () => collectionActivity200Schema
)
