/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { cardConditionSchema } from "./cardConditionSchema"
import { cardViewSchema } from "./cardViewSchema"
import { z } from "zod/v4"

export const collectionItemViewSchema = z.object({
  id: z.uuid(),
  quantity: z.int(),
  get condition() {
    return cardConditionSchema
  },
  language: z.string(),
  is_graded: z.boolean(),
  grade: z.union([z.number(), z.null()]),
  notes: z.union([z.string(), z.null()]),
  acquired_at: z.union([z.iso.date(), z.null()]),
  created_at: z.iso.datetime(),
  get card() {
    return cardViewSchema.describe(
      "A card with both layers: what is printed, and the species it depicts."
    )
  },
})
