/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4"

/**
 * @description What the collection is worth, and how much of it could be priced.\n\nThe coverage travels with the total because most cards have no market price;\na figure without it would read as complete when it is not.
 */
export const collectionValueSchema = z
  .object({
    total_eur: z.string().regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/),
    priced_cards: z.int(),
    unpriced_cards: z.int(),
  })
  .describe(
    "What the collection is worth, and how much of it could be priced.\n\nThe coverage travels with the total because most cards have no market price;\na figure without it would read as complete when it is not."
  )
