/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { generationCountSchema } from "./generationCountSchema"
import { setCoverageSchema } from "./setCoverageSchema"
import { typeCountSchema } from "./typeCountSchema"
import { z } from "zod/v4"

export const collectionStatsSchema = z.object({
  total_groups: z.int(),
  total_cards: z.int(),
  get types() {
    return z.array(typeCountSchema)
  },
  get generations() {
    return z.array(generationCountSchema)
  },
  get sets() {
    return z.array(setCoverageSchema)
  },
})

/**
 * @description Successful Response
 */
export const collectionStats200Schema = z.lazy(() => collectionStatsSchema)

export const collectionStatsQueryResponseSchema = z.lazy(
  () => collectionStats200Schema
)
