/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { profileSetSchema } from "./profileSetSchema"
import { z } from "zod/v4"

/**
 * @description A collector as another collector may see them.\n\nDeliberately not a portfolio: what a collection is worth is a claim about a\nperson, and it stays with them. What is published is what could move — how\nmuch is spare, what each of you is short of — plus the shape of what they\ncollect, which is what tells you whether it is worth talking to them.
 */
export const collectorProfileSchema = z
  .object({
    user_id: z.string(),
    name: z.union([z.string(), z.null()]),
    is_self: z.boolean(),
    joined_at: z.union([z.iso.datetime(), z.null()]),
    cards: z.int(),
    distinct_cards: z.int(),
    spares: z.int(),
    wants: z.int(),
    you_want: z.int(),
    they_want: z.int(),
    get sets() {
      return z.array(profileSetSchema)
    },
  })
  .describe(
    "A collector as another collector may see them.\n\nDeliberately not a portfolio: what a collection is worth is a claim about a\nperson, and it stays with them. What is published is what could move — how\nmuch is spare, what each of you is short of — plus the shape of what they\ncollect, which is what tells you whether it is worth talking to them."
  )
