/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { HTTPValidationErrorSchema } from "./HTTPValidationErrorSchema"
import { visualComparisonSchema } from "./visualComparisonSchema"
import { z } from "zod/v4"

export const compareCardsQueryParamsSchema = z.object({
  a: z.string(),
  b: z.string(),
})

/**
 * @description Successful Response
 */
export const compareCards200Schema = z
  .lazy(() => visualComparisonSchema)
  .describe("What the model saw, kept short enough to read beside the cards.")

/**
 * @description Validation Error
 */
export const compareCards422Schema = z.lazy(() => HTTPValidationErrorSchema)

export const compareCardsQueryResponseSchema = z.lazy(
  () => compareCards200Schema
)
