/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4"

/**
 * @description What the largest `cards` positions add up to.
 */
export const concentrationBucketSchema = z
  .object({
    cards: z.int(),
    value: z.string().regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/),
    share: z.number(),
  })
  .describe("What the largest `cards` positions add up to.")
