/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { cardConditionSchema } from "./cardConditionSchema"
import { z } from "zod/v4"

export const conditionCountSchema = z.object({
  get condition() {
    return cardConditionSchema
  },
  copies: z.int(),
})
