/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { HTTPValidationErrorSchema } from "./HTTPValidationErrorSchema"
import { createOfferRequestSchema } from "./createOfferRequestSchema"
import { tradeOfferViewSchema } from "./tradeOfferViewSchema"
import { z } from "zod/v4"

export const counterOfferPathParamsSchema = z.object({
  offer_id: z.uuid(),
})

/**
 * @description Successful Response
 */
export const counterOffer201Schema = z
  .lazy(() => tradeOfferViewSchema)
  .describe(
    "An offer told from the reader's side.\n\n`you_give` and `you_get` swap meaning depending on who is looking, so the\nservice resolves them per reader rather than storing them that way."
  )

/**
 * @description Validation Error
 */
export const counterOffer422Schema = z.lazy(() => HTTPValidationErrorSchema)

export const counterOfferMutationRequestSchema = z.lazy(
  () => createOfferRequestSchema
)

export const counterOfferMutationResponseSchema = z.lazy(
  () => counterOffer201Schema
)
