/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { offerCardInputSchema } from "./offerCardInputSchema"
import { z } from "zod/v4"

/**
 * @description Wanted cards are ids alone: a state can only be promised by whoever holds\nthe card, and on this side nobody holds it yet.
 */
export const createListingRequestSchema = z
  .object({
    get give() {
      return z
        .array(
          offerCardInputSchema.describe(
            "A card put on the table, in a state.\n\nLeaving the condition out lets the service pick the worst copy its owner\nholds, which is the one a collector parts with."
          )
        )
        .min(1)
    },
    want: z.array(z.string()).min(1),
    note: z.optional(z.union([z.string(), z.null()])),
  })
  .describe(
    "Wanted cards are ids alone: a state can only be promised by whoever holds\nthe card, and on this side nobody holds it yet."
  )
