/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { HTTPValidationErrorSchema } from "./HTTPValidationErrorSchema"
import { createOfferRequestSchema } from "./createOfferRequestSchema"
import { tradeOfferViewSchema } from "./tradeOfferViewSchema"
import { z } from "zod/v4"

/**
 * @description Successful Response
 */
export const createOffer201Schema = z
  .lazy(() => tradeOfferViewSchema)
  .describe(
    "An offer told from the reader's side.\n\n`you_give` and `you_get` swap meaning depending on who is looking, so the\nservice resolves them per reader rather than storing them that way."
  )

/**
 * @description Validation Error
 */
export const createOffer422Schema = z.lazy(() => HTTPValidationErrorSchema)

export const createOfferMutationRequestSchema = z.lazy(
  () => createOfferRequestSchema
)

export const createOfferMutationResponseSchema = z.lazy(
  () => createOffer201Schema
)
