/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4"

export const createOfferRequestSchema = z.object({
  to_user_id: z.string(),
  offered: z.array(z.string()).min(1),
  requested: z.array(z.string()).min(1),
  message: z.optional(z.union([z.string(), z.null()])),
})
