/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { HTTPValidationErrorSchema } from "./HTTPValidationErrorSchema"
import { bodyCreateScanSchema } from "./bodyCreateScanSchema"
import { scanResultSchema } from "./scanResultSchema"
import { z } from "zod/v4"

/**
 * @description Successful Response
 */
export const createScan201Schema = z.lazy(() => scanResultSchema)

/**
 * @description Validation Error
 */
export const createScan422Schema = z.lazy(() => HTTPValidationErrorSchema)

export const createScanMutationRequestSchema = z.lazy(
  () => bodyCreateScanSchema
)

export const createScanMutationResponseSchema = z.lazy(
  () => createScan201Schema
)
