/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4"

/**
 * @description One message, told from the reader\'s side.\n\n`mine` is resolved per reader rather than stored: the same row is on the\nleft for one of the two and on the right for the other.
 */
export const directMessageViewSchema = z
  .object({
    id: z.uuid(),
    thread_id: z.uuid(),
    sender_id: z.string(),
    mine: z.boolean(),
    body: z.string(),
    created_at: z.iso.datetime(),
    read_at: z.union([z.iso.datetime(), z.null()]),
  })
  .describe(
    "One message, told from the reader's side.\n\n`mine` is resolved per reader rather than stored: the same row is on the\nleft for one of the two and on the right for the other."
  )
