/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4"

/**
 * @description One species of an evolution family, as its own Pokedex entry.
 */
export const evolutionMemberViewSchema = z
  .object({
    id: z.int(),
    name: z.string(),
    types: z.array(z.string()),
    sprite_url: z.union([z.string(), z.null()]),
    owned: z.boolean(),
    is_current: z.boolean(),
  })
  .describe("One species of an evolution family, as its own Pokedex entry.")
