/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { HTTPValidationErrorSchema } from "./HTTPValidationErrorSchema"
import { z } from "zod/v4"

export const exportCollectionQueryParamsSchema = z.object({
  format: z.enum(["csv", "json"]).default("csv"),
})

/**
 * @description Successful Response
 */
export const exportCollection200Schema = z.any()

/**
 * @description Validation Error
 */
export const exportCollection422Schema = z.lazy(() => HTTPValidationErrorSchema)

export const exportCollectionQueryResponseSchema = z.lazy(
  () => exportCollection200Schema
)
