/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { HTTPValidationErrorSchema } from "./HTTPValidationErrorSchema"
import { conversationDetailSchema } from "./conversationDetailSchema"
import { z } from "zod/v4"

export const getConversationPathParamsSchema = z.object({
  conversation_id: z.uuid(),
})

/**
 * @description Successful Response
 */
export const getConversation200Schema = z.lazy(() => conversationDetailSchema)

/**
 * @description Validation Error
 */
export const getConversation422Schema = z.lazy(() => HTTPValidationErrorSchema)

export const getConversationQueryResponseSchema = z.lazy(
  () => getConversation200Schema
)
