/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { HTTPValidationErrorSchema } from "./HTTPValidationErrorSchema"
import { collectorProfileSchema } from "./collectorProfileSchema"
import { z } from "zod/v4"

export const getCollectorPathParamsSchema = z.object({
  owner_id: z.string(),
})

/**
 * @description Successful Response
 */
export const getCollector200Schema = z
  .lazy(() => collectorProfileSchema)
  .describe(
    "A collector as another collector may see them.\n\nDeliberately not a portfolio: what a collection is worth is a claim about a\nperson, and it stays with them. What is published is what could move — how\nmuch is spare, what each of you is short of — plus the shape of what they\ncollect, which is what tells you whether it is worth talking to them."
  )

/**
 * @description Validation Error
 */
export const getCollector422Schema = z.lazy(() => HTTPValidationErrorSchema)

export const getCollectorQueryResponseSchema = z.lazy(
  () => getCollector200Schema
)
