/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { HTTPValidationErrorSchema } from "./HTTPValidationErrorSchema"
import { collectionItemViewSchema } from "./collectionItemViewSchema"
import { z } from "zod/v4"

export const getItemPathParamsSchema = z.object({
  item_id: z.uuid(),
})

/**
 * @description Successful Response
 */
export const getItem200Schema = z.lazy(() => collectionItemViewSchema)

/**
 * @description Validation Error
 */
export const getItem422Schema = z.lazy(() => HTTPValidationErrorSchema)

export const getItemQueryResponseSchema = z.lazy(() => getItem200Schema)
