/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { HTTPValidationErrorSchema } from "./HTTPValidationErrorSchema"
import { z } from "zod/v4"

export const getScanImagePathParamsSchema = z.object({
  scan_id: z.uuid(),
})

/**
 * @description Successful Response
 */
export const getScanImage200Schema = z.any()

/**
 * @description Validation Error
 */
export const getScanImage422Schema = z.lazy(() => HTTPValidationErrorSchema)

export const getScanImageQueryResponseSchema = z.lazy(
  () => getScanImage200Schema
)
