/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { shareLinkViewSchema } from "./shareLinkViewSchema"
import { z } from "zod/v4"

/**
 * @description Successful Response
 */
export const getShareLink200Schema = z.union([
  z.lazy(() => shareLinkViewSchema),
  z.null(),
])

export const getShareLinkQueryResponseSchema = z.lazy(
  () => getShareLink200Schema
)
