/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { HTTPValidationErrorSchema } from "./HTTPValidationErrorSchema"
import { threadViewSchema } from "./threadViewSchema"
import { z } from "zod/v4"

export const getThreadWithPathParamsSchema = z.object({
  partner_id: z.string(),
})

/**
 * @description Successful Response
 */
export const getThreadWith200Schema = z
  .lazy(() => threadViewSchema)
  .describe(
    'A conversation as one of its two participants sees it.\n\n`id` is null for a conversation nobody has started. The partner is the\naddress, not the thread, so a collector can be opened and written to before\nany row exists — which is what keeps an abandoned "Mensaje" click from\nleaving an empty thread in everyone\'s list.'
  )

/**
 * @description Validation Error
 */
export const getThreadWith422Schema = z.lazy(() => HTTPValidationErrorSchema)

export const getThreadWithQueryResponseSchema = z.lazy(
  () => getThreadWith200Schema
)
