/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4"

/**
 * @description Successful Response
 */
export const health200Schema = z.object({}).catchall(z.string())

export const healthQueryResponseSchema = z.lazy(() => health200Schema)
