/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { HTTPValidationErrorSchema } from "./HTTPValidationErrorSchema"
import { listingStatusSchema } from "./listingStatusSchema"
import { pageTradeListingViewSchema } from "./pageTradeListingViewSchema"
import { z } from "zod/v4"

export const listListingsQueryParamsSchema = z.object({
  search: z.optional(z.union([z.string(), z.null()])),
  fulfillable: z.optional(z.union([z.boolean(), z.null()])),
  mine: z.optional(z.union([z.boolean(), z.null()])),
  get status_filter() {
    return listingStatusSchema.default("open")
  },
  limit: z.coerce.number().int().min(1).max(50).default(6),
  offset: z.coerce.number().int().min(0).default(0),
})

/**
 * @description Successful Response
 */
export const listListings200Schema = z.lazy(() => pageTradeListingViewSchema)

/**
 * @description Validation Error
 */
export const listListings422Schema = z.lazy(() => HTTPValidationErrorSchema)

export const listListingsQueryResponseSchema = z.lazy(
  () => listListings200Schema
)
