/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { HTTPValidationErrorSchema } from "./HTTPValidationErrorSchema"
import { cardConditionSchema } from "./cardConditionSchema"
import { pageCollectionItemViewSchema } from "./pageCollectionItemViewSchema"
import { z } from "zod/v4"

export const listCollectionQueryParamsSchema = z.object({
  type: z.optional(z.union([z.string(), z.null()])),
  generation: z.optional(z.union([z.coerce.number().int(), z.null()])),
  set_id: z.optional(z.union([z.string(), z.null()])),
  get condition() {
    return z.union([cardConditionSchema, z.null()]).optional()
  },
  search: z.optional(z.union([z.string(), z.null()])),
  limit: z.coerce.number().int().min(1).max(200).default(50),
  offset: z.coerce.number().int().min(0).default(0),
})

/**
 * @description Successful Response
 */
export const listCollection200Schema = z.lazy(
  () => pageCollectionItemViewSchema
)

/**
 * @description Validation Error
 */
export const listCollection422Schema = z.lazy(() => HTTPValidationErrorSchema)

export const listCollectionQueryResponseSchema = z.lazy(
  () => listCollection200Schema
)
