/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { HTTPValidationErrorSchema } from "./HTTPValidationErrorSchema"
import { pageTradeMatchSchema } from "./pageTradeMatchSchema"
import { z } from "zod/v4"

export const listTradesQueryParamsSchema = z.object({
  search: z.optional(z.union([z.string(), z.null()])),
  favourable: z.optional(z.union([z.boolean(), z.null()])),
  limit: z.coerce.number().int().min(1).max(50).default(10),
  offset: z.coerce.number().int().min(0).default(0),
})

/**
 * @description Successful Response
 */
export const listTrades200Schema = z.lazy(() => pageTradeMatchSchema)

/**
 * @description Validation Error
 */
export const listTrades422Schema = z.lazy(() => HTTPValidationErrorSchema)

export const listTradesQueryResponseSchema = z.lazy(() => listTrades200Schema)
