/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { HTTPValidationErrorSchema } from "./HTTPValidationErrorSchema"
import { offerStatusSchema } from "./offerStatusSchema"
import { pageTradeOfferViewSchema } from "./pageTradeOfferViewSchema"
import { z } from "zod/v4"

export const listOffersQueryParamsSchema = z.object({
  get status_filter() {
    return z.union([offerStatusSchema, z.null()]).optional()
  },
  direction: z.optional(z.union([z.enum(["sent", "received"]), z.null()])),
  limit: z.coerce.number().int().min(1).max(50).default(10),
  offset: z.coerce.number().int().min(0).default(0),
})

/**
 * @description Successful Response
 */
export const listOffers200Schema = z.lazy(() => pageTradeOfferViewSchema)

/**
 * @description Validation Error
 */
export const listOffers422Schema = z.lazy(() => HTTPValidationErrorSchema)

export const listOffersQueryResponseSchema = z.lazy(() => listOffers200Schema)
