/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { HTTPValidationErrorSchema } from "./HTTPValidationErrorSchema"
import { setGapSchema } from "./setGapSchema"
import { z } from "zod/v4"

export const listGapsQueryParamsSchema = z.object({
  set_id: z.optional(z.union([z.string(), z.null()])),
  limit: z.coerce.number().int().default(20),
})

/**
 * @description Successful Response
 */
export const listGaps200Schema = z.array(z.lazy(() => setGapSchema))

/**
 * @description Validation Error
 */
export const listGaps422Schema = z.lazy(() => HTTPValidationErrorSchema)

export const listGapsQueryResponseSchema = z.lazy(() => listGaps200Schema)
