/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { cardConditionSchema } from "./cardConditionSchema"
import { cardViewSchema } from "./cardViewSchema"
import { z } from "zod/v4"

/**
 * @description A card named on a listing.\n\n`condition` is null on the wanted side, and so is `adjusted_usd` with it:\nnobody has said yet which copy would arrive, so the market price is the only\nhonest figure there.
 */
export const listingCardViewSchema = z
  .object({
    get card() {
      return cardViewSchema.describe(
        "A card with both layers: what is printed, and the species it depicts."
      )
    },
    get condition() {
      return z.union([cardConditionSchema, z.null()])
    },
    price_usd: z.union([
      z.string().regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/),
      z.null(),
    ]),
    adjusted_usd: z.union([
      z.string().regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/),
      z.null(),
    ]),
  })
  .describe(
    "A card named on a listing.\n\n`condition` is null on the wanted side, and so is `adjusted_usd` with it:\nnobody has said yet which copy would arrive, so the market price is the only\nhonest figure there."
  )
