/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { HTTPValidationErrorSchema } from "./HTTPValidationErrorSchema"
import { offerStatusSchema } from "./offerStatusSchema"
import { tradeOfferViewSchema } from "./tradeOfferViewSchema"
import { z } from "zod/v4"

export const listOffersQueryParamsSchema = z
  .object({
    get status_filter() {
      return z.union([offerStatusSchema, z.null()]).optional()
    },
  })
  .optional()

/**
 * @description Successful Response
 */
export const listOffers200Schema = z.array(
  z
    .lazy(() => tradeOfferViewSchema)
    .describe(
      "An offer told from the reader's side.\n\n`you_give` and `you_get` swap meaning depending on who is looking, so the\nservice resolves them per reader rather than storing them that way."
    )
)

/**
 * @description Validation Error
 */
export const listOffers422Schema = z.lazy(() => HTTPValidationErrorSchema)

export const listOffersQueryResponseSchema = z.lazy(() => listOffers200Schema)
