/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { conversationViewSchema } from "./conversationViewSchema"
import { z } from "zod/v4"

/**
 * @description Successful Response
 */
export const listConversations200Schema = z.array(
  z.lazy(() => conversationViewSchema)
)

export const listConversationsQueryResponseSchema = z.lazy(
  () => listConversations200Schema
)
