/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { HTTPValidationErrorSchema } from "./HTTPValidationErrorSchema"
import { pageThreadViewSchema } from "./pageThreadViewSchema"
import { z } from "zod/v4"

export const listThreadsQueryParamsSchema = z.object({
  search: z.optional(z.union([z.string(), z.null()])),
  limit: z.coerce.number().int().min(1).max(50).default(12),
  offset: z.coerce.number().int().min(0).default(0),
})

/**
 * @description Successful Response
 */
export const listThreads200Schema = z.lazy(() => pageThreadViewSchema)

/**
 * @description Validation Error
 */
export const listThreads422Schema = z.lazy(() => HTTPValidationErrorSchema)

export const listThreadsQueryResponseSchema = z.lazy(() => listThreads200Schema)
