/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { HTTPValidationErrorSchema } from "./HTTPValidationErrorSchema"
import { pageDirectMessageViewSchema } from "./pageDirectMessageViewSchema"
import { z } from "zod/v4"

export const listThreadMessagesPathParamsSchema = z.object({
  thread_id: z.uuid(),
})

export const listThreadMessagesQueryParamsSchema = z.object({
  limit: z.coerce.number().int().min(1).max(100).default(30),
  offset: z.coerce.number().int().min(0).default(0),
})

/**
 * @description Successful Response
 */
export const listThreadMessages200Schema = z.lazy(
  () => pageDirectMessageViewSchema
)

/**
 * @description Validation Error
 */
export const listThreadMessages422Schema = z.lazy(
  () => HTTPValidationErrorSchema
)

export const listThreadMessagesQueryResponseSchema = z.lazy(
  () => listThreadMessages200Schema
)
