/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { setMarketViewSchema } from "./setMarketViewSchema"
import { z } from "zod/v4"

/**
 * @description Successful Response
 */
export const marketSets200Schema = z.array(
  z
    .lazy(() => setMarketViewSchema)
    .describe(
      "One set as a position: how much of it is held, and what finishing costs."
    )
)

export const marketSetsQueryResponseSchema = z.lazy(() => marketSets200Schema)
