/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { HTTPValidationErrorSchema } from "./HTTPValidationErrorSchema"
import { pagePositionViewSchema } from "./pagePositionViewSchema"
import { z } from "zod/v4"

export const marketPositionsQueryParamsSchema = z.object({
  sort: z
    .enum(["value", "gain", "gain_percent", "cost", "quantity", "name"])
    .default("value"),
  direction: z.enum(["asc", "desc"]).default("desc"),
  limit: z.coerce.number().int().min(1).max(100).default(20),
  offset: z.coerce.number().int().min(0).default(0),
})

/**
 * @description Successful Response
 */
export const marketPositions200Schema = z.lazy(() => pagePositionViewSchema)

/**
 * @description Validation Error
 */
export const marketPositions422Schema = z.lazy(() => HTTPValidationErrorSchema)

export const marketPositionsQueryResponseSchema = z.lazy(
  () => marketPositions200Schema
)
