/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { marketTypeCountSchema } from "./marketTypeCountSchema"
import { priceChangeSchema } from "./priceChangeSchema"
import { z } from "zod/v4"

export const marketSummarySchema = z.object({
  total_cards: z.int(),
  owned_cards: z.int(),
  catalog_value: z.string().regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/),
  owned_value: z.string().regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/),
  missing_value: z.string().regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/),
  get types() {
    return z.array(
      marketTypeCountSchema.describe(
        "How many catalog cards carry a type, and how many of those are held."
      )
    )
  },
  get change() {
    return z.union([priceChangeSchema, z.null()]).optional()
  },
})

/**
 * @description Successful Response
 */
export const marketSummary200Schema = z.lazy(() => marketSummarySchema)

export const marketSummaryQueryResponseSchema = z.lazy(
  () => marketSummary200Schema
)
