/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4";

/**
 * @description Successful Response
 */
export const markNewsSeen204Schema = z.any();

export const markNewsSeenMutationResponseSchema = z.lazy(
  () => markNewsSeen204Schema,
);
