/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { HTTPValidationErrorSchema } from "./HTTPValidationErrorSchema"
import { pageMarketCardViewSchema } from "./pageMarketCardViewSchema"
import { z } from "zod/v4"

export const marketCardsQueryParamsSchema = z.object({
  type: z.optional(z.union([z.string(), z.null()])),
  generation: z.optional(z.union([z.coerce.number().int(), z.null()])),
  set_id: z.optional(z.union([z.string(), z.null()])),
  search: z.optional(z.union([z.string(), z.null()])),
  owned: z.enum(["all", "owned", "missing"]).default("all"),
  sort: z.enum(["number", "name", "price", "owned"]).default("number"),
  limit: z.coerce.number().int().min(1).max(200).default(50),
  offset: z.coerce.number().int().min(0).default(0),
})

/**
 * @description Successful Response
 */
export const marketCards200Schema = z.lazy(() => pageMarketCardViewSchema)

/**
 * @description Validation Error
 */
export const marketCards422Schema = z.lazy(() => HTTPValidationErrorSchema)

export const marketCardsQueryResponseSchema = z.lazy(() => marketCards200Schema)
