/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4"

export const meResponseSchema = z.object({
  id: z.string(),
  email: z.union([z.string(), z.null()]),
})
