/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { meResponseSchema } from "./meResponseSchema"
import { z } from "zod/v4"

/**
 * @description Successful Response
 */
export const me200Schema = z.lazy(() => meResponseSchema)

export const meQueryResponseSchema = z.lazy(() => me200Schema)
