/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { messageRoleSchema } from "./messageRoleSchema"
import { z } from "zod/v4"

export const messageViewSchema = z.object({
  id: z.uuid(),
  get role() {
    return messageRoleSchema
  },
  text: z.string(),
  created_at: z.iso.datetime(),
})
