/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { HTTPValidationErrorSchema } from "./HTTPValidationErrorSchema";
import { newsEntrySchema } from "./newsEntrySchema";
import { z } from "zod/v4";

export const newsFeedSchema = z.object({
  get entries() {
    return z.array(
      newsEntrySchema.describe(
        "Something that happened, told from the reader's side.",
      ),
    );
  },
  waiting: z.int(),
});

export const newsFeedQueryParamsSchema = z.object({
  limit: z.coerce.number().int().min(1).max(50).default(20),
});

/**
 * @description Successful Response
 */
export const newsFeed200Schema = z.lazy(() => newsFeedSchema);

/**
 * @description Validation Error
 */
export const newsFeed422Schema = z.lazy(() => HTTPValidationErrorSchema);

export const newsFeedQueryResponseSchema = z.lazy(() => newsFeed200Schema);
