/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { cardViewSchema } from "./cardViewSchema"
import { z } from "zod/v4"

/**
 * @description A card named in an offer.\n\nNo copy count, unlike a match: a match reports what is available to trade,\nan offer names which cards are on the table.
 */
export const offerCardViewSchema = z
  .object({
    get card() {
      return cardViewSchema.describe(
        "A card with both layers: what is printed, and the species it depicts."
      )
    },
    price_usd: z.union([
      z.string().regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/),
      z.null(),
    ]),
  })
  .describe(
    "A card named in an offer.\n\nNo copy count, unlike a match: a match reports what is available to trade,\nan offer names which cards are on the table."
  )
