/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4"

/**
 * @description One collector number the user holds, and what that card is.\n\nThe type travels with the number because the client draws coverage as a strip\nof type-coloured slots; without it every owned card renders the same.
 */
export const ownedSlotSchema = z
  .object({
    number: z.string(),
    type: z.union([z.string(), z.null()]),
  })
  .describe(
    "One collector number the user holds, and what that card is.\n\nThe type travels with the number because the client draws coverage as a strip\nof type-coloured slots; without it every owned card renders the same."
  )
