/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { marketCardViewSchema } from "./marketCardViewSchema"
import { z } from "zod/v4"

export const pageMarketCardViewSchema = z.object({
  get items() {
    return z.array(
      marketCardViewSchema.describe(
        "A catalog card plus how many copies the reader holds. Zero is a real\nanswer here, not a missing one: the whole grid is owned against unowned."
      )
    )
  },
  total: z.int(),
  limit: z.int(),
  offset: z.int(),
})
