/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { collectorViewSchema } from "./collectorViewSchema"
import { z } from "zod/v4"

export const pageCollectorViewSchema = z.object({
  get items() {
    return z.array(
      collectorViewSchema.describe(
        "Another collector, described only by what could move between you.\n\nTheir collection stays theirs: what is published is how much is spare and\nhow much of it either of you is short of."
      )
    )
  },
  total: z.int(),
  limit: z.int(),
  offset: z.int(),
})
