/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { collectionItemViewSchema } from "./collectionItemViewSchema"
import { z } from "zod/v4"

export const pageCollectionItemViewSchema = z.object({
  get items() {
    return z.array(collectionItemViewSchema)
  },
  total: z.int(),
  limit: z.int(),
  offset: z.int(),
})
