/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { threadViewSchema } from "./threadViewSchema"
import { z } from "zod/v4"

export const pageThreadViewSchema = z.object({
  get items() {
    return z.array(
      threadViewSchema.describe(
        'A conversation as one of its two participants sees it.\n\n`id` is null for a conversation nobody has started. The partner is the\naddress, not the thread, so a collector can be opened and written to before\nany row exists — which is what keeps an abandoned "Mensaje" click from\nleaving an empty thread in everyone\'s list.'
      )
    )
  },
  total: z.int(),
  limit: z.int(),
  offset: z.int(),
})
