/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { directMessageViewSchema } from "./directMessageViewSchema"
import { z } from "zod/v4"

export const pageDirectMessageViewSchema = z.object({
  get items() {
    return z.array(
      directMessageViewSchema.describe(
        "One message, told from the reader's side.\n\n`mine` is resolved per reader rather than stored: the same row is on the\nleft for one of the two and on the right for the other."
      )
    )
  },
  total: z.int(),
  limit: z.int(),
  offset: z.int(),
})
