/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { tradeOfferViewSchema } from "./tradeOfferViewSchema"
import { z } from "zod/v4"

export const pageTradeOfferViewSchema = z.object({
  get items() {
    return z.array(
      tradeOfferViewSchema.describe(
        "An offer told from the reader's side.\n\n`you_give` and `you_get` swap meaning depending on who is looking, so the\nservice resolves them per reader rather than storing them that way."
      )
    )
  },
  total: z.int(),
  limit: z.int(),
  offset: z.int(),
})
