/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4"

/**
 * @description What the holdings cost against what they are worth now.\n\nMeasured only over the copies with a recorded cost, and it says how many\nthose are: a return computed over half a collection would otherwise read as\na return over all of it.
 */
export const portfolioReturnSchema = z
  .object({
    cost_basis: z.string().regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/),
    market_value: z.string().regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/),
    absolute: z.string().regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/),
    percent: z.number(),
    positions: z.int(),
    positions_without_cost: z.int(),
  })
  .describe(
    "What the holdings cost against what they are worth now.\n\nMeasured only over the copies with a recorded cost, and it says how many\nthose are: a return computed over half a collection would otherwise read as\na return over all of it."
  )
