/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { cardViewSchema } from "./cardViewSchema"
import { z } from "zod/v4"

/**
 * @description One held card as a position: what it cost, what it is worth now, and how\nmuch of the portfolio rests on it.\n\nCost and gain are measured over the copies carrying a recorded cost, and\n`costed_quantity` says how many those are: a copy bought before costs were\ntracked would otherwise land on the value side of the subtraction alone and\nread as pure profit.
 */
export const positionViewSchema = z
  .object({
    get card() {
      return cardViewSchema.describe(
        "A card with both layers: what is printed, and the species it depicts."
      )
    },
    quantity: z.int(),
    costed_quantity: z.int(),
    unit_cost_usd: z.union([
      z.string().regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/),
      z.null(),
    ]),
    cost_basis: z.union([
      z.string().regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/),
      z.null(),
    ]),
    market_value: z.union([
      z.string().regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/),
      z.null(),
    ]),
    gain_absolute: z.union([
      z.string().regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/),
      z.null(),
    ]),
    gain_percent: z.union([z.number(), z.null()]),
    portfolio_share: z.number(),
  })
  .describe(
    "One held card as a position: what it cost, what it is worth now, and how\nmuch of the portfolio rests on it.\n\nCost and gain are measured over the copies carrying a recorded cost, and\n`costed_quantity` says how many those are: a copy bought before costs were\ntracked would otherwise land on the value side of the subtraction alone and\nread as pure profit."
  )
