/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4"

/**
 * @description One durable fact the assistant learned, as its owner can read it.\n\nExposed so the user can see what is being remembered about them and delete\nany of it: the agent writes here without being asked, and a memory nobody\ncan inspect is one nobody agreed to.
 */
export const preferenceViewSchema = z
  .object({
    key: z.string(),
    value: z.object({}).catchall(z.any()),
  })
  .describe(
    "One durable fact the assistant learned, as its owner can read it.\n\nExposed so the user can see what is being remembered about them and delete\nany of it: the agent writes here without being asked, and a memory nobody\ncan inspect is one nobody agreed to."
  )
