/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4";

/**
 * @description A card in a proposal, carrying enough of itself to be drawn.\n\nThe simulator shows cards, not names, and a proposal that arrived as ids\nwould have to fetch each one back before it could render.
 */
export const proposedLegSchema = z
  .object({
    card_id: z.string(),
    card_name: z.string(),
    set_name: z.optional(z.string().default("")),
    image_url: z.optional(z.union([z.string(), z.null()])),
    category: z.optional(z.string().default("Pokemon")),
    price_usd: z.optional(
      z.union([z.string().regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/), z.null()]),
    ),
    owned: z.optional(z.int().default(1)),
    quantity: z.optional(z.int().default(1)),
  })
  .describe(
    "A card in a proposal, carrying enough of itself to be drawn.\n\nThe simulator shows cards, not names, and a proposal that arrived as ids\nwould have to fetch each one back before it could render.",
  );
