/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { HTTPValidationErrorSchema } from "./HTTPValidationErrorSchema";
import { tradeAdviceRequestSchema } from "./tradeAdviceRequestSchema";
import { tradeAdviceSchema } from "./tradeAdviceSchema";
import { z } from "zod/v4";

/**
 * @description Successful Response
 */
export const proposeTrade200Schema = z
  .lazy(() => tradeAdviceSchema)
  .describe(
    "A swap the assistant thinks is worth simulating.\n\nIt proposes and explains; it never sends anything. The reader loads it into\nthe simulator, which is where the numbers come from.",
  );

/**
 * @description Validation Error
 */
export const proposeTrade422Schema = z.lazy(() => HTTPValidationErrorSchema);

export const proposeTradeMutationRequestSchema = z.lazy(
  () => tradeAdviceRequestSchema,
);

export const proposeTradeMutationResponseSchema = z.lazy(
  () => proposeTrade200Schema,
);
