/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { cardConditionSchema } from "./cardConditionSchema"
import { cardViewSchema } from "./cardViewSchema"
import { z } from "zod/v4"

/**
 * @description A narrower view than the owner\'s own.\n\nNotes are free text the user wrote for themselves, and acquisition dates\ndescribe their habits; neither belongs on a page anyone with the link can\nopen. Reusing the private view here would have published both.
 */
export const publicItemViewSchema = z
  .object({
    id: z.uuid(),
    quantity: z.int(),
    get condition() {
      return cardConditionSchema
    },
    get card() {
      return cardViewSchema.describe(
        "A card with both layers: what is printed, and the species it depicts."
      )
    },
  })
  .describe(
    "A narrower view than the owner's own.\n\nNotes are free text the user wrote for themselves, and acquisition dates\ndescribe their habits; neither belongs on a page anyone with the link can\nopen. Reusing the private view here would have published both."
  )
