/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { HTTPValidationErrorSchema } from "./HTTPValidationErrorSchema"
import { createListingRequestSchema } from "./createListingRequestSchema"
import { tradeListingViewSchema } from "./tradeListingViewSchema"
import { z } from "zod/v4"

/**
 * @description Successful Response
 */
export const publishListing201Schema = z
  .lazy(() => tradeListingViewSchema)
  .describe(
    "A listing as one reader sees it.\n\nSides are named from the publisher, who is fixed, rather than from the\nreader, who is not. `balance` is what taking it would be worth — positive\nmeans the taker comes out ahead — and it is the same number for everyone.\n\n`available` is the publisher's half of the promise still standing, and\n`can_fulfil` the reader's: both have to be true for the listing to be\ntakeable, and a listing whose publisher has since traded away what it names\nis shown rather than hidden, so the board does not appear to lose rows."
  )

/**
 * @description Validation Error
 */
export const publishListing422Schema = z.lazy(() => HTTPValidationErrorSchema)

export const publishListingMutationRequestSchema = z
  .lazy(() => createListingRequestSchema)
  .describe(
    "Wanted cards are ids alone: a state can only be promised by whoever holds\nthe card, and on this side nobody holds it yet."
  )

export const publishListingMutationResponseSchema = z.lazy(
  () => publishListing201Schema
)
