/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { publicItemViewSchema } from "./publicItemViewSchema"
import { setCoverageSchema } from "./setCoverageSchema"
import { typeCountSchema } from "./typeCountSchema"
import { z } from "zod/v4"

export const publicCollectionSchema = z.object({
  total_cards: z.int(),
  total_groups: z.int(),
  get types() {
    return z.array(typeCountSchema)
  },
  get sets() {
    return z.array(setCoverageSchema)
  },
  get items() {
    return z.array(
      publicItemViewSchema.describe(
        "A narrower view than the owner's own.\n\nNotes are free text the user wrote for themselves, and acquisition dates\ndescribe their habits; neither belongs on a page anyone with the link can\nopen. Reusing the private view here would have published both."
      )
    )
  },
})
