/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { HTTPValidationErrorSchema } from "./HTTPValidationErrorSchema"
import { publicCollectionSchema } from "./publicCollectionSchema"
import { z } from "zod/v4"

export const readSharedCollectionPathParamsSchema = z.object({
  token: z.string(),
})

/**
 * @description Successful Response
 */
export const readSharedCollection200Schema = z.lazy(
  () => publicCollectionSchema
)

/**
 * @description Validation Error
 */
export const readSharedCollection422Schema = z.lazy(
  () => HTTPValidationErrorSchema
)

export const readSharedCollectionQueryResponseSchema = z.lazy(
  () => readSharedCollection200Schema
)
