/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { HTTPValidationErrorSchema } from "./HTTPValidationErrorSchema"
import { z } from "zod/v4"

export const removeItemPathParamsSchema = z.object({
  item_id: z.uuid(),
})

/**
 * @description Successful Response
 */
export const removeItem204Schema = z.any()

/**
 * @description Validation Error
 */
export const removeItem422Schema = z.lazy(() => HTTPValidationErrorSchema)

export const removeItemMutationResponseSchema = z.lazy(
  () => removeItem204Schema
)
