/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { HTTPValidationErrorSchema } from "./HTTPValidationErrorSchema"
import { z } from "zod/v4"

export const removeFromWishlistPathParamsSchema = z.object({
  item_id: z.uuid(),
})

/**
 * @description Successful Response
 */
export const removeFromWishlist204Schema = z.any()

/**
 * @description Validation Error
 */
export const removeFromWishlist422Schema = z.lazy(
  () => HTTPValidationErrorSchema
)

export const removeFromWishlistMutationResponseSchema = z.lazy(
  () => removeFromWishlist204Schema
)
