/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { HTTPValidationErrorSchema } from "./HTTPValidationErrorSchema"
import { speciesViewSchema } from "./speciesViewSchema"
import { z } from "zod/v4"

export const searchSpeciesQueryParamsSchema = z.object({
  name: z.optional(z.union([z.string(), z.null()])),
  type: z.optional(z.union([z.string(), z.null()])),
  generation: z.optional(z.union([z.coerce.number().int(), z.null()])),
  limit: z.coerce.number().int().min(1).max(200).default(50),
})

/**
 * @description Successful Response
 */
export const searchSpecies200Schema = z.array(z.lazy(() => speciesViewSchema))

/**
 * @description Validation Error
 */
export const searchSpecies422Schema = z.lazy(() => HTTPValidationErrorSchema)

export const searchSpeciesQueryResponseSchema = z.lazy(
  () => searchSpecies200Schema
)
