/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4"

export const sendMessageRequestSchema = z.object({
  to_user_id: z.string(),
  body: z.string().min(1).max(2000),
})
