/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { HTTPValidationErrorSchema } from "./HTTPValidationErrorSchema"
import { chatRequestSchema } from "./chatRequestSchema"
import { z } from "zod/v4"

/**
 * @description Successful Response
 */
export const sendMessage200Schema = z.any()

/**
 * @description Validation Error
 */
export const sendMessage422Schema = z.lazy(() => HTTPValidationErrorSchema)

export const sendMessageMutationRequestSchema = z.lazy(() => chatRequestSchema)

export const sendMessageMutationResponseSchema = z.lazy(
  () => sendMessage200Schema
)
