/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { HTTPValidationErrorSchema } from "./HTTPValidationErrorSchema"
import { directMessageViewSchema } from "./directMessageViewSchema"
import { sendMessageRequestSchema } from "./sendMessageRequestSchema"
import { z } from "zod/v4"

/**
 * @description Successful Response
 */
export const sendDirectMessage201Schema = z
  .lazy(() => directMessageViewSchema)
  .describe(
    "One message, told from the reader's side.\n\n`mine` is resolved per reader rather than stored: the same row is on the\nleft for one of the two and on the right for the other."
  )

/**
 * @description Validation Error
 */
export const sendDirectMessage422Schema = z.lazy(
  () => HTTPValidationErrorSchema
)

export const sendDirectMessageMutationRequestSchema = z.lazy(
  () => sendMessageRequestSchema
)

export const sendDirectMessageMutationResponseSchema = z.lazy(
  () => sendDirectMessage201Schema
)
