/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { ownedSlotSchema } from "./ownedSlotSchema"
import { z } from "zod/v4"

export const setCoverageSchema = z.object({
  set_id: z.string(),
  set_name: z.string(),
  printed_total: z.int(),
  owned: z.int(),
  get owned_slots() {
    return z.array(
      ownedSlotSchema.describe(
        "One collector number the user holds, and what that card is.\n\nThe type travels with the number because the client draws coverage as a strip\nof type-coloured slots; without it every owned card renders the same."
      )
    )
  },
})
