/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4"

export const shareLinkViewSchema = z.object({
  id: z.uuid(),
  token: z.string(),
  created_at: z.iso.datetime(),
})
