/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { HTTPValidationErrorSchema } from "./HTTPValidationErrorSchema"
import { tradeSimulationRequestSchema } from "./tradeSimulationRequestSchema"
import { tradeSimulationSchema } from "./tradeSimulationSchema"
import { z } from "zod/v4"

/**
 * @description Successful Response
 */
export const simulateTrade200Schema = z
  .lazy(() => tradeSimulationSchema)
  .describe(
    "The portfolio either side of a swap that has not happened.\n\nCards with no market price are named rather than valued at zero, because a\nswap resting on them is not the even trade the totals would claim."
  )

/**
 * @description Validation Error
 */
export const simulateTrade422Schema = z.lazy(() => HTTPValidationErrorSchema)

export const simulateTradeMutationRequestSchema = z.lazy(
  () => tradeSimulationRequestSchema
)

export const simulateTradeMutationResponseSchema = z.lazy(
  () => simulateTrade200Schema
)
