/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { cardViewSchema } from "./cardViewSchema"
import { conditionCountSchema } from "./conditionCountSchema"
import { z } from "zod/v4"

/**
 * @description A card free to trade, seen by someone who might want it.
 */
export const spareCardSchema = z
  .object({
    get card() {
      return cardViewSchema.describe(
        "A card with both layers: what is printed, and the species it depicts."
      )
    },
    copies: z.int(),
    price_usd: z.union([
      z.string().regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/),
      z.null(),
    ]),
    wanted: z.boolean(),
    get conditions() {
      return z.array(conditionCountSchema)
    },
  })
  .describe("A card free to trade, seen by someone who might want it.")
