/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { HTTPValidationErrorSchema } from "./HTTPValidationErrorSchema"
import { evolutionMemberViewSchema } from "./evolutionMemberViewSchema"
import { z } from "zod/v4"

export const speciesEvolutionsPathParamsSchema = z.object({
  species_id: z.coerce.number().int(),
})

/**
 * @description Successful Response
 */
export const speciesEvolutions200Schema = z.array(
  z
    .lazy(() => evolutionMemberViewSchema)
    .describe("One species of an evolution family, as its own Pokedex entry.")
)

/**
 * @description Validation Error
 */
export const speciesEvolutions422Schema = z.lazy(
  () => HTTPValidationErrorSchema
)

export const speciesEvolutionsQueryResponseSchema = z.lazy(
  () => speciesEvolutions200Schema
)
