/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4"

export const speciesViewSchema = z.object({
  id: z.int(),
  name: z.string(),
  generation: z.int(),
  types: z.array(z.string()),
  stats: z.object({}).catchall(z.int()),
  evolution_chain_id: z.union([z.int(), z.null()]),
  sprite_url: z.union([z.string(), z.null()]),
})
