/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4"

/**
 * @description A conversation as one of its two participants sees it.\n\n`id` is null for a conversation nobody has started. The partner is the\naddress, not the thread, so a collector can be opened and written to before\nany row exists — which is what keeps an abandoned \"Mensaje\" click from\nleaving an empty thread in everyone\'s list.
 */
export const threadViewSchema = z
  .object({
    id: z.union([z.uuid(), z.null()]),
    partner_id: z.string(),
    partner_name: z.union([z.string(), z.null()]),
    last_body: z.union([z.string(), z.null()]),
    last_at: z.union([z.iso.datetime(), z.null()]),
    last_mine: z.boolean(),
    unread: z.int(),
  })
  .describe(
    'A conversation as one of its two participants sees it.\n\n`id` is null for a conversation nobody has started. The partner is the\naddress, not the thread, so a collector can be opened and written to before\nany row exists — which is what keeps an abandoned "Mensaje" click from\nleaving an empty thread in everyone\'s list.'
  )
