/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { tradeLegSchema } from "./tradeLegSchema"
import { z } from "zod/v4"

export const tradeSimulationRequestSchema = z.object({
  get give() {
    return z.array(tradeLegSchema).max(50).optional()
  },
  get receive() {
    return z.array(tradeLegSchema).max(50).optional()
  },
})
