/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4"

export const tradeLegSchema = z.object({
  card_id: z.string(),
  quantity: z.optional(z.int().min(1).default(1)),
})
