/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { proposedLegSchema } from "./proposedLegSchema";
import { z } from "zod/v4";

/**
 * @description A swap the assistant thinks is worth simulating.\n\nIt proposes and explains; it never sends anything. The reader loads it into\nthe simulator, which is where the numbers come from.
 */
export const tradeAdviceSchema = z
  .object({
    get give() {
      return z.array(
        proposedLegSchema.describe(
          "A card in a proposal, carrying enough of itself to be drawn.\n\nThe simulator shows cards, not names, and a proposal that arrived as ids\nwould have to fetch each one back before it could render.",
        ),
      );
    },
    get receive() {
      return z.array(
        proposedLegSchema.describe(
          "A card in a proposal, carrying enough of itself to be drawn.\n\nThe simulator shows cards, not names, and a proposal that arrived as ids\nwould have to fetch each one back before it could render.",
        ),
      );
    },
    rationale: z.string(),
  })
  .describe(
    "A swap the assistant thinks is worth simulating.\n\nIt proposes and explains; it never sends anything. The reader loads it into\nthe simulator, which is where the numbers come from.",
  );
