/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { cardViewSchema } from "./cardViewSchema"
import { z } from "zod/v4"

/**
 * @description A card that could change hands, and how many copies are free to move.
 */
export const tradeCardSchema = z
  .object({
    get card() {
      return cardViewSchema.describe(
        "A card with both layers: what is printed, and the species it depicts."
      )
    },
    copies: z.int(),
    price_usd: z.union([
      z.string().regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/),
      z.null(),
    ]),
  })
  .describe(
    "A card that could change hands, and how many copies are free to move."
  )
