/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { portfolioConcentrationSchema } from "./portfolioConcentrationSchema"
import { z } from "zod/v4"

/**
 * @description The portfolio either side of a swap that has not happened.\n\nCards with no market price are named rather than valued at zero, because a\nswap resting on them is not the even trade the totals would claim.
 */
export const tradeSimulationSchema = z
  .object({
    get before() {
      return portfolioConcentrationSchema.describe(
        "How few cards carry the value.\n\n`cards_for_half` is the count of positions, largest first, that reach half\nthe portfolio: one number for how exposed the whole thing is to a handful of\ncards. Unpriced holdings are counted but never valued."
      )
    },
    get after() {
      return portfolioConcentrationSchema.describe(
        "How few cards carry the value.\n\n`cards_for_half` is the count of positions, largest first, that reach half\nthe portfolio: one number for how exposed the whole thing is to a handful of\ncards. Unpriced holdings are counted but never valued."
      )
    },
    give_value: z.string().regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/),
    receive_value: z.string().regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/),
    value_delta: z.string().regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/),
    unpriced_cards: z.array(z.string()),
  })
  .describe(
    "The portfolio either side of a swap that has not happened.\n\nCards with no market price are named rather than valued at zero, because a\nswap resting on them is not the even trade the totals would claim."
  )
