/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { tradeCardSchema } from "./tradeCardSchema"
import { z } from "zod/v4"

/**
 * @description A counterparty who wants something spare, and has something wanted.\n\nOnly the cards on both sides of the overlap are named. What else the\ncounterparty holds, and what their collection is worth, stay theirs: this\nanswers whether a trade exists, not what someone owns.\n\nValues count one copy of each card. `balance` is what the trade is worth to\nthe reader — positive means they come out ahead — and it is reported rather\nthan balanced, because which cards even out a swap is the traders\' call.
 */
export const tradeMatchSchema = z
  .object({
    partner_id: z.string(),
    partner_name: z.union([z.string(), z.null()]),
    get you_give() {
      return z.array(
        tradeCardSchema.describe(
          "A card that could change hands, and how many copies are free to move."
        )
      )
    },
    get you_get() {
      return z.array(
        tradeCardSchema.describe(
          "A card that could change hands, and how many copies are free to move."
        )
      )
    },
    give_value: z.string().regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/),
    get_value: z.string().regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/),
    balance: z.string().regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/),
    unpriced: z.int(),
  })
  .describe(
    "A counterparty who wants something spare, and has something wanted.\n\nOnly the cards on both sides of the overlap are named. What else the\ncounterparty holds, and what their collection is worth, stay theirs: this\nanswers whether a trade exists, not what someone owns.\n\nValues count one copy of each card. `balance` is what the trade is worth to\nthe reader — positive means they come out ahead — and it is reported rather\nthan balanced, because which cards even out a swap is the traders' call."
  )
