/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { offerCardViewSchema } from "./offerCardViewSchema"
import { offerStatusSchema } from "./offerStatusSchema"
import { z } from "zod/v4"

/**
 * @description An offer told from the reader\'s side.\n\n`you_give` and `you_get` swap meaning depending on who is looking, so the\nservice resolves them per reader rather than storing them that way.
 */
export const tradeOfferViewSchema = z
  .object({
    id: z.uuid(),
    get status() {
      return offerStatusSchema
    },
    direction: z.enum(["sent", "received"]),
    partner_id: z.string(),
    partner_name: z.union([z.string(), z.null()]),
    get you_give() {
      return z.array(
        offerCardViewSchema.describe(
          "A card named in an offer.\n\nNo copy count, unlike a match: a match reports what is available to trade,\nan offer names which cards are on the table."
        )
      )
    },
    get you_get() {
      return z.array(
        offerCardViewSchema.describe(
          "A card named in an offer.\n\nNo copy count, unlike a match: a match reports what is available to trade,\nan offer names which cards are on the table."
        )
      )
    },
    give_value: z.string().regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/),
    get_value: z.string().regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/),
    balance: z.string().regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/),
    message: z.union([z.string(), z.null()]),
    created_at: z.iso.datetime(),
    responded_at: z.union([z.iso.datetime(), z.null()]),
  })
  .describe(
    "An offer told from the reader's side.\n\n`you_give` and `you_get` swap meaning depending on who is looking, so the\nservice resolves them per reader rather than storing them that way."
  )
