/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { listingCardViewSchema } from "./listingCardViewSchema"
import { listingStatusSchema } from "./listingStatusSchema"
import { z } from "zod/v4"

/**
 * @description A listing as one reader sees it.\n\nSides are named from the publisher, who is fixed, rather than from the\nreader, who is not. `balance` is what taking it would be worth — positive\nmeans the taker comes out ahead — and it is the same number for everyone.\n\n`available` is the publisher\'s half of the promise still standing, and\n`can_fulfil` the reader\'s: both have to be true for the listing to be\ntakeable, and a listing whose publisher has since traded away what it names\nis shown rather than hidden, so the board does not appear to lose rows.
 */
export const tradeListingViewSchema = z
  .object({
    id: z.uuid(),
    owner_id: z.string(),
    owner_name: z.union([z.string(), z.null()]),
    is_mine: z.boolean(),
    get status() {
      return listingStatusSchema
    },
    get gives() {
      return z.array(
        listingCardViewSchema.describe(
          "A card named on a listing.\n\n`condition` is null on the wanted side, and so is `adjusted_usd` with it:\nnobody has said yet which copy would arrive, so the market price is the only\nhonest figure there."
        )
      )
    },
    get wants() {
      return z.array(
        listingCardViewSchema.describe(
          "A card named on a listing.\n\n`condition` is null on the wanted side, and so is `adjusted_usd` with it:\nnobody has said yet which copy would arrive, so the market price is the only\nhonest figure there."
        )
      )
    },
    give_value: z.string().regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/),
    want_value: z.string().regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/),
    balance: z.string().regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/),
    available: z.boolean(),
    can_fulfil: z.boolean(),
    missing: z.int(),
    note: z.union([z.string(), z.null()]),
    offer_id: z.union([z.uuid(), z.null()]),
    created_at: z.iso.datetime(),
    taken_at: z.union([z.iso.datetime(), z.null()]),
  })
  .describe(
    "A listing as one reader sees it.\n\nSides are named from the publisher, who is fixed, rather than from the\nreader, who is not. `balance` is what taking it would be worth — positive\nmeans the taker comes out ahead — and it is the same number for everyone.\n\n`available` is the publisher's half of the promise still standing, and\n`can_fulfil` the reader's: both have to be true for the listing to be\ntakeable, and a listing whose publisher has since traded away what it names\nis shown rather than hidden, so the board does not appear to lose rows."
  )
