/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4";

export const tradeAdviceRequestSchema = z.object({
  goal: z.optional(z.union([z.string(), z.null()])),
});
