/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { cardConditionSchema } from "./cardConditionSchema"
import { z } from "zod/v4"

export const updateItemRequestSchema = z.object({
  quantity: z.optional(z.union([z.int(), z.null()])),
  get condition() {
    return z.union([cardConditionSchema, z.null()]).optional()
  },
  notes: z.optional(z.union([z.string(), z.null()])),
})
