/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { cardConditionSchema } from "./cardConditionSchema"
import { z } from "zod/v4"

export const updateItemRequestSchema = z.object({
  quantity: z.optional(z.union([z.int(), z.null()])),
  get condition() {
    return z.union([cardConditionSchema, z.null()]).optional()
  },
  notes: z.optional(z.union([z.string(), z.null()])),
  unit_cost_usd: z.optional(
    z.union([
      z.number(),
      z
        .string()
        .regex(
          /^(?!^[-+.]*$)[+-]?0*(?:\d{0,8}|(?=[\d.]{1,11}0*$)\d{0,8}\.\d{0,2}0*$)/
        ),
      z.null(),
    ])
  ),
})
