/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4"

/**
 * @description What the model saw, kept short enough to read beside the cards.
 */
export const visualComparisonSchema = z
  .object({
    summary: z.string().max(400),
    differences: z.optional(z.array(z.string()).max(4)),
  })
  .describe("What the model saw, kept short enough to read beside the cards.")
