"""catalog and collection tables

Revision ID: 6bdeccb4af7f
Revises: bb4e34c86509
Create Date: 2026-08-11 21:57:37.798246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6bdeccb4af7f'
down_revision: Union[str, Sequence[str], None] = 'bb4e34c86509'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_set',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('series', sa.Text(), nullable=True),
    sa.Column('printed_total', sa.SmallInteger(), nullable=False),
    sa.Column('total', sa.SmallInteger(), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('symbol_url', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='pokedex'
    )
    op.create_index(op.f('ix_pokedex_card_set_printed_total'), 'card_set', ['printed_total'], unique=False, schema='pokedex')
    op.create_table('species',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('generation', sa.SmallInteger(), nullable=False),
    sa.Column('types', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('evolution_chain_id', sa.Integer(), nullable=True),
    sa.Column('sprite_url', sa.Text(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='pokedex'
    )
    op.create_index(op.f('ix_pokedex_species_evolution_chain_id'), 'species', ['evolution_chain_id'], unique=False, schema='pokedex')
    op.create_index(op.f('ix_pokedex_species_generation'), 'species', ['generation'], unique=False, schema='pokedex')
    op.create_index(op.f('ix_pokedex_species_name'), 'species', ['name'], unique=True, schema='pokedex')
    op.create_index('ix_species_types', 'species', ['types'], unique=False, schema='pokedex', postgresql_using='gin')
    op.create_table('card',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('set_id', sa.String(length=64), nullable=False),
    sa.Column('species_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=16), nullable=False),
    sa.Column('number', sa.String(length=16), nullable=False),
    sa.Column('number_prefix', sa.String(length=16), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('name_normalized', sa.Text(), nullable=False),
    sa.Column('rarity', sa.String(length=64), nullable=True),
    sa.Column('variants', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('hp', sa.SmallInteger(), nullable=True),
    sa.Column('image_small_url', sa.Text(), nullable=True),
    sa.Column('image_large_url', sa.Text(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['set_id'], ['pokedex.card_set.id'], ),
    sa.ForeignKeyConstraint(['species_id'], ['pokedex.species.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='pokedex'
    )
    op.create_index('ix_card_name_normalized_trgm', 'card', ['name_normalized'], unique=False, schema='pokedex', postgresql_using='gin', postgresql_ops={'name_normalized': 'gin_trgm_ops'})
    op.create_index(op.f('ix_pokedex_card_category'), 'card', ['category'], unique=False, schema='pokedex')
    op.create_index(op.f('ix_pokedex_card_number_prefix'), 'card', ['number_prefix'], unique=False, schema='pokedex')
    op.create_index(op.f('ix_pokedex_card_rarity'), 'card', ['rarity'], unique=False, schema='pokedex')
    op.create_index(op.f('ix_pokedex_card_set_id'), 'card', ['set_id'], unique=False, schema='pokedex')
    op.create_index(op.f('ix_pokedex_card_species_id'), 'card', ['species_id'], unique=False, schema='pokedex')
    op.create_table('collection_item',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('card_id', sa.String(length=64), nullable=False),
    sa.Column('condition', sa.Enum('mint', 'near_mint', 'lightly_played', 'moderately_played', 'heavily_played', 'damaged', name='card_condition', schema='pokedex'), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('is_graded', sa.Boolean(), nullable=False),
    sa.Column('grade', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('acquired_at', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(is_graded AND grade IS NOT NULL) OR (NOT is_graded AND grade IS NULL)', name='ck_collection_item_grade_only_when_graded'),
    sa.CheckConstraint('quantity > 0', name='ck_collection_item_quantity_positive'),
    sa.ForeignKeyConstraint(['card_id'], ['pokedex.card.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['auth.user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'card_id', 'condition', 'language', 'is_graded', 'grade', name='uq_collection_item_group', postgresql_nulls_not_distinct=True),
    schema='pokedex'
    )
    op.create_index(op.f('ix_pokedex_collection_item_card_id'), 'collection_item', ['card_id'], unique=False, schema='pokedex')
    op.create_index(op.f('ix_pokedex_collection_item_user_id'), 'collection_item', ['user_id'], unique=False, schema='pokedex')
    op.create_table('scan',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('image_key', sa.Text(), nullable=False),
    sa.Column('extracted', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('candidate_ids', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('resolved_card_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('pending', 'extracted', 'ambiguous', 'resolved', 'failed', name='scan_status', schema='pokedex'), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['resolved_card_id'], ['pokedex.card.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['auth.user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='pokedex'
    )
    op.create_index(op.f('ix_pokedex_scan_created_at'), 'scan', ['created_at'], unique=False, schema='pokedex')
    op.create_index(op.f('ix_pokedex_scan_status'), 'scan', ['status'], unique=False, schema='pokedex')
    op.create_index(op.f('ix_pokedex_scan_user_id'), 'scan', ['user_id'], unique=False, schema='pokedex')
    op.create_table('wishlist_item',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('card_id', sa.String(length=64), nullable=False),
    sa.Column('priority', sa.SmallInteger(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('added_by', sa.Enum('user', 'agent', name='wishlist_source', schema='pokedex'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['pokedex.card.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['auth.user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'card_id', name='uq_wishlist_item_user_card'),
    schema='pokedex'
    )
    op.create_index(op.f('ix_pokedex_wishlist_item_card_id'), 'wishlist_item', ['card_id'], unique=False, schema='pokedex')
    op.create_index(op.f('ix_pokedex_wishlist_item_user_id'), 'wishlist_item', ['user_id'], unique=False, schema='pokedex')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pokedex_wishlist_item_user_id'), table_name='wishlist_item', schema='pokedex')
    op.drop_index(op.f('ix_pokedex_wishlist_item_card_id'), table_name='wishlist_item', schema='pokedex')
    op.drop_table('wishlist_item', schema='pokedex')
    op.drop_index(op.f('ix_pokedex_scan_user_id'), table_name='scan', schema='pokedex')
    op.drop_index(op.f('ix_pokedex_scan_status'), table_name='scan', schema='pokedex')
    op.drop_index(op.f('ix_pokedex_scan_created_at'), table_name='scan', schema='pokedex')
    op.drop_table('scan', schema='pokedex')
    op.drop_index(op.f('ix_pokedex_collection_item_user_id'), table_name='collection_item', schema='pokedex')
    op.drop_index(op.f('ix_pokedex_collection_item_card_id'), table_name='collection_item', schema='pokedex')
    op.drop_table('collection_item', schema='pokedex')
    op.drop_index(op.f('ix_pokedex_card_species_id'), table_name='card', schema='pokedex')
    op.drop_index(op.f('ix_pokedex_card_set_id'), table_name='card', schema='pokedex')
    op.drop_index(op.f('ix_pokedex_card_rarity'), table_name='card', schema='pokedex')
    op.drop_index(op.f('ix_pokedex_card_number_prefix'), table_name='card', schema='pokedex')
    op.drop_index(op.f('ix_pokedex_card_category'), table_name='card', schema='pokedex')
    op.drop_index('ix_card_name_normalized_trgm', table_name='card', schema='pokedex', postgresql_using='gin', postgresql_ops={'name_normalized': 'gin_trgm_ops'})
    op.drop_table('card', schema='pokedex')
    op.drop_index('ix_species_types', table_name='species', schema='pokedex', postgresql_using='gin')
    op.drop_index(op.f('ix_pokedex_species_name'), table_name='species', schema='pokedex')
    op.drop_index(op.f('ix_pokedex_species_generation'), table_name='species', schema='pokedex')
    op.drop_index(op.f('ix_pokedex_species_evolution_chain_id'), table_name='species', schema='pokedex')
    op.drop_table('species', schema='pokedex')
    op.drop_index(op.f('ix_pokedex_card_set_printed_total'), table_name='card_set', schema='pokedex')
    op.drop_table('card_set', schema='pokedex')

    # Alembic drops tables but never the enum types they used, which makes the
    # next upgrade fail with DuplicateObject.
    for enum_name in ("card_condition", "scan_status", "wishlist_source"):
        sa.Enum(name=enum_name, schema="pokedex").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
