"""price in usd

Revision ID: 74d39a548989
Revises: e2e3d803b64f
Create Date: 2026-08-12 10:02:39.744606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74d39a548989'
down_revision: Union[str, Sequence[str], None] = 'e2e3d803b64f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('price_usd', sa.Numeric(precision=10, scale=2), nullable=True), schema='pokedex')
    op.drop_column('card', 'price_eur', schema='pokedex')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('price_eur', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True), schema='pokedex')
    op.drop_column('card', 'price_usd', schema='pokedex')
    # ### end Alembic commands ###
