"""species trivia

Revision ID: 93ad6cd56e10
Revises: 74d39a548989
Create Date: 2026-08-12 12:52:56.316257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93ad6cd56e10'
down_revision: Union[str, Sequence[str], None] = '74d39a548989'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('species_trivia',
    sa.Column('species_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('model', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['species_id'], ['pokedex.species.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('species_id'),
    schema='pokedex'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('species_trivia', schema='pokedex')
    # ### end Alembic commands ###
