"""card market price

Revision ID: accab2983069
Revises: f10e26c5d508
Create Date: 2026-08-12 08:52:44.961178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'accab2983069'
down_revision: Union[str, Sequence[str], None] = 'f10e26c5d508'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('price_eur', sa.Numeric(precision=10, scale=2), nullable=True), schema='pokedex')
    op.add_column('card', sa.Column('price_updated_at', sa.DateTime(), nullable=True), schema='pokedex')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('card', 'price_updated_at', schema='pokedex')
    op.drop_column('card', 'price_eur', schema='pokedex')
    # ### end Alembic commands ###
