"""card price history

Revision ID: c8b10ea0425b
Revises: 93ad6cd56e10
Create Date: 2026-08-12 20:38:11.665983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8b10ea0425b'
down_revision: Union[str, Sequence[str], None] = '93ad6cd56e10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_price',
    sa.Column('card_id', sa.String(length=64), nullable=False),
    sa.Column('recorded_on', sa.Date(), nullable=False),
    sa.Column('price_usd', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['pokedex.card.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('card_id', 'recorded_on'),
    schema='pokedex'
    )
    op.create_index(op.f('ix_pokedex_card_price_recorded_on'), 'card_price', ['recorded_on'], unique=False, schema='pokedex')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pokedex_card_price_recorded_on'), table_name='card_price', schema='pokedex')
    op.drop_table('card_price', schema='pokedex')
    # ### end Alembic commands ###
