"""share link

Revision ID: e2e3d803b64f
Revises: accab2983069
Create Date: 2026-08-12 09:05:54.505723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2e3d803b64f'
down_revision: Union[str, Sequence[str], None] = 'accab2983069'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('share_link',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth.user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='pokedex'
    )
    op.create_index(op.f('ix_pokedex_share_link_token'), 'share_link', ['token'], unique=True, schema='pokedex')
    op.create_index(op.f('ix_pokedex_share_link_user_id'), 'share_link', ['user_id'], unique=False, schema='pokedex')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pokedex_share_link_user_id'), table_name='share_link', schema='pokedex')
    op.drop_index(op.f('ix_pokedex_share_link_token'), table_name='share_link', schema='pokedex')
    op.drop_table('share_link', schema='pokedex')
    # ### end Alembic commands ###
