"""conversation, message, user_preference

Revision ID: f10e26c5d508
Revises: 6bdeccb4af7f
Create Date: 2026-08-12 00:56:17.074627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f10e26c5d508'
down_revision: Union[str, Sequence[str], None] = '6bdeccb4af7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth.user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='pokedex'
    )
    op.create_index(op.f('ix_pokedex_conversation_user_id'), 'conversation', ['user_id'], unique=False, schema='pokedex')
    op.create_table('user_preference',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth.user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'key', name='uq_user_preference_key'),
    schema='pokedex'
    )
    op.create_index(op.f('ix_pokedex_user_preference_user_id'), 'user_preference', ['user_id'], unique=False, schema='pokedex')
    op.create_table('message',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('user', 'assistant', name='message_role', schema='pokedex'), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['pokedex.conversation.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='pokedex'
    )
    op.create_index('ix_message_conversation_created', 'message', ['conversation_id', 'created_at'], unique=False, schema='pokedex')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_message_conversation_created', table_name='message', schema='pokedex')
    op.drop_table('message', schema='pokedex')
    op.drop_index(op.f('ix_pokedex_user_preference_user_id'), table_name='user_preference', schema='pokedex')
    op.drop_table('user_preference', schema='pokedex')
    op.drop_index(op.f('ix_pokedex_conversation_user_id'), table_name='conversation', schema='pokedex')
    op.drop_table('conversation', schema='pokedex')

    # Alembic drops tables but never the enum types they used, which makes the
    # next upgrade fail with DuplicateObject.
    sa.Enum(name="message_role", schema="pokedex").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
